### ISSUE TITLE
Client::Session#load being called with String

### ISSUE THREAD

**Issue by djspiewak** [travis-ci/travis-ci#10006]
I get this error every time I try to run `travis logs` on a *completed* pull request build on [slamdata/quasar](https://github.com/slamdata/quasar):

```
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `each_pair' for #<String:0x00007fa98b1702a0>
Did you mean?  each_char
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/session.rb:139:in `load'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/session.rb:166:in `get'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/session.rb:319:in `fetch_one'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/session.rb:128:in `reload'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/entity.rb:208:in `load_attribute'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/entity.rb:194:in `relation'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/artifact.rb:51:in `body'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

Taking a quick glance at the source code, it looks like the culprit is someone is passing a `String` to `load`, when it actually expects a `Hash`.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
