### ISSUE TITLE
Failing to require gems on OSX

### ISSUE THREAD

**Issue by castwide** [travis-ci/travis-ci#10092]
A job configured to use Ruby 2.4 on OSX is failing to find required gems when it starts the specs. All other Linux jobs are passing.

First error message after `bundle exec rspec`:

```
An error occurred while loading ./spec/diagnostics/base_spec.rb.
Failure/Error: require 'rubocop'
LoadError:
  dlopen(/Users/travis/build/castwide/solargraph/vendor/bundle/ruby/2.4.0/gems/jaro_winkler-1.5.1-x86_64-darwin-17/lib/jaro_winkler/jaro_winkler_ext.bundle, 9): Library not loaded: /Users/travis/.rvm/rubies/ruby-2.4.1/lib/libruby.2.4.1.dylib
    Referenced from: /Users/travis/build/castwide/solargraph/vendor/bundle/ruby/2.4.0/gems/jaro_winkler-1.5.1-x86_64-darwin-17/lib/jaro_winkler/jaro_winkler_ext.bundle
    Reason: image not found - /Users/travis/build/castwide/solargraph/vendor/bundle/ruby/2.4.0/gems/jaro_winkler-1.5.1-x86_64-darwin-17/lib/jaro_winkler/jaro_winkler_ext.bundle
# ./vendor/bundle/ruby/2.4.0/gems/jaro_winkler-1.5.1-x86_64-darwin-17/lib/jaro_winkler.rb:6:in `require'
# ./vendor/bundle/ruby/2.4.0/gems/jaro_winkler-1.5.1-x86_64-darwin-17/lib/jaro_winkler.rb:6:in `<top (required)>'
# ./vendor/bundle/ruby/2.4.0/gems/rubocop-0.58.2/lib/rubocop/string_util.rb:3:in `require'
# ./vendor/bundle/ruby/2.4.0/gems/rubocop-0.58.2/lib/rubocop/string_util.rb:3:in `<top (required)>'
# ./vendor/bundle/ruby/2.4.0/gems/rubocop-0.58.2/lib/rubocop.rb:21:in `require_relative'
# ./vendor/bundle/ruby/2.4.0/gems/rubocop-0.58.2/lib/rubocop.rb:21:in `<top (required)>'
# ./lib/solargraph/diagnostics/rubocop.rb:1:in `require'
# ./lib/solargraph/diagnostics/rubocop.rb:1:in `<top (required)>'
# ./lib/solargraph/diagnostics.rb:44:in `require'
# ./lib/solargraph/diagnostics.rb:44:in `<module:Diagnostics>'
# ./lib/solargraph/diagnostics.rb:5:in `<module:Solargraph>'
# ./lib/solargraph/diagnostics.rb:1:in `<top (required)>'
# ./spec/diagnostics/base_spec.rb:1:in `require'
# ./spec/diagnostics/base_spec.rb:1:in `<top (required)>'
```

Job config:

```


{
  "os": "osx",
  "rvm": 2.4,
  "cache": [
    "bundler"
  ],
  "script": "bundle exec rspec",
  "language": "ruby",
  "before_script": "bundle exec yard gems",
  "before_install": [
    "bundle install"
  ]
}
```

Failed job: https://travis-ci.org/castwide/solargraph/jobs/425415532

**Comment by BanzaiMan** [comment]
If the build used to pass, please try removing the cache.

**Comment by castwide** [comment]
It started passing again this morning. If I run into the same problem, I'll try removing the cache first. Thanks for getting back to me.
