### ISSUE TITLE
S3 Deployment times out

### ISSUE THREAD

**Issue by alxdarksage** [travis-ci/travis-ci#10205]
This build was working with keys we've verified still work using the AWS CLI (`S3_ACCESS_KEY_ID` and `S3_SECRET_KEY` which are in the environment variable settings of the project):

```
language: ruby
install:
  - bundle install
script:
  - bundle exec jekyll build
branches:
  only:
    - release
deploy:
    - provider: s3
      access_key_id: ${S3_ACCESS_KEY_ID}
      secret_access_key: ${S3_SECRET_KEY}
      bucket: "developer.void.org"
      skip_cleanup: true
      acl: public_read
      detect_encoding: false
      endpoint: "https://developer.void.org.s3-website-us-east-1.amazonaws.com"
      region: "us-east-1"
      local_dir: _site
      on:
          branch: release    
```

At first this build broke because the endpoint did not include "https" (although this worked in prior builds). After changing this, we now get the following error:

```
uploading "src/components.js" with {:content_type=>"application/javascript", :acl=>"public-read"}
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:879:in `initialize': execution expired (Seahorse::Client::NetworkingError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/timeout.rb:98:in `call'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:858:in `start'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/net_http/handler.rb:119:in `session'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/net_http/handler.rb:45:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/plugins/content_length.rb:12:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_request_signer.rb:88:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_request_signer.rb:23:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_host_id.rb:14:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_request_signer.rb:65:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_redirects.rb:15:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:120:in `retry_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:103:in `retry_if_possible'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:91:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:120:in `retry_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:103:in `retry_if_possible'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:91:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:120:in `retry_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:103:in `retry_if_possible'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/retry_errors.rb:91:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_dualstack.rb:32:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_accelerate.rb:49:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_md5s.rb:31:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_expect_100_continue.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_bucket_name_restrictions.rb:12:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_bucket_dns.rb:31:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/rest/handler.rb:7:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-core-2.11.144/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-resources-2.11.144/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `block in put_object'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-resources-2.11.144/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-resources-2.11.144/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-resources-2.11.144/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-resources-2.11.144/lib/aws-sdk-resources/services/s3/object.rb:252:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-s3-1.10.3/lib/dpl/provider/s3.rb:114:in `block (2 levels) in upload_multithreaded'
```

This was working and honestly we're surprised this hasn't been reported by someone else, so it's probably something to do with our .travis.yml file.

**Comment by BanzaiMan** [comment]
Is the endpoint you provided correct? We used to ignore this option, but now we consult this value for S3-compatible storage backend. If the default value is acceptable, I suggest you drop it.

**Comment by alxdarksage** [comment]
We resolved this by using the AWS CLI directly and avoiding Travis' support for S3 deployments.
