### ISSUE TITLE
com.android.ddmlib.InstallException

### ISSUE THREAD

**Issue by GuilhE** [travis-ci/travis-ci#10303]
Hi, here's my travis.yml:
https://gist.github.com/GuilhE/d97e4536451e1e7a0624516ab49d3de6

Here's the build output:

```
Waiting for emulator to start
...
Waiting for emulator to start
Emulator is ready
adb shell input keyevent 82 &
./gradlew connectedCheck --stacktrace

...lots of error output...
:library:connectedDebugAndroidTest
```
at this point it hangs a lot of time here and then:
```
04:56:51 V/ddms: execute: running am get-config
04:56:58 V/ddms: execute 'am get-config' on 'emulator-5554' : EOF hit. Read: -1
04:56:58 V/ddms: execute: returning
04:56:58 D/library-debug-androidTest.apk: Uploading library-debug-androidTest.apk onto device 'emulator-5554'
04:56:58 D/Device: Uploading file onto device 'emulator-5554'
04:56:58 D/ddms: Reading file permision of /home/travis/build/GuilhE/SharedPrefsUtils/library/build/outputs/apk/androidTest/debug/library-debug-androidTest.apk as: rw-rw-r--
04:56:59 V/ddms: execute: running pm install -r -t "/data/local/tmp/library-debug-androidTest.apk"
05:01:11 V/ddms: execute: returning
Unable to install /home/travis/build/GuilhE/SharedPrefsUtils/library/build/outputs/apk/androidTest/debug/library-debug-androidTest.apk
com.android.ddmlib.InstallException
	at com.android.ddmlib.Device.installRemotePackage(Device.java:1038)
	at com.android.ddmlib.Device.installPackage(Device.java:902)
	at com.android.ddmlib.Device.installPackage(Device.java:880)
	at com.android.ddmlib.Device.installPackage(Device.java:869)
	at com.android.builder.testing.ConnectedDevice.installPackage(ConnectedDevice.java:126)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:159)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:59)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:557)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:383)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:594)
	at com.android.ddmlib.Device.installRemotePackage(Device.java:1028)
	... 11 more
com.android.builder.testing.ConnectedDevice > runTests[test(AVD) - 5.1.1] FAILED 
...
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':library:connectedDebugAndroidTest'.
...
BUILD FAILED in 4m 43s
45 actionable tasks: 1 executed, 44 up-to-date
The command "./gradlew connectedCheck --stacktrace" exited with 1.
```

Heres the link for more detail:
https://travis-ci.org/GuilhE/SharedPrefsUtils/builds/448919288

If you browse my build history you'll find some successful builds and instead of hanging in this line:
`:android-utils:connectedDebugAndroidTest`

it completes:

```

Starting 19 tests on test(AVD) - 5.1.1
:android-utils:createDebugAndroidTestCoverageReport
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.ant/0.7.4.201502262128/org.jacoco.ant-0.7.4.201502262128.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-parent/5.0.1/asm-parent-5.0.1.pom
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.ant/0.7.4.201502262128/org.jacoco.ant-0.7.4.201502262128.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.jar
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128.jar
:android-utils:connectedAndroidTest
:android-utils:connectedCheck
BUILD SUCCESSFUL in 1m 22s
48 actionable tasks: 3 executed, 45 up-to-date
The command "./gradlew connectedCheck" exited with 0.
```

What's happening? If I run the same command locally (IDE/cmd+emulator) it works.

**Comment by GuilhE** [comment]
After 50 builds it worked ¯\_(ツ)_/¯

**Comment by offdev** [comment]
This is probably a cause of the installation reaching the timeout. Try changing the ```ADB_INSTALL_TIMEOUT``` env to something bigger than the default (2 minutes) by default).

**Comment by GuilhE** [comment]
Hello @offdev ,
Where should I add that flag? I'm already using this:
```
adbOptions {
        timeOutInMs 10 * 60 * 1000  // Set the timeout to 10 minutes
        installOptions "-d","-t"
    }
```

**Comment by GuilhE** [comment]
Added:

```
env:
  global:
    - ADB_INSTALL_TIMEOUT=10
...
```

to my travis.yml and it worked :)

**Comment by BanzaiMan** [comment]
Looks like this can be closed.
