### ISSUE TITLE
fails to load a file from AWS S3

### ISSUE THREAD

**Issue by TC-hJiang** [travis-ci/travis-ci#10578]
The build always fails due to the failure of loading a file from AWS S3. 
The following is the printout.

`Installing deploy dependencies
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dpl/provider/s3 (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/provider.rb:93:in `rescue in block in new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/provider.rb:68:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/provider.rb:67:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
failed to deploy`

https://app.travis-ci.com/github/tigertext/roles/builds/267424870

**Comment by nikhilo** [comment]
I feel this could be due to a recent update to the `aws-eventstream` gem that was pushed on Nov 22
Here is the full log of the "Installing deploy dependencies" step
```
Installing deploy dependencies
Fetching aws-sigv4-1.7.0.gem
Fetching mime-types-data-3.2023.1003.gem
Fetching aws-eventstream-1.3.0.gem
Fetching aws-sdk-core-2.11.632.gem
Fetching jmespath-1.6.2.gem
Fetching aws-sdk-2.11.632.gem
Fetching mime-types-3.5.1.gem
Fetching aws-sdk-resources-2.11.632.gem
Fetching dpl-s3-1.10.16.gem
Successfully installed mime-types-data-3.2023.1003
Successfully installed mime-types-3.5.1
ERROR:  Error installing dpl-s3:
	The last version of aws-eventstream (~> 1, >= 1.0.2) to support your Ruby & RubyGems was 1.2.0. Try installing it with `gem install aws-eventstream -v 1.2.0` and then running the current command again
	aws-eventstream requires Ruby version >= 2.5. The current ruby version is 2.4.5.335.
/home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dpl/provider/s3 (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/provider.rb:93:in `rescue in block in new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/provider.rb:68:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/provider.rb:67:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.16/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
failed to deploy
```
