### ISSUE TITLE
gem connection timeout

### ISSUE THREAD

**Issue by tjwebb** [travis-ci/travis-ci#1942]
When trying to deploy to openshift:

```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ETIMEDOUT: Connection timed out - connect(2) (https://api.rubygems.org/gems/httpclient-2.3.4.1.gem)
/home/travis/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rhc (LoadError)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/provider.rb:46:in `requires'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/provider/openshift.rb:4:in `<class:Openshift>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/provider/openshift.rb:3:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/provider/openshift.rb:2:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/provider/openshift.rb:1:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/provider.rb:30:in `const_get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/provider.rb:30:in `block in new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/provider.rb:27:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.5.7/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p484/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by roidrage** [comment]
I'm closing this issue as there've been no further updates on this.
