### ISSUE TITLE
<%= breaks travis-yaml

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#2687]
```
[master][~/Code/github.com/travis-ci/travis-yaml] bundle exec ruby play/lint.rb travis-yml-test
/Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/node.rb:44:in `%': malformed format string - %= (ArgumentError)
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/node.rb:44:in `warning'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/sequence.rb:73:in `block (2 levels) in verify_children'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/sequence.rb:73:in `each'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/sequence.rb:73:in `block in verify_children'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/sequence.rb:71:in `delete_if'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/sequence.rb:71:in `verify_children'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/sequence.rb:66:in `verify'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser/psych.rb:100:in `accept'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/mapping.rb:99:in `visit_key_value'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/mapping.rb:92:in `visit_pair'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser/psych.rb:204:in `block in apply_mapping'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser/psych.rb:204:in `zip'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser/psych.rb:204:in `apply_mapping'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/nodes/mapping.rb:87:in `visit_mapping'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser/psych.rb:128:in `accept_mapping'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser/psych.rb:93:in `accept'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser/psych.rb:96:in `accept'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser/psych.rb:81:in `parse'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser/psych.rb:67:in `parse'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml/parser.rb:15:in `parse'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml.rb:14:in `parse'
	from /Users/henrikhodne/Code/github.com/travis-ci/travis-yaml/lib/travis/yaml.rb:20:in `parse!'
	from play/lint.rb:8:in `<main>'
[master][~/Code/github.com/travis-ci/travis-yaml] cat travis-yml-test
language: node_js
node_js:
  - <%= node_version %>
```

The same doesn't seem to happen with ruby versions.

This is the cause behind this Sentry error: https://app.getsentry.com/travis-ci/travis-api/group/29081874/

**Comment by BanzaiMan** [comment]
This no longer happens. https://travis-ci.org/BanzaiMan/travis_production_test/builds/126028235
