### ISSUE TITLE
TypeError: buf must be a byte string

### ISSUE THREAD

**Issue by mjallday** [travis-ci/travis-ci#3003]
Occurs when using pip 1.5.6 to build packages and attempting to install a package that returns a 301 redirect

https://magnum.travis-ci.com/balanced/knox/builds/7931499

```
Downloading/unpacking nosexcover==1.0.10 (from blumpkin>=0.4.2,<0.5)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/index.py", line 252, in find_requirement
    for page in self._get_pages(locations, req):
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/index.py", line 387, in _get_pages
    page = self._get_page(location, req)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/index.py", line 670, in get_page
    resp = session.get(url, headers={"Accept": "text/html"})
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 506, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 168, in resolve_redirects
    allow_redirects=False,
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/python/2.7.8/lib/python2.7/httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "/opt/python/2.7.8/lib/python2.7/httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "/opt/python/2.7.8/lib/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/opt/python/2.7.8/lib/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/opt/python/2.7.8/lib/python2.7/httplib.py", line 820, in send
    self.sock.sendall(data)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 323, in sendall
    return self.connection.sendall(data)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string
```

I'm attempting to use different versions of pip to see if I can isolate the issue however I have not run into this problem when running the same build on a fresh Ubuntu 12.04 VM that so far appears to mirror the environment for travis.

I think this is a similar issue to https://github.com/kennethreitz/requests/issues/1887 however pip embeds requests so it's not trivial to upgrade. The latest version of pip (devel branch) has [a newer version of requests embedded](https://github.com/pypa/pip/pull/2145) so I'll give that a shot and report back.

**Comment by keshavagrawal89** [comment]
pip upgrade solved the issue :+1:
