### ISSUE TITLE
Ddmlib is too aggressive with timeouts - kills `gradlew connectedCheck`

### ISSUE THREAD

**Issue by barbeau** [travis-ci/travis-ci#3110]
In our Android project, over the last month I have been seeing a lot of:
~~~
/home/travis/build.sh: line 41:  Killed ./gradlew connectedCheck -PdisablePreDex
The command "./gradlew connectedCheck -PdisablePreDex" exited with 137.
~~~

...failures, after a successful emulator start.  

For example, see:

https://travis-ci.org/OneBusAway/onebusaway-android/builds/46797885

Occasionally it will pass, but most of the time it fails with this error.

I'm guessing that this is a result of the issue with ddmlib being too aggressive with timeouts, which is discussed in this AOSP issue:
https://code.google.com/p/android/issues/detail?id=69735

Occasionally I'll get the stack trace discussed in the above AOSP issue too (for example, see [this build](https://travis-ci.org/OneBusAway/onebusaway-android/builds/46371886)).

If I understand the resolution to this AOSP issue, it sounds like a file bundled with Android Studio was patched, but that file still needs to be manually copied into the Github repo and copied into the Travis file path as part of our scripts?

Are there plans to patch this in the Travis VM itself?

**Comment by barbeau** [comment]
It seems I was able to fix this by switching to the [container-based infrastructure](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/).

I added the two lines to disable caching and set sudo to false to my .travis.yml file, so the top looks like this:

~~~
language: android
jdk: oraclejdk7
# Turn off caching to avoid any caching problems
cache: false
# Use the Travis Container-Based Infrastructure (see #203)
sudo: false
env:
  global:
  ...
~~~

You can see more details in the issue I filed on our project:
https://github.com/OneBusAway/onebusaway-android/issues/203

There is also a similar issue from another project that helped me resolve this problem:
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/236

I'm going to close this issue for now, and will re-open if the same `exited with 137` error seems to pop up on the container-based infrastructure builds.

**Comment by barbeau** [comment]
I'm seeing this issue again, this time in the container-based infrastructure builds.  

Around 10 or so of the last builds of [OBA Android](https://github.com/OneBusAway/onebusaway-android) have failed in the first execution, but then passed in the second execution. For example, the first and second execution of [this build](https://travis-ci.org/OneBusAway/onebusaway-android/builds/53255857) failed with the following error:

~~~
:onebusaway-android:connectedAndroidTest
09:48:14 E/Device: Error during shell execution: null
Unable to install /home/travis/build/OneBusAway/onebusaway-android/onebusaway-android/build/outputs/apk/onebusaway-android-debug.apk
com.android.ddmlib.InstallException
	at com.android.ddmlib.Device.installPackages(Device.java:927)
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:105)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:125)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:513)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:390)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:359)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:566)
	at com.android.ddmlib.Device.createMultiInstallSession(Device.java:987)
	at com.android.ddmlib.Device.installPackages(Device.java:884)
	... 9 more
com.android.builder.testing.ConnectedDevice > runTests[test(AVD) - 5.0.1] FAILED 
	com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException
		at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:108)
null
com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:108)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:125)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.ddmlib.InstallException
	at com.android.ddmlib.Device.installPackages(Device.java:927)
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:105)
	... 8 more
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:513)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:390)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:359)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:566)
	at com.android.ddmlib.Device.createMultiInstallSession(Device.java:987)
	at com.android.ddmlib.Device.installPackages(Device.java:884)
	... 9 more
:onebusaway-android:connectedAndroidTest FAILED
FAILURE: Build failed with an exception.
~~~

...but the third build passed.

The .travis.yml is [here](https://github.com/OneBusAway/onebusaway-android/blob/master/.travis.yml).

Could this ddmlib timeout value be patched in the Travis VM so we no longer have this problem?

See [this AOSP issue](https://code.google.com/p/android/issues/detail?id=69735) for details on a solution.

**Comment by ardock** [comment]
I answered you there, a patch is not required. Another example increasing the timeout:
https://github.com/ardock/android-testing/blob/ttt-colors/.travis.yml

**Comment by barbeau** [comment]
@ardock Thanks!  Didn't know that `ADB_INSTALL_TIMEOUT` variable existed.  I'm trying that now (https://github.com/OneBusAway/onebusaway-android/pull/248) to see if it resolves the issue.

**Comment by ardock** [comment]
@barbeau You are welcome, thanks to you for share your project, i didn't know that i can use the env globals in android-components section. Good luck, waiting onebus in Barcelona :)

**Comment by barbeau** [comment]
@ardock Well, so far so good!  The [first PR that included `ADB_INSTALL_TIMEOUT=8`](https://github.com/OneBusAway/onebusaway-android/pull/248) passed, which is definitely an improvement.  Thanks again!

I'm going to close this for now, and will re-open if the issue re-appears.

For those interested in the full solution, see the StackOverflow post [Android tests fail on Travis with ShellCommandUnresponsiveException](http://stackoverflow.com/questions/28949722/android-tests-fail-on-travis-with-shellcommandunresponsiveexception/28949723#28949723).

**Comment by SjoerdvGestel** [comment]
still have a lot of issues with timeouts, 90% of builds faile due to com.android.ddmlib.ShellCommandUnresponsiveException, even with ADB_INSTALL_TIMEOUT put to 10 or higher

**Comment by mickyzinho** [comment]
Same here

**Comment by ardock** [comment]
Follow @barbeau links like [this one](https://code.google.com/p/android/issues/detail?id=189764), Google needs to fix too low hardcoded timeouts. It's not a Travis-ci issue.

**Comment by barbeau** [comment]
Yes, I believe the current timeouts are due to another similar issue - https://code.google.com/p/android/issues/detail?id=189764.

The good news is that Google just recently updated the above issue and increased in priority, so hopefully we see a fix soon.

**Comment by SjoerdvGestel** [comment]
well up the amount of ram to min of 4GB would help

**Comment by ardock** [comment]
I have 8GB of RAM in my local machine and I'm affected by the same timeout when I use ARM emulators. The problem is that Google added a new functionality for API 22 or higher that parse a variable amount of data about the emulator and 5 seconds for that is too strict, they need fix it.

**Comment by barbeau** [comment]
I agree with @ardock, bumping specs won't help - I'm getting a `com.android.ddmlib.ShellCommandUnresponsiveException` every time I do "gradlew installDebug" on API 23 Google APIs emulator image on my work machine, which is a dual CPU Xeon with 16GB of RAM and an SSD.
