### ISSUE TITLE
SBT builds frequently fail with download errors

### ISSUE THREAD

**Issue by djspiewak** [travis-ci/travis-ci#3242]
I don't have any current-failing build to grab a log from, and Travis doesn't seem to preserve restarted build logs, but [here's a build](https://travis-ci.org/scalaz/scalaz-stream/builds/50977839) which *was* failing.  Basically, the issue I've been seeing quite frequently with SBT builds across multiple projects is that the build will often fail with errors downloading artifacts from Ivy.  The scala-compiler artifact is a common culprit, but I've also seen scalaz be a problem, dispatch, and more.  All of these artifacts are in Maven Central, so perhaps Sonatype is rate-limiting Travis's IP block?

The next time I see a failure, I'll update this issue with the log.

---

Failure achieved!  See the following log:

```
Switching to OpenJDK7 (java-1.7.0-openjdk-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-7-openjdk-amd64
$ export JVM_OPTS=@/etc/sbt/jvmopts
$ export SBT_OPTS=@/etc/sbt/sbtopts
$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~precise1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
$ javac -version
javac 1.7.0_75
Using Scala 2.10.4
63.80s$ sbt ++2.10.4 test
Detected sbt version 0.13.7
Using jvm options defined in file /etc/sbt/jvmopts
# Executing command line:
/usr/lib/jvm/java-7-openjdk-amd64/bin/java
-Xms2048M
-Xmx2048M
-Xss6M
-XX:MaxPermSize=512M
-jar
/home/travis/.sbt/launchers/0.13.7/sbt-launch.jar
++2.10.4
test
[info] Loading project definition from /home/travis/build/scalaz/scalaz-stream/project
[info] Updating {file:/home/travis/build/scalaz/scalaz-stream/project/}scalaz-stream-build...
[info] Resolving me.lessis#bintray-sbt;0.1.1 ...
[info] Resolving me.lessis#bintray-sbt;0.1.1 ...
[info] Resolving me.lessis#bintry_2.10;0.2.0 ...
[info] Resolving me.lessis#bintry_2.10;0.2.0 ...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Resolving net.databinder.dispatch#dispatch-json4s-native_2.10;0.11.0 ...
[info] Resolving net.databinder.dispatch#dispatch-json4s-native_2.10;0.11.0 ...
[info] Resolving net.databinder.dispatch#dispatch-core_2.10;0.11.0 ...
[info] Resolving net.databinder.dispatch#dispatch-core_2.10;0.11.0 ...
[info] Resolving com.ning#async-http-client;1.7.16 ...
[info] Resolving com.ning#async-http-client;1.7.16 ...
[info] Resolving org.sonatype.oss#oss-parent;5 ...
[info] Resolving org.sonatype.oss#oss-parent;5 ...
[info] Resolving io.netty#netty;3.6.3.Final ...
[info] Resolving io.netty#netty;3.6.3.Final ...
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[info] Resolving org.slf4j#slf4j-api;1.6.2 ...
[info] Resolving org.slf4j#slf4j-api;1.6.2 ...
[info] Resolving org.slf4j#slf4j-parent;1.6.2 ...
[info] Resolving org.slf4j#slf4j-parent;1.6.2 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.4 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.4 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.4 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.4 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.5.2 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.5.2 ...
[info] Resolving com.thoughtworks.paranamer#paranamer-parent;2.5.2 ...
[info] Resolving com.thoughtworks.paranamer#paranamer-parent;2.5.2 ...
[info] Resolving org.codehaus#codehaus-parent;1 ...
[info] Resolving org.codehaus#codehaus-parent;1 ...
[info] Resolving org.scala-lang#scalap;2.10.0 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
[info] Resolving org.json4s#json4s-native_2.10;3.2.4 ...
[info] Resolving org.json4s#json4s-native_2.10;3.2.4 ...
[info] Resolving com.typesafe.sbt#sbt-osgi;0.6.0 ...
[info] Resolving com.typesafe.sbt#sbt-osgi;0.6.0 ...
[info] Resolving biz.aQute.bnd#bndlib;2.1.0 ...
[info] Resolving biz.aQute.bnd#bndlib;2.1.0 ...
[info] Resolving biz.aQute.bnd#parent;2.1.0 ...
[info] Resolving biz.aQute.bnd#parent;2.1.0 ...
[info] Resolving org.osgi#org.osgi.core;4.2.0 ...
[info] Resolving org.osgi#org.osgi.core;4.2.0 ...
[info] Resolving com.github.tkawachi#sbt-doctest;0.3.3 ...
[info] Resolving com.github.tkawachi#sbt-doctest;0.3.3 ...
[info] Resolving commons-io#commons-io;2.4 ...
[info] Resolving commons-io#commons-io;2.4 ...
[info] Resolving org.apache.commons#commons-parent;25 ...
[info] Resolving org.apache.commons#commons-parent;25 ...
[info] Resolving org.apache#apache;9 ...
[info] Resolving org.apache#apache;9 ...
[info] Resolving org.scala-sbt#sbt;0.13.7 ...
[info] Resolving org.scala-sbt#main;0.13.7 ...
[info] Resolving org.scala-sbt#actions;0.13.7 ...
[info] Resolving org.scala-sbt#classpath;0.13.7 ...
[info] Resolving org.scala-sbt#launcher-interface;0.13.7 ...
[info] Resolving org.scala-sbt#interface;0.13.7 ...
[info] Resolving org.scala-sbt#io;0.13.7 ...
[info] Resolving org.scala-sbt#control;0.13.7 ...
[info] Resolving org.scala-sbt#completion;0.13.7 ...
[info] Resolving org.scala-sbt#collections;0.13.7 ...
[info] Resolving jline#jline;2.11 ...
[info] Resolving org.scala-sbt#api;0.13.7 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.7 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.7 ...
[info] Resolving org.scala-sbt#logging;0.13.7 ...
[info] Resolving org.scala-sbt#process;0.13.7 ...
[info] Resolving org.scala-sbt#relation;0.13.7 ...
[info] Resolving org.scala-sbt#compile;0.13.7 ...
[info] Resolving org.scala-sbt#persist;0.13.7 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#classfile;0.13.7 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.7 ...
[info] Resolving org.scala-sbt#ivy;0.13.7 ...
[info] Resolving org.scala-sbt#cross;0.13.7 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-fccfbd44c9f64523b61398a0155784dcbaeae28f ...
[info] Resolving com.jcraft#jsch;0.1.46 ...
[info] Resolving org.json4s#json4s-native_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.7 ...
[info] Resolving org.scala-sbt#task-system;0.13.7 ...
[info] Resolving org.scala-sbt#tasks;0.13.7 ...
[info] Resolving org.scala-sbt#tracking;0.13.7 ...
[info] Resolving org.scala-sbt#cache;0.13.7 ...
[info] Resolving org.scala-sbt#testing;0.13.7 ...
[info] Resolving org.scala-sbt#test-agent;0.13.7 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.7 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.7 ...
[info] Resolving org.scala-sbt#command;0.13.7 ...
[info] Resolving org.scala-sbt#logic;0.13.7 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.7 ...
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.7 ...
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.7 ...
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.7 ...
[info] Resolving org.scala-lang#jline;2.10.4 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/me.lessis/bintray-sbt/scala_2.10/sbt_0.13/0.1.1/jars/bintray-sbt.jar ...
[info] 	[SUCCESSFUL ] me.lessis#bintray-sbt;0.1.1!bintray-sbt.jar (540ms)
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-osgi/scala_2.10/sbt_0.13/0.6.0/jars/sbt-osgi.jar ...
[info] 	[SUCCESSFUL ] com.typesafe.sbt#sbt-osgi;0.6.0!sbt-osgi.jar (381ms)
[info] downloading https://repo1.maven.org/maven2/com/github/tkawachi/sbt-doctest_2.10_0.13/0.3.3/sbt-doctest-0.3.3.jar ...
[info] 	[SUCCESSFUL ] com.github.tkawachi#sbt-doctest;0.3.3!sbt-doctest.jar (101ms)
[info] downloading https://repo1.maven.org/maven2/me/lessis/bintry_2.10/0.2.0/bintry_2.10-0.2.0.jar ...
[info] 	[SUCCESSFUL ] me.lessis#bintry_2.10;0.2.0!bintry_2.10.jar (98ms)
[info] downloading https://repo1.maven.org/maven2/net/databinder/dispatch/dispatch-json4s-native_2.10/0.11.0/dispatch-json4s-native_2.10-0.11.0.jar ...
[info] 	[SUCCESSFUL ] net.databinder.dispatch#dispatch-json4s-native_2.10;0.11.0!dispatch-json4s-native_2.10.jar (58ms)
[info] downloading https://repo1.maven.org/maven2/net/databinder/dispatch/dispatch-core_2.10/0.11.0/dispatch-core_2.10-0.11.0.jar ...
[info] 	[SUCCESSFUL ] net.databinder.dispatch#dispatch-core_2.10;0.11.0!dispatch-core_2.10.jar (73ms)
[info] downloading https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.4/json4s-core_2.10-3.2.4.jar ...
[info] 	[SUCCESSFUL ] org.json4s#json4s-core_2.10;3.2.4!json4s-core_2.10.jar (94ms)
[info] downloading https://repo1.maven.org/maven2/org/json4s/json4s-native_2.10/3.2.4/json4s-native_2.10-3.2.4.jar ...
[info] 	[SUCCESSFUL ] org.json4s#json4s-native_2.10;3.2.4!json4s-native_2.10.jar (187ms)
[info] downloading https://repo1.maven.org/maven2/com/ning/async-http-client/1.7.16/async-http-client-1.7.16.jar ...
[info] 	[SUCCESSFUL ] com.ning#async-http-client;1.7.16!async-http-client.jar (204ms)
[info] downloading https://repo1.maven.org/maven2/io/netty/netty/3.6.3.Final/netty-3.6.3.Final.jar ...
[info] 	[SUCCESSFUL ] io.netty#netty;3.6.3.Final!netty.jar(bundle) (279ms)
[info] downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.2/slf4j-api-1.6.2.jar ...
[info] 	[SUCCESSFUL ] org.slf4j#slf4j-api;1.6.2!slf4j-api.jar (214ms)
[info] downloading https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.4/json4s-ast_2.10-3.2.4.jar ...
[info] 	[SUCCESSFUL ] org.json4s#json4s-ast_2.10;3.2.4!json4s-ast_2.10.jar (183ms)
[info] downloading https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.5.2/paranamer-2.5.2.jar ...
[info] 	[SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.5.2!paranamer.jar (184ms)
[info] downloading https://repo1.maven.org/maven2/biz/aQute/bnd/bndlib/2.1.0/bndlib-2.1.0.jar ...
[info] 	[SUCCESSFUL ] biz.aQute.bnd#bndlib;2.1.0!bndlib.jar (136ms)
[info] downloading https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar ...
[info] 	[SUCCESSFUL ] org.osgi#org.osgi.core;4.2.0!org.osgi.core.jar (72ms)
[info] downloading https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar ...
[info] 	[SUCCESSFUL ] commons-io#commons-io;2.4!commons-io.jar (75ms)
[info] Done updating.
Missing bintray credentials /home/travis/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to scalaz-stream (in build file:/home/travis/build/scalaz/scalaz-stream/)
[info] Setting version to 2.10.4
[info] Reapplying settings...
Missing bintray credentials /home/travis/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to scalaz-stream (in build file:/home/travis/build/scalaz/scalaz-stream/)
[warn] Credentials file /home/travis/.bintray/.credentials does not exist
[info] Updating {file:/home/travis/build/scalaz/scalaz-stream/}scalaz-stream...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Resolving org.scalaz#scalaz-core_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-core_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-concurrent_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-concurrent_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-effect_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-effect_2.10;7.0.6 ...
[info] Resolving org.scodec#scodec-bits_2.10;1.0.5 ...
[info] Resolving org.scodec#scodec-bits_2.10;1.0.5 ...
[info] Resolving org.scalaz#scalaz-scalacheck-binding_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-scalacheck-binding_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-typelevel_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-typelevel_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-xml_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-xml_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-iteratee_2.10;7.0.6 ...
[info] Resolving org.scalaz#scalaz-iteratee_2.10;7.0.6 ...
[info] Resolving org.scalacheck#scalacheck_2.10;1.12.1 ...
[info] Resolving org.scalacheck#scalacheck_2.10;1.12.1 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
[info] Resolving org.scala-lang#jline;2.10.4 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.10/7.0.6/scalaz-core_2.10-7.0.6.jar ...
[warn] 	[FAILED     ] org.scalaz#scalaz-core_2.10;7.0.6!scalaz-core_2.10.jar(bundle): Connection reset (4399ms)
[warn] 	[FAILED     ] org.scalaz#scalaz-core_2.10;7.0.6!scalaz-core_2.10.jar(bundle): Connection reset (4399ms)
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.10/7.0.6/scalaz-core_2.10-7.0.6.jar
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-concurrent_2.10/7.0.6/scalaz-concurrent_2.10-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.scalaz#scalaz-concurrent_2.10;7.0.6!scalaz-concurrent_2.10.jar(bundle) (1200ms)
[info] downloading https://repo1.maven.org/maven2/org/scodec/scodec-bits_2.10/1.0.5/scodec-bits_2.10-1.0.5.jar ...
[info] 	[SUCCESSFUL ] org.scodec#scodec-bits_2.10;1.0.5!scodec-bits_2.10.jar(bundle) (990ms)
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-effect_2.10/7.0.6/scalaz-effect_2.10-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.scalaz#scalaz-effect_2.10;7.0.6!scalaz-effect_2.10.jar(bundle) (191ms)
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-scalacheck-binding_2.10/7.0.6/scalaz-scalacheck-binding_2.10-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.scalaz#scalaz-scalacheck-binding_2.10;7.0.6!scalaz-scalacheck-binding_2.10.jar(bundle) (86ms)
[info] downloading https://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.10/1.12.1/scalacheck_2.10-1.12.1.jar ...
[info] 	[SUCCESSFUL ] org.scalacheck#scalacheck_2.10;1.12.1!scalacheck_2.10.jar (120ms)
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-typelevel_2.10/7.0.6/scalaz-typelevel_2.10-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.scalaz#scalaz-typelevel_2.10;7.0.6!scalaz-typelevel_2.10.jar(bundle) (99ms)
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-xml_2.10/7.0.6/scalaz-xml_2.10-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.scalaz#scalaz-xml_2.10;7.0.6!scalaz-xml_2.10.jar(bundle) (111ms)
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-iteratee_2.10/7.0.6/scalaz-iteratee_2.10-7.0.6.jar ...
[info] 	[SUCCESSFUL ] org.scalaz#scalaz-iteratee_2.10;7.0.6!scalaz-iteratee_2.10.jar(bundle) (101ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalaz#scalaz-core_2.10;7.0.6!scalaz-core_2.10.jar(bundle)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: org.scalaz#scalaz-core_2.10;7.0.6!scalaz-core_2.10.jar(bundle)
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
	at sbt.IvySbt.withIvy(Ivy.scala:123)
	at sbt.IvySbt.withIvy(Ivy.scala:120)
	at sbt.IvySbt$Module.withModule(Ivy.scala:151)
	at sbt.IvyActions$.updateEither(IvyActions.scala:157)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: download failed: org.scalaz#scalaz-core_2.10;7.0.6!scalaz-core_2.10.jar(bundle)
[error] Total time: 9 s, completed Feb 17, 2015 5:10:59 PM
```

Precise jobs where I saw this just now are [scalaz/scalaz-stream #1054.2](https://travis-ci.org/scalaz/scalaz-stream/jobs/51104790) and [#1054.3](https://travis-ci.org/scalaz/scalaz-stream/jobs/51104791).  For some reason, the "restart" button is absent, so they're hanging out in a failed state for a while.

**Comment by BanzaiMan** [comment]
@djspiewak Hello. Is this still happening? We deployed some network configuration changes recently, and are trying to figure out if it was effective.

**Comment by djspiewak** [comment]
@BanzaiMan I haven't seen the issue recently.  Seems like the changes were effective!  I'll keep an eye on things and can reopen if you would like.

**Comment by BanzaiMan** [comment]
@djspiewak Sweet! I'm closing this one optimistically. If you see the problem recur, do let us know.

**Comment by djspiewak** [comment]
It's back.  :-(  Build log is [here](https://gist.github.com/djspiewak/9667388ecab6a2890ce2) (not done inline due to length.  Actual job is [here](https://travis-ci.org/scalaz/scalaz-stream/jobs/54927338).

**Comment by yanyanJing** [comment]
@BanzaiMan   Excuse me.
Here, I get a mistake, Can anyone help me? 
 I had downloaded com.thoughtworks.paranamer.jar, but what to do next?
Thank you!


jyy@jyy-linux:~/Downloads/prongfun-assignment/example$ sbt
[info] Loading project definition from /home/jyy/Downloads/prongfun-assignment/example/project/project
[info] Loading project definition from /home/jyy/Downloads/prongfun-assignment/example/project
[info] Set current project to progfun-example (in build file:/home/jyy/Downloads/prongfun-assignment/example/)
> console
[info] Updating {file:/home/jyy/Downloads/prongfun-assignment/example/}assignment...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.5.6 ...
[warn] problem while downloading module descriptor: http://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.5.6/paranamer-2.5.6.pom: invalid sha1: expected=534448ad3c4af760c8995370c1405b9dbf88609e computed=0d33f7748ec6c8928db74f9652a2cb7567fe4044 (1848ms)
[warn] module not found: com.thoughtworks.paranamer#paranamer;2.5.6
[warn] ==== local: tried
[warn]   /home/jyy/.ivy2/local/com.thoughtworks.paranamer/paranamer/2.5.6/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.5.6/paranamer-2.5.6.pom
[info] Resolving org.hamcrest#hamcrest-core;1.1 ...
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] ::          UNRESOLVED DEPENDENCIES         ::
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: com.thoughtworks.paranamer#paranamer;2.5.6: not found
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last assignment/*:update for the full output.
[error] (assignment/*:update) sbt.ResolveException: unresolved dependency: com.thoughtworks.paranamer#paranamer;2.5.6: not found
[error] Total time: 5 s, completed Jun 16, 2015 4:13:14 PM
>

**Comment by patelprakashp** [comment]
I am also facing the same issue . anyone help me to fix the issue 
<update:` sbt.ResolveException: download failed: com.thoughtworks.paranamer#paranamer;2.6!paranamer.jar

>

**Comment by architsingh99** [comment]
It's happening again out of sudden. I am facing the same issue.
