### ISSUE TITLE
Travis can't find com.google.android.gms:play-services-ads:7.0.0

### ISSUE THREAD

**Issue by jaredsburrows** [travis-ci/travis-ci#3642]
For some reason, Travis is having a hard time resolving: `com.google.android.gms:play-services-ads:7.0.0`. It had no problem resolving the previous version: `com.google.android.gms:play-services-ads:6.5.87`.
   
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    A problem occurred configuring project ':App-ExampleForAdmob'.
    > A problem occurred configuring project ':Lib-BurrowsApps'.
       > Could not resolve all dependencies for configuration ':Lib-BurrowsApps:_debugCompile'.
          > Could not find com.google.android.gms:play-services-ads:7.0.0.
            Searched in the following locations:
                https://jcenter.bintray.com/com/google/android/gms/play-services-ads/7.0.0/play-services-ads-7.0.0.pom
                https://jcenter.bintray.com/com/google/android/gms/play-services-ads/7.0.0/play-services-ads-7.0.0.jar
                file:/usr/local/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads/7.0.0/play-services-ads-7.0.0.pom
                file:/usr/local/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-ads/7.0.0/play-services-ads-7.0.0.jar
                file:/usr/local/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads/7.0.0/play-services-ads-7.0.0.pom
                file:/usr/local/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-ads/7.0.0/play-services-ads-7.0.0.jar
            Required by:
                BurrowsAppsExamples:Lib-BurrowsApps:unspecified
    
    * Try:
    Run with --info or --debug option to get more log output.
    
    * Exception is:
    org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':App-ExampleForAdmob'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:492)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
    Caused by: org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':Lib-BurrowsApps'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:492)
        at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:550)
        at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:542)
        at com.android.build.gradle.internal.DependencyManager$_ensureConfigured_closure10.doCall(DependencyManager.groovy:578)
        at com.android.build.gradle.internal.DependencyManager$_ensureConfigured_closure10.call(DependencyManager.groovy)
        at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.groovy:577)
        at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.groovy:213)
        at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.groovy:128)
        at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.groovy:250)
        at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:500)
        at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:585)
        at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:364)
        at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:231)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:431)
        at com.android.build.gradle.BasePlugin$_createTasks_closure9.doCall(BasePlugin.groovy:373)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
        ... 31 more

Please see the log here: https://s3.amazonaws.com/archive.travis-ci.org/jobs/57897469/log.txt.

**Comment by jaredsburrows** [comment]
I guess Travis has changed a little?

I now have to add this to my `.travis.yml`:

    android:
      components:
        - build-tools-22.0.1
        - extra-android-support
        - extra-android-m2repository
        - android-22
      licenses:
        - '.+'

**Comment by jaredsburrows** [comment]
Ah, I spoke too soon:

https://api.travis-ci.org/jobs/57898926/log.txt?deansi=true

I can download AppCompat with the new `.travis.yml` setup but not the latest Google Play Services.

**Comment by jaredsburrows** [comment]
After reading the recent updates from http://docs.travis-ci.com/user/languages/android/, I was able to put this together:

    android:
      components:
        - extra-android-support
        - extra-google-google_play_services
        - extra-android-m2repository
        - extra-google-m2repository  
        - build-tools-22.0.1
        - android-22
      licenses:
        - '.+'

Now everything is able to resolve and once again passes the build.

**Comment by IgorGanapolsky** [comment]
@jaredsburrows Why is `licences` block useful?

**Comment by jaredsburrows** [comment]
@IgorGanapolsky  It automatically accepts all the license agreements.

**Comment by IgorGanapolsky** [comment]
@jaredsburrows Wouldn't it automatically accept them without this block anyway??

**Comment by jaredsburrows** [comment]
It did not for me. Read the docs here: http://docs.travis-ci.com/user/languages/android/#Dealing-with-Licenses.

**Comment by IgorGanapolsky** [comment]
Ok, it says 
> By default, Travis CI will accept all the requested licenses

I see your point, thanks for sharing.
