### ISSUE TITLE
Gems fail to install for the default Ruby due to permission issues

### ISSUE THREAD

**Issue by bill-auger** [travis-ci/travis-ci#3662]
this is trying to build using the identical configuration that was passing about 12 hours ago - has been re-run several times and the failure is consistent - this is not affecting only my project - it has also been reported by others on the IRC channel with the only difference being the particular gem being installed
```
Fetching: ffi-1.9.8.gem (100%)
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /home/travis/.rvm/gems/ruby-1.9.3-p551/extensions/x86_64-linux/1.9.1/ffi-1.9.8
```

**Comment by BanzaiMan** [comment]
Sorry about this. I'll be rolling back the image, and make some changes.

**Comment by bill-auger** [comment]
passing again ty

**Comment by BanzaiMan** [comment]
We need to fix this issue before the update goes out. :-)

**Comment by bill-auger** [comment]
am getting a different error now - the gems install successfully but after the main buld when calling the executable that was installed as a gem this error appears:
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/lib/fpm/package/deb.rb:394:in `initialize': No such file or directory - /home/travis/build/linjam/linjam/Builds/Linux/Build/debian/changelog (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/lib/fpm/package/deb.rb:394:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/lib/fpm/package/deb.rb:394:in `block (2 levels) in output'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/lib/fpm/package/deb.rb:391:in `tap'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/lib/fpm/package/deb.rb:391:in `block in output'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/lib/fpm/package/deb.rb:390:in `tap'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/lib/fpm/package/deb.rb:390:in `output'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/lib/fpm/command.rb:450:in `execute'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/clamp-0.6.4/lib/clamp/command.rb:67:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/clamp-0.6.4/lib/clamp/command.rb:132:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/fpm-1.3.3/bin/fpm:8:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/fpm:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/fpm:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
```

again this gem is not itself broken - this was working correctly yesterday

**Comment by bill-auger** [comment]
nm my bad on that last one
