### ISSUE TITLE
Android build on Docker can fail in `:preDexBetaDebug` stage

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3695]
The `gradle` process can die with exit status 137 (out of memory) with stack trace like this:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task '…:preDexBetaDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-oracle/bin/java'' finished with non-zero exit value 137
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:116)
	at com.android.ide.common.internal.WaitableExecutor$waitForTasksWithQuickFail$0.call(Unknown Source)
	at com.android.build.gradle.tasks.PreDex.taskAction(PreDex.groovy:106)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more
Caused by: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-oracle/bin/java'' finished with non-zero exit value 137
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:42)
	at com.android.builder.core.AndroidBuilder.preDexLibrary(AndroidBuilder.java:1298)
	at com.android.builder.internal.compiler.PreDexCache.preDexLibrary(PreDexCache.java:122)
	at com.android.builder.core.AndroidBuilder.preDexLibrary(AndroidBuilder.java:1250)
	at com.android.builder.core.AndroidBuilder$preDexLibrary$27.call(Unknown Source)
	at com.android.build.gradle.tasks.PreDex$PreDexTask.call(PreDex.groovy:150)
	at com.android.build.gradle.tasks.PreDex$PreDexTask.call(PreDex.groovy)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-oracle/bin/java'' finished with non-zero exit value 137
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:40)
	... 6 more
```

The exact trace, or the build stage may differ, but in general, the symptom is such that `gradle` process runs out of memory and dies.

**Comment by BanzaiMan** [comment]
One user reports that skipping pre-dexing works reduces memory usage in `build.gradle` with something similar in spirit to:

```
dexOptions {
    // Skip pre-dexing when running on Travis CI or when disabled via -Dpre-dex=false.
    preDexLibraries = preDexEnabled && !isTravis
}
```

Also setting memory limits may help. https://gradle.org/docs/current/userguide/build_environment.html

**Comment by BanzaiMan** [comment]
Another possible solution is to tune glibc memory usage by setting `MALLOC_ARENA_MAX=2`.

See https://github.com/travis-ci/travis-cookbooks/pull/458 and https://devcenter.heroku.com/articles/testing-cedar-14-memory-use.

**Comment by MariadeAnton** [comment]
Also reported through the slack lounge, ERROR message: "com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-oracle/bin/java'' finished with non-zero exit value 137"

**Comment by IgorGanapolsky** [comment]
This is likely due to your app exceeding the 65k method count, thus causing a dex error.  There is no solution, other than enabling multidexing in your app.

**Comment by sirvon** [comment]
same problem here...
I have dex enabled within my build, my app builds properly on my local system.
I added this to my .travis.yml:
```yml
sudo: required
```
which forces travis to build in a non-container based worker.
It builds successfully now, albeit a tad slower.

**Comment by anubiann00b** [comment]
I have the same problem here. I'm under the 65k method limit.

**Comment by snejati86** [comment]
Has anyone solved this problem ?

**Comment by tv8eye** [comment]
Yes, i solved exactly the same problem today (Added `MALLOC_ARENA_MAX=2` and `sudo: required`).

```yml
language: android

jdk:
  - oraclejdk8

env:
  global:
    # Add this
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

cache: false
# Add this
sudo: required

script:
  - gradle assembleDebug
```

Build works fine. But now I have message from travis:
"*This job ran on our legacy infrastructure.*" 
Is it critical?

**Comment by anothem** [comment]
Adding sudo doesn't fix the problem, it just hacks around it. When you do that, instead of running on Docker, you run on the old infra (because Docker doesn't yet support sudo). That's also what that warning message is telling you.

**Comment by tv8eye** [comment]
@anothem Yes, I understand but i have no other solution. Any suggestions?

**Comment by anothem** [comment]
I wasn't criticising, just making sure it's clear what that does :) 
I'm afraid I have nothing that hasn't been suggested here already. I managed to make this work by turning preDexing off.

**Comment by snejati86** [comment]
I have been unable to disable pre dexing on Travis,
here are the things I've tried,

1. Defining isTravis environment and setting dexOptions { preDexLibrary = ! isTravis }  ( taking a hint from U2020 project. )
2. Passing -PdisablePreDex to the gradle execution line on yaml.
3. Setting -Dpre-dex=disable and looking for the flag in dexOptions { preDexLibrary = isPreDex }  


These are the solutions I've seen online to disable predexing, Is there something I am missing ? None of these solutions passed the pre dexing on Travis and it all exited with 137 until I added the sudo, obviously I rather have the test run on the new infrastructure which provides faster bootup.

Any ideas?

**Comment by anothem** [comment]
The way I've done it is by putting this in my root gradle file (https://gist.github.com/anothem/9f1a8fc3fb6c5cafd5a5) and then using the -PdisablePreDex option.

**Comment by IgorGanapolsky** [comment]
@anothem That's pretty much the way Google recommends doing it in their developer docs.  But does it guarantee predexing on Travis-ci?

**Comment by snejati86** [comment]
@anothem 
It makes sense cause I'm running the gradle build from the top wrapper so probably the flag didn't apply to the sub modules ?

I'll give it a try.

**Comment by anothem** [comment]
@IgorGanapolsky that must be where I grabbed it from, I can't recall :) The Gradle build should run the exact same way on Travis as it does locally, there's nothing special going on there. If it disables preDexing successfully locally, it should do it on Travis as well.

**Comment by SandroMachado** [comment]
Any updates relating this issue?

**Comment by snejati86** [comment]
@SandroMachado 
I gave up on emulator testing,
I still have a build on EC2 that runs a snapshotted emulator build ~ 15 mins long for <100 tests for now, but I've decided to move to a device rack, Emulator launch has been flaky and test results are not consistent.
