### ISSUE TITLE
Problem with starting a new process

### ISSUE THREAD

**Issue by moleksyuk** [travis-ci/travis-ci#3747]
Hi,

I have one test that executes 'ping' command without any params. (I need this to simulate command that exits with non zero value).

This test passed 3 months ago but today it fails in Travis.
BTW it passes in Windows PC and OS X now.
https://travis-ci.org/moleksyuk/vcs-semantic-version/builds
```
Caused by:
20:54:15.697 [DEBUG] [TestEventLogger]         org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'ping''
20:54:15.698 [DEBUG] [TestEventLogger]             at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:196)
20:54:15.698 [DEBUG] [TestEventLogger]             at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:325)
20:54:15.698 [DEBUG] [TestEventLogger]             at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
20:54:15.698 [DEBUG] [TestEventLogger]             ... 4 more
20:54:15.698 [DEBUG] [TestEventLogger] 
20:54:15.699 [DEBUG] [TestEventLogger]             Caused by:
20:54:15.699 [DEBUG] [TestEventLogger]             net.rubygrapefruit.platform.NativeException: Could not start 'ping'
20:54:15.699 [DEBUG] [TestEventLogger]                 at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
20:54:15.699 [DEBUG] [TestEventLogger]                 at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
20:54:15.699 [DEBUG] [TestEventLogger]                 at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:65)
20:54:15.700 [DEBUG] [TestEventLogger]                 ... 4 more
20:54:15.700 [DEBUG] [TestEventLogger] 
20:54:15.700 [DEBUG] [TestEventLogger]                 Caused by:
20:54:15.700 [DEBUG] [TestEventLogger]                 java.io.IOException: Cannot run program "ping" (in directory "/tmp/gradle5421121654428696755projectDir"): error=2, No such file or directory
20:54:15.700 [DEBUG] [TestEventLogger]                     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
20:54:15.701 [DEBUG] [TestEventLogger]                     at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
20:54:15.702 [DEBUG] [TestEventLogger]                     ... 6 more
20:54:15.702 [DEBUG] [TestEventLogger] 
20:54:15.702 [DEBUG] [TestEventLogger]                     Caused by:
20:54:15.702 [DEBUG] [TestEventLogger]                     java.io.IOException: error=2, No such file or directory
20:54:15.702 [DEBUG] [TestEventLogger]                         at java.lang.UNIXProcess.forkAndExec(Native Method)
20:54:15.702 [DEBUG] [TestEventLogger]                         at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
20:54:15.703 [DEBUG] [TestEventLogger]                         at java.lang.ProcessImpl.start(ProcessImpl.java:130)
20:54:15.703 [DEBUG] [TestEventLogger]                         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
20:54:15.703 [DEBUG] [TestEventLogger]                         ... 7 more
```

**Comment by BanzaiMan** [comment]
Sorry, but `ping` is not supported on containers. See https://github.com/travis-ci/travis-ci/issues/3080 for details.

If you need a command with non-zero exit status, you can use `false`. You can also opt-in to the standard infrastructure with `sudo: required`. Or simulate `ping` with creating a TCP socket with Ruby (or Python, or whatever you desire).

**Comment by moleksyuk** [comment]
@BanzaiMan thanks a lot man. Not it works fine :+1:
