### ISSUE TITLE
Tests fail when using the new containter-based infrastructure

### ISSUE THREAD

**Issue by sebigavril** [travis-ci/travis-ci#3775]
I'm using Travis for my Scala (2.11.6) project. Lately I've tried experimenting with Travis' cache capabilities. It seems to work, however my tests are always failing at some point with
```
Exception in thread "Thread-7" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at sbt.React.react(ForkTests.scala:114)
	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
	at java.lang.Thread.run(Thread.java:745)
```
I am forking my tests in sbt so that they run in different JVM. If i remove the fork option, they work. It seems that the container-based infrastructure is causing them to fail when they are forked.

**Comment by BanzaiMan** [comment]
Can you tell from the thread dump _why_ JVM fork fails?

**Comment by sebigavril** [comment]
@BanzaiMan There is some detail, but don't understand the cause:
> `
Running java with options -classpath /home/travis/build/sebigavril/backend/platform/target/scala-2.11/platform_2.11-8.21.0-SNAPSHOT-tests.jar:/home/travis/build/sebigavril/backend/platform/target/scala-2.11/platform_2.11-8.21.0-SNAPSHOT.jar:/home/travis/.sbt/0.13/staging/d859917c22d2b71383bc/slick-joda-mapper/target/scala-2.11/classes:/home/travis/build/sebigavril/backend/events/target/scala-2.11/classes:/home/travis/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar:/home/travis/.ivy2/cache/com.typesafe.play/play-cache_2.11/jars/play-cache_2.11-2.3.7.jar:/home/travis/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.3.7.jar:/home/travis/.ivy2/cache/com.typesafe.play/build-link/jars/build-link-2.3.7.jar:/home/travis/.ivy2/cache/com.typesafe.play/play-exceptions/jars/play-exceptions-2.3.7.jar:/home/travis/.ivy2/cache/org.javassist/javassist/bundles/javassist-3.18.2-GA.jar:/home/travis/.ivy2/cache/com.typesafe.play/play-iteratees_2.11/jars/play-iteratees_2.11-2.3.7.jar:/home/travis/.ivy2/cache/org.scala-stm/scala-stm_2.11/jars/scala-stm_2.11-0.7.jar:/home/travis/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/home/travis/.ivy2/cache/com.typesafe.play/play-json_2.11/jars/play-json_2.11-2.3.7.jar:/home/travis/.ivy2/cache/com.typesafe.play/play-functional_2.11/jars/play-functional_2.11-2.3.7.jar:/home/travis/.ivy2/cache/com.typesafe.play/play-datacommons_2.11/jars/play-datacommons_2.11-2.3.7.jar:/home/travis/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.7.jar:/home/travis/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.7.jar:/home/travis/.ivy2/cache/com.typesafe.play/twirl-api_2.11/jars/twirl-api_2.11-1.0.2.jar:/home/travis/.ivy2/cache/org.apache.commons/commons-lang3/jars/commons-lang3-3.1.jar:/home/travis/.ivy2/cache/io.netty/netty/bundles/netty-3.9.3.Final.jar:/home/travis/.ivy2/cache/com.typesafe.netty/netty-http-pipelining/jars/netty-http-pipelining-1.1.2.jar:/home/travis/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.6.jar:/home/travis/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.6.jar:/home/travis/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.1.jar:/home/travis/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.1.jar:/home/travis/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.4-SNAPSHOT.jar:/home/travis/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.4-SNAPSHOT.jar:/home/travis/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.9.jar:/home/travis/.ivy2/cache/xerces/xercesImpl/jars/xercesImpl-2.11.0.jar:/home/travis/.ivy2/cache/xml-apis/xml-apis/jars/xml-apis-1.4.01.jar:/home/travis/.ivy2/cache/javax.transaction/jta/jars/jta-1.1.jar:/home/travis/.ivy2/cache/net.sf.ehcache/ehcache-core/jars/ehcache-core-2.6.8.jar:/home/travis/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.7.jar:/home/travis/.ivy2/cache/org.reflections/reflections/jars/reflections-0.9.9.jar:/home/travis/.ivy2/cache/com.google.code.findbugs/annotations/jars/annotations-2.0.1.jar:/home/travis/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.4.jar:/home/travis/.ivy2/cache/com.beachape.filemanagement/schwatcher_2.11/jars/schwatcher_2.11-0.1.7.jar:/home/travis/.ivy2/cache/io.reactivex/rxscala_2.11/jars/rxscala_2.11-0.23.1.jar:/home/travis/.ivy2/cache/io.reactivex/rxjava/jars/rxjava-1.0.4.jar:/home/travis/.ivy2/cache/com.github.danielwegener/logback-kafka-appender/jars/logback-kafka-appender-0.0.2.jar:/home/travis/.ivy2/cache/org.apache.kafka/kafka-clients/jars/kafka-clients-0.8.2.0.jar:/home/travis/.ivy2/cache/net.jpountz.lz4/lz4/jars/lz4-1.2.0.jar:/home/travis/.ivy2/cache/org.xerial.snappy/snappy-java/bundles/snappy-java-1.1.1.6.jar:/home/travis/.ivy2/cache/com.nimbusds/nimbus-jose-jwt/jars/nimbus-jose-jwt-2.10.1.jar:/home/travis/.ivy2/cache/org.bouncycastle/bcprov-jdk16/jars/bcprov-jdk16-1.46.jar:/home/travis/.ivy2/cache/net.jcip/jcip-annotations/jars/jcip-annotations-1.0.jar:/home/travis/.ivy2/cache/net.minidev/json-smart/jars/json-smart-1.1.1.jar:/home/travis/.ivy2/cache/com.typesafe.play/play-ws_2.11/jars/play-ws_2.11-2.3.7.jar:/home/travis/.ivy2/cache/com.ning/async-http-client/jars/async-http-client-1.8.14.jar:/home/travis/.ivy2/cache/oauth.signpost/signpost-core/jars/signpost-core-1.2.1.2.jar:/home/travis/.ivy2/cache/oauth.signpost/signpost-commonshttp4/jars/signpost-commonshttp4-1.2.1.2.jar:/home/travis/.ivy2/cache/org.apache.httpcomponents/httpcore/jars/httpcore-4.0.1.jar:/home/travis/.ivy2/cache/org.apache.httpcomponents/httpclient/jars/httpclient-4.0.1.jar:/home/travis/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/home/travis/.ivy2/cache/com.typesafe.scala-logging/scala-logging_2.11/jars/scala-logging_2.11-3.0.0.jar:/home/travis/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-3.0.0-RC3.jar:/home/travis/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.RC4.jar:/home/travis/.ivy2/cache/com.wordnik/swagger-play2_2.11/jars/swagger-play2_2.11-1.3.12.jar:/home/travis/.ivy2/cache/com.wordnik/swagger-jaxrs_2.11/jars/swagger-jaxrs_2.11-1.3.12.jar:/home/travis/.ivy2/cache/com.wordnik/swagger-core_2.11/bundles/swagger-core_2.11-1.3.12.jar:/home/travis/.ivy2/cache/com.fasterxml.jackson.module/jackson-module-scala_2.11/bundles/jackson-module-scala_2.11-2.4.1.jar:/home/travis/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.4.1.jar:/home/travis/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.4.1.jar:/home/travis/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.4.1.1.jar:/home/travis/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar:/home/travis/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-2.0.1.jar:/home/travis/.ivy2/cache/com.fasterxml.jackson.module/jackson-module-jsonSchema/bundles/jackson-module-jsonSchema-2.4.1.jar:/home/travis/.ivy2/cache/com.fasterxml.jackson.jaxrs/jackson-jaxrs-json-provider/bundles/jackson-jaxrs-json-provider-2.4.1.jar:/home/travis/.ivy2/cache/com.fasterxml.jackson.jaxrs/jackson-jaxrs-base/bundles/jackson-jaxrs-base-2.4.1.jar:/home/travis/.ivy2/cache/com.fasterxml.jackson.module/jackson-module-jaxb-annotations/bundles/jackson-module-jaxb-annotations-2.4.1.jar:/home/travis/.ivy2/cache/com.wordnik/swagger-annotations/bundles/swagger-annotations-1.3.12.jar:/home/travis/.ivy2/cache/org.json4s/json4s-ext_2.11/jars/json4s-ext_2.11-3.2.11.jar:/home/travis/.ivy2/cache/org.json4s/json4s-native_2.11/jars/json4s-native_2.11-3.2.11.jar:/home/travis/.ivy2/cache/org.json4s/json4s-core_2.11/jars/json4s-core_2.11-3.2.11.jar:/home/travis/.ivy2/cache/org.json4s/json4s-ast_2.11/jars/json4s-ast_2.11-3.2.11.jar:/home/travis/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.11.0.jar:/home/travis/.ivy2/cache/org.json4s/json4s-jackson_2.11/jars/json4s-jackson_2.11-3.2.11.jar:/home/travis/.ivy2/cache/javax.ws.rs/jsr311-api/jars/jsr311-api-1.1.1.jar:/home/travis/.ivy2/cache/com.zaxxer/HikariCP-java6/bundles/HikariCP-java6-2.1.0.jar:/home/travis/.ivy2/cache/dnsjava/dnsjava/jars/dnsjava-2.1.1.jar:/home/travis/.ivy2/cache/mysql/mysql-connector-java/jars/mysql-connector-java-5.1.30.jar:/home/travis/.ivy2/cache/net.codingwell/scala-guice_2.11/jars/scala-guice_2.11-4.0.0-beta5.jar:/home/travis/.ivy2/cache/com.google.inject/guice/jars/guice-4.0-beta5.jar:/home/travis/.ivy2/cache/javax.inject/javax.inject/jars/javax.inject-1.jar:/home/travis/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:/home/travis/.ivy2/cache/com.google.inject.extensions/guice-multibindings/jars/guice-multibindings-4.0-beta5.jar:/home/travis/.ivy2/cache/com.google.guava/guava/bundles/guava-17.0.jar:/home/travis/.ivy2/cache/net.sf.jtidy/jtidy/jars/jtidy-r938.jar:/home/travis/.ivy2/cache/net.sf.opencsv/opencsv/jars/opencsv-2.1.jar:/home/travis/.ivy2/cache/org.apache.commons/commons-email/jars/commons-email-1.3.3.jar:/home/travis/.ivy2/cache/javax.mail/mail/jars/mail-1.4.5.jar:/home/travis/.ivy2/cache/javax.activation/activation/jars/activation-1.1.1.jar:/home/travis/.ivy2/cache/org.codehaus.janino/janino/jars/janino-2.7.8.jar:/home/travis/.ivy2/cache/org.codehaus.janino/commons-compiler/jars/commons-compiler-2.7.8.jar:/home/travis/.ivy2/cache/org.jsoup/jsoup/jars/jsoup-1.7.3.jar:/home/travis/.ivy2/cache/org.scala-lang.modules/scala-async_2.11/bundles/scala-async_2.11-0.9.2.jar:/home/travis/.ivy2/cache/org.subethamail/subethasmtp-wiser/jars/subethasmtp-wiser-1.2.jar:/home/travis/.ivy2/cache/org.subethamail/subethasmtp-smtp/jars/subethasmtp-smtp-1.2.jar:/home/travis/.ivy2/cache/com.h2database/h2/jars/h2-1.4.178.jar:/home/travis/.ivy2/cache/org.mockito/mockito-all/jars/mockito-all-1.9.5.jar:/home/travis/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.12.0.jar:/home/travis/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar:/home/travis/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.2.jar:/home/travis/.ivy2/cache/org.specs2/specs2_2.11/jars/specs2_2.11-2.4.jar:/home/travis/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.2.jar:/home/travis/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.2.jar:/home/travis/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar:/home/travis/.ivy2/cache/org.pegdown/pegdown/jars/pegdown-1.2.1.jar:/home/travis/.ivy2/cache/org.parboiled/parboiled-java/jars/parboiled-java-1.1.4.jar:/home/travis/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.4.jar:/home/travis/.ivy2/cache/org.ow2.asm/asm/jars/asm-4.1.jar:/home/travis/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-4.1.jar:/home/travis/.ivy2/cache/org.ow2.asm/asm-analysis/jars/asm-analysis-4.1.jar:/home/travis/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-4.1.jar:/home/travis/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.1.0.jar:/home/travis/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/bundles/scalaz-concurrent_2.11-7.1.0.jar:/home/travis/.ivy2/cache/org.scalaz/scalaz-effect_2.11/bundles/scalaz-effect_2.11-7.1.0.jar:/home/travis/.ivy2/cache/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.3.jar:/home/travis/.ivy2/cache/org.mockito/mockito-core/jars/mockito-core-1.9.5.jar:/home/travis/.ivy2/cache/org.objenesis/objenesis/jars/objenesis-1.0.jar:/home/travis/.ivy2/cache/junit/junit/jars/junit-4.11.jar:/home/travis/.ivy2/cache/org.specs2/classycle/jars/classycle-1.4.3.jar:/home/travis/.sbt/boot/scala-2.10.4/org.scala-sbt/sbt/0.13.7/test-agent-0.13.7.jar:/home/travis/.sbt/boot/scala-2.10.4/org.scala-sbt/sbt/0.13.7/test-interface-1.0.jar sbt.ForkMain 37497 failed with exit code 137
`

**Comment by BanzaiMan** [comment]
It'll be great if you could identify the JVM thread dump, dump its content. I'm thinking we'll have to send it upstream for further analysis. Do you have a build log URL?

**Comment by sebigavril** [comment]
I can't get the thread dump - I don't have access to the machine. We're running on a private repo on travis-ci.com, so i don't think the URL is accessable.

**Comment by JPrevost** [comment]
I had this happening in a public repo before I disabled fork in Test. Here's a sample build log where it happened.
https://travis-ci.org/MITLibraries/scoap3hub/builds/58442011

**Comment by sebigavril** [comment]
Disabling fork in tests isn't a solution for me - at this point in time at least.

**Comment by BanzaiMan** [comment]
Does the same problem happen with the standard infrastructure (`sudo: required`)?

**Comment by JPrevost** [comment]
We had `sudo: false` since February and didn't get this issue until early April. The fails did not appear to coincide with any announced changes, but I could be incorrect on that.

I'm reenabling fork in Test on my repo and will test with both `sudo: required` and `sudo: false`.

**Comment by JPrevost** [comment]
@BanzaiMan 
Fails on new infrastructure:
https://travis-ci.org/MITLibraries/scoap3hub/builds/60733975

Passes on old infrastructure:
https://travis-ci.org/MITLibraries/scoap3hub/builds/60735215

We'd occasionally get passed tests even on the old infrastructure though so this is not a guarantee to be anything other than coincidence.

**Comment by sebigavril** [comment]
@BanzaiMan `sudo: true` works most of the time - sometimes I would get this failure but very rarely. Restarting the build usually does the trick. `sudo: false` is failing almost every time.

**Comment by BanzaiMan** [comment]
I've changed `travis-build` in such a way that, at least `java` and `javac` would be able to print the version strings without halting the build. Could you try setting the `JAVA_OPTS` or equivalent on your builds, so that the build may run?

**Comment by JPrevost** [comment]
@BanzaiMan can you provide a suggestion for a change in `JAVA_OPTS` that might help? I'm happy to help debug this but it's unclear what you are suggesting might help. Thanks!

**Comment by sebigavril** [comment]
@BanzaiMan This is still occurring and it is a blocker for using the docker container. Please note @JPrevost's question regarding `JAVA_OPTS`

**Comment by tjdett** [comment]
The fix in nativelibs4java/scalaxy-streams@01ffbadeece7e2db8b21373fcdc25298845869d4 works. Extra memory for forks, as suggested in sbt/sbt#653.

**Comment by DwayneJengSage** [comment]
I'm also running into this issue.

My .travis.yml:
https://github.com/Sage-Bionetworks/BridgePF/blob/develop/.travis.yml

My built.sbt:
https://github.com/Sage-Bionetworks/BridgePF/blob/develop/build.sbt

I attempted to disable forking in tests, but this appears to have had no effect:
https://github.com/Sage-Bionetworks/BridgePF/pull/1433/files

Travis build without disabling fork:
https://travis-ci.org/Sage-Bionetworks/BridgePF/builds/228048525

Travis build disabling fork (also failed):
https://travis-ci.org/Sage-Bionetworks/BridgePF/builds/228077590

Please advise. Thanks!

**Comment by DwayneJengSage** [comment]
I'm still seeing this problem intermittently. One of my builds has failed twice with this error now.

Is there anything I can provide to help you track this down?

**Comment by DwayneJengSage** [comment]
This is still a problem for me. Is anyone looking at this?

**Comment by BanzaiMan** [comment]
I reckon the fork fails because there is not enough resources on the container host to do so. Try `sudo: required`, which gets your builds on a VM with more resources.

**Comment by michaelvoronov** [comment]
@redbaron thank you for your investigation and comment. Helped me in 2019 :).

**Comment by vasylyamnych** [comment]
@redbaron you helped me in 2023 :) - thank you!
