### ISSUE TITLE
Unable to deploy to openshift (No stash found.)

### ISSUE THREAD

**Issue by intrepido** [travis-ci/travis-ci#4112]
I'm trying to make deployments to OpenShift. This is my  `.travis.yml`

```
language: node_js
node_js:
- '0.10'
before_script: npm install -g karma-cli
deploy:
  provider: openshift
  user: in3fff732@gmail.com
  password:
    secure: U50sC8Sm2NKas5CiecPftu+NM4Y8xu1UEAHfoLoQpgKK6MnXLYZjPC0i/qmbigv40nvBu9t+xdbpUbGuOO12A8UASLIcGMIyeMCcN9yU+Ud4jJsA=
  app: citest2
  domain: fideltest
  on:
    repo: intrepido/CI-Test2
```

I get this error in travis build:

```
Using worker: worker-linux-docker-359335dc.prod.travis-ci.org:travis-linux-5

Build system information
Build language: node_js
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"

$ git clone --depth=50 --branch=master git://github.com/intrepido/CI-Test2.git intrepido/CI-Test2
Cloning into 'intrepido/CI-Test2'...
remote: Counting objects: 185, done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 185 (delta 103), reused 163 (delta 81), pack-reused 0
Receiving objects: 100% (185/185), 82.41 KiB | 0 bytes/s, done.
Resolving deltas: 100% (103/103), done.
Checking connectivity... done.
$ cd intrepido/CI-Test2
$ git checkout -qf 848d05b316a03c272d0faea88923d73c324f8939

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
$ nvm install 0.10
######################################################################## 100.0%
Now using node v0.10.38
$ node --version
v0.10.38
$ npm --version
1.4.28
$ nvm --version
0.23.3
$ npm install 
npm WARN package.json karma-sauce-example@0.0.0 No repository field.
npm WARN package.json karma-sauce-example@0.0.0 No README data
npm WARN optional dep failed, continuing fsevents@0.3.6

> phantomjs@1.9.17 install /home/travis/build/intrepido/CI-Test2/node_modules/phantomjs
> node install.js

Writing location.js file
PhantomJS is already installed at /usr/local/phantomjs/bin/phantomjs.

> ws@0.4.32 install /home/travis/build/intrepido/CI-Test2/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/travis/build/intrepido/CI-Test2/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/travis/build/intrepido/CI-Test2/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
karma-safari-launcher@0.1.1 node_modules/karma-safari-launcher

karma-firefox-launcher@0.1.6 node_modules/karma-firefox-launcher

karma-jasmine@0.2.3 node_modules/karma-jasmine

karma-chrome-launcher@0.1.12 node_modules/karma-chrome-launcher
└── which@1.1.1 (is-absolute@0.1.7)

karma-phantomjs-launcher@0.2.0 node_modules/karma-phantomjs-launcher
└── lodash@3.9.3

phantomjs@1.9.17 node_modules/phantomjs
├── which@1.0.9
├── progress@1.1.8
├── kew@0.4.0
├── request-progress@0.3.1 (throttleit@0.0.2)
├── adm-zip@0.4.4
├── npmconf@2.1.1 (uid-number@0.0.5, ini@1.3.4, inherits@2.0.1, once@1.3.2, osenv@0.1.2, config-chain@1.1.9, nopt@3.0.2, semver@4.3.6, mkdirp@0.5.1)
├── fs-extra@0.18.4 (jsonfile@2.0.1, graceful-fs@3.0.8, rimraf@2.4.0)
└── request@2.42.0 (caseless@0.6.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, json-stringify-safe@5.0.1, qs@1.2.2, node-uuid@1.4.3, mime-types@1.0.2, form-data@0.1.4, http-signature@0.10.1, bl@0.9.4, hawk@1.1.1, tough-cookie@2.0.0)

karma@0.12.36 node_modules/karma
├── di@0.0.1
├── graceful-fs@3.0.8
├── mime@1.3.4
├── colors@1.1.2
├── q@1.4.1
├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── rimraf@2.4.0 (glob@4.5.3)
├── useragent@2.1.7 (lru-cache@2.2.4)
├── chokidar@1.0.3 (arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, path-is-absolute@1.0.0, is-binary-path@1.0.1, readdirp@1.3.0, anymatch@1.3.0)
├── source-map@0.4.2 (amdefine@0.1.1)
├── http-proxy@0.10.4 (colors@0.6.2, pkginfo@0.3.0, utile@0.2.1)
├── connect@2.30.0 (cookie@0.1.3, bytes@2.1.0, utils-merge@1.0.0, cookie-signature@1.0.6, fresh@0.3.0, pause@0.0.1, response-time@2.3.1, vhost@3.0.0, content-type@1.0.1, on-headers@1.0.0, basic-auth-connect@1.0.0, parseurl@1.3.0, cookie-parser@1.3.5, depd@1.0.1, qs@2.4.2, http-errors@1.3.1, connect-timeout@1.6.2, debug@2.2.0, method-override@2.3.3, finalhandler@0.4.0, serve-favicon@2.3.0, csurf@1.8.3, morgan@1.6.0, express-session@1.11.3, serve-static@1.10.0, multiparty@3.3.2, type-is@1.6.3, body-parser@1.13.1, errorhandler@1.4.0, serve-index@1.7.0, compression@1.5.0)
├── log4js@0.6.26 (async@0.2.10, underscore@1.8.2, readable-stream@1.0.33, semver@4.3.6)
├── lodash@3.9.3
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)
$ npm install -g karma-cli
/home/travis/.nvm/v0.10.38/bin/karma -> /home/travis/.nvm/v0.10.38/lib/node_modules/karma-cli/bin/karma
karma-cli@0.0.4 /home/travis/.nvm/v0.10.38/lib/node_modules/karma-cli
└── resolve@0.5.1
$ npm test

> karma-sauce-example@0.0.0 test /home/travis/build/intrepido/CI-Test2
> karma start --single-run --browsers PhantomJS

INFO [karma]: Karma v0.12.36 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket 4LoWny-H9AkLJYO5hDau with id 95304112
PhantomJS 1.9.8 (Linux 0.0.0): Executed 0 of 2 SUCCESS (0 secs / 0 secs)
PhantomJS 1.9.8 (Linux 0.0.0): Executed 1 of 2 SUCCESS (0 secs / 0.001 secs)
PhantomJS 1.9.8 (Linux 0.0.0): Executed 2 of 2 SUCCESS (0 secs / 0.001 secs)
PhantomJS 1.9.8 (Linux 0.0.0): Executed 2 of 2 SUCCESS (0.002 secs / 0.001 secs)

The command "npm test" exited with 0.
Fetching: dpl-1.7.11.gem (100%)
Successfully installed dpl-1.7.11
1 gem installed
Installing deploy dependencies
Fetching: httpclient-2.4.0.gem (100%)
Successfully installed httpclient-2.4.0
1 gem installed
Fetching: open4-1.3.4.gem (100%)
Successfully installed open4-1.3.4
Fetching: highline-1.6.21.gem (100%)
Successfully installed highline-1.6.21
Fetching: commander-4.2.1.gem (100%)
Successfully installed commander-4.2.1
Fetching: archive-tar-minitar-0.5.2.gem (100%)
Successfully installed archive-tar-minitar-0.5.2
Fetching: net-ssh-2.9.2.gem (100%)
Successfully installed net-ssh-2.9.2
Fetching: net-ssh-gateway-1.2.0.gem (100%)
Successfully installed net-ssh-gateway-1.2.0
Fetching: net-ssh-multi-1.2.1.gem (100%)
Successfully installed net-ssh-multi-1.2.1
Fetching: net-scp-1.2.1.gem (100%)
Successfully installed net-scp-1.2.1
Fetching: rhc-1.35.4.gem (100%)
===========================================================================

If this is your first time installing the RHC tools, please run 'rhc setup'

===========================================================================
Successfully installed rhc-1.35.4
9 gems installed

Preparing deploy

No stash found.
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rhc-1.35.4/lib/rhc/rest/client.rb:750:in `handle_error!': Not authenticated (RHC::Rest::UnAuthorizedException)
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rhc-1.35.4/lib/rhc/rest/client.rb:423:in `block in request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rhc-1.35.4/lib/rhc/rest/client.rb:405:in `block in attempt'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rhc-1.35.4/lib/rhc/rest/client.rb:404:in `each'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rhc-1.35.4/lib/rhc/rest/client.rb:404:in `attempt'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rhc-1.35.4/lib/rhc/rest/client.rb:411:in `request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rhc-1.35.4/lib/rhc/rest/base.rb:30:in `rest_method'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rhc-1.35.4/lib/rhc/rest/client.rb:73:in `user'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/openshift.rb:17:in `user'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/openshift.rb:25:in `check_auth'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider.rb:122:in `block in deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider.rb:121:in `deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:32:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy

```

**Comment by AlexChesters** [comment]
I get the same error, did you manage to solve this?

**Comment by mayararysia** [comment]
#401 Unauthorized
Try checking user authentication.

**Comment by frederikmartin** [comment]
Any updates on this issue?

**Comment by BanzaiMan** [comment]
Is this still a problem?

If so, please add a build log URL that shows the problem. Thanks.
