### ISSUE TITLE
Out of Memory Exception with Android build.

### ISSUE THREAD

**Issue by jd-alexander** [travis-ci/travis-ci#4185]
I'm attempting to build my project but I'm getting this error when it reaches the groovy plugin.
This is my project https://travis-ci.org/jd-alexander/flender

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':flender-plugin:groovydoc'.
> java.lang.OutOfMemoryError: PermGen space
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1 mins 42.573 secs
Exception in thread "Thread-60" java.lang.OutOfMemoryError: PermGen space
	at java.util.prefs.XmlSupport.writeDoc(XmlSupport.java:276)
	at java.util.prefs.XmlSupport.exportMap(XmlSupport.java:355)
	at java.util.prefs.FileSystemPreferences$7.run(FileSystemPreferences.java:622)
	at java.util.prefs.FileSystemPreferences$7.run(FileSystemPreferences.java:615)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.prefs.FileSystemPreferences.writeBackCache(FileSystemPreferences.java:614)
	at java.util.prefs.FileSystemPreferences.syncSpiPrivileged(FileSystemPreferences.java:801)
	at java.util.prefs.FileSystemPreferences.access$2300(FileSystemPreferences.java:50)
```

**Comment by jd-alexander** [comment]
I simply changed the perm size from the root gradle.properties and everything works now.
org.gradle.daemon=true
org.gradle.jvmargs=-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m
VERSION_CODE=1
