### ISSUE TITLE
Appium can't start Instruments when run in Travis

### ISSUE THREAD

**Issue by uber5001** [travis-ci/travis-ci#4218]
When running appium on travis, appium can't start Instruments. I'm getting this error:

`warn: Instruments socket client never checked in; timing out (global)` [(see log)](https://travis-ci.org/uber5001/react-native-renderer/builds/70308454#L1431)

I've tried using `osx_image` xcode6.4, beta xcode6.3, and the default, with iphonesimulator 8.4, 8.3, and 8.1.

This seems identical to this issue within appium: appium/appium#3328, but I can only reproduce the issue in travis.

Also, for one build, I attempted to use the globally installed `appium` (from #2348), but it was not there, instead I got a `appium: command not found` [(see log)](https://travis-ci.org/uber5001/react-native-renderer/builds/70305355#L1359). This might be a separate problem. Let me know if I should create a separate issue for it.

**Comment by BanzaiMan** [comment]
Hello! I see that recent builds are passing (https://travis-ci.org/uber5001/react-native-renderer/builds). Is there still a problem for us to look at?

**Comment by uber5001** [comment]
I've switched over to using appium on sauce labs, but I think the issue still stands.

**Comment by michalmikolajczyk** [comment]
I am experiencing the same issue, using `osx_image: xcode6.4` and Appium 1.4.10. 
XCode 6.4 and Appium 1.4.10 work fine for me locally.

Please find the log from Travis below:

```
info: Launching instruments
info: [debug] Attempting to run app on iPad 2 (8.4 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPad 2 (8.4 Simulator)" /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/115718-2377-1edwfgl/myapp.app -e UIASCRIPT "/Users/travis/Library/Application Support/appium/bootstrap/bootstrap-f0bbd3ea2878e4fd.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.4","deviceName":"iPad 2","app":"http://myapp-ios.s3.amazonaws.com/simulator/myapp-Simulator-Latest.zip"}}
info: Client User-Agent string: admc/wd/0.3.12
info: [debug] Using downloadable app from desired caps: http://myapp-ios.s3.amazonaws.com/simulator/myapp-Simulator-Latest.zip
info: [debug] http://myapp-ios.s3.amazonaws.com/simulator/myapp-Simulator-Latest.zip downloaded to /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/115718-2377-xjow7g/appium-app.zip
info: [debug] Unzipping /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/115718-2377-xjow7g/appium-app.zip
info: [debug] Testing zip archive: /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/115718-2377-xjow7g/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using extracted app: /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/115718-2377-xjow7g/myapp.app
info: [debug] Creating new appium session 1db7d340-250d-4ad3-a907-ddbece3bdd1b
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Xcode version set to 6.4
info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 8.4
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.4","iOSSDKVersion":"8.4","deviceName":"iPad 2","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad 2 (8.4 Simulator)'
info: [debug] iOS sim UDID is 10517896-AD59-4310-A3E0-5C969D4F4CC5
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/115718-2377-xjow7g/myapp.app/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/115718-2377-xjow7g/myapp.app/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/travis/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.5/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
...
info: [debug] Dynamic bootstrap path: /Users/travis/Library/Application Support/appium/bootstrap/bootstrap-f0bbd3ea2878e4fd.js
info: [debug] Reusing dynamic bootstrap: /Users/travis/Library/Application Support/appium/bootstrap/bootstrap-f0bbd3ea2878e4fd.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.4","iOSSDKVersion":"8.4","deviceName":"iPad 2","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad 2 (8.4 Simulator)'
36minfo: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.4","iOSSDKVersion":"8.4","deviceName":"iPad 2","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad 2 (8.4 Simulator)'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase 10517896-AD59-4310-A3E0-5C969D4F4CC5 and timeout: 2000
info: node-simctl: Executing: xcrun with args: simctl erase 10517896-AD59-4310-A3E0-5C969D4F4CC5 and timeout: 2000
info: node-simctl: Executing: xcrun with args: simctl erase 10517896-AD59-4310-A3E0-5C969D4F4CC5 and timeout: 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/travis/Library/Developer/CoreSimulator/Devices/10517896-AD59-4310-A3E0-5C969D4F4CC5/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/travis/Library/Developer/CoreSimulator/Devices/10517896-AD59-4310-A3E0-5C969D4F4CC5/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Resetting Content and Settings for Simulator
info: node-simctl: Executing: xcrun with args: simctl erase 10517896-AD59-4310-A3E0-5C969D4F4CC5 and timeout: 2000
info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 8.* simulator log capture
info: [debug] Not pre-launching simulator
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPad 2 (8.4 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPad 2 (8.4 Simulator)" /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/115718-2377-xjow7g/myapp.app -e UIASCRIPT "/Users/travis/Library/Application Support/appium/bootstrap/bootstrap-f0bbd3ea2878e4fd.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator
info: [debug] Killall iOS Simulator
info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase 10517896-AD59-4310-A3E0-5C969D4F4CC5 and timeout: 2000
info: node-simctl: Executing: xcrun with args: simctl erase 10517896-AD59-4310-A3E0-5C969D4F4CC5 and timeout: 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/travis/Library/Developer/CoreSimulator/Devices/10517896-AD59-4310-A3E0-5C969D4F4CC5/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/travis/Library/Developer/CoreSimulator/Devices/10517896-AD59-4310-A3E0-5C969D4F4CC5/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Resetting Content and Settings for Simulator
info: node-simctl: Executing: xcrun with args: simctl erase 10517896-AD59-4310-A3E0-5C969D4F4CC5 and timeout: 2000
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Instruments never checked in
info: [debug] Error: Instruments never checked in
    at [object Object].Instruments.onInstrumentsExit (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:442:31)
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments never checked in)","origValue":"Instruments never checked in"},"sessionId":null}
info: <-- POST /wd/hub/session 500 220758.784 ms - 178 
info: Launching instruments
info: [debug] Attempting to run app on iPad 2 (8.4 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPad 2 (8.4 Simulator)" /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/115718-2377-xjow7g/myapp.app -e UIASCRIPT "/Users/travis/Library/Application Support/appium/bootstrap/bootstrap-f0bbd3ea2878e4fd.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...
info: --> DELETE /wd/hub/session {}
info: [debug] Trying to stop appium but there's no session, doing nothing
info: [debug] Responding to client with error: {"status":1,"value":{"message":"undefined status object"},"sessionId":null}
info: <-- DELETE /wd/hub/session 500 2.043 ms - 75 
```

**Comment by AlexeyYurchuk** [comment]
@michalmikolajczyk @BanzaiMan Same issue for me, also using osx_image: xcode6.4 and Appium 1.4.10 on travis. Locally on my mac all is working fine.

info: Welcome to Appium v1.4.10 (REV c97e824665ae82df682a0b540b38dfe8c13c8ac7)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"log":"appium.log","deviceName":"Iphone 5","platformName":"iOS","platformVersion":"8.4"}
info: Console LogLevel: debug
info: File LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/travis/build/fahlo/bkstg_mobile_automation/Fahlo.app","platformVersion":"8.4","platformName":"iOS","bundleId":"me.fahlo.getcloser","deviceName":"iPhone 5","sendKeyStrategy":"grouped","launchTimeout":"120000"}}
info: Client User-Agent string: Python-urllib/3.4
info: [debug] Using local app from desired caps: /Users/travis/build/fahlo/bkstg_mobile_automation/Fahlo.app
info: [debug] Creating new appium session 50457c6d-a07f-41f8-a7fd-0b2590e6099d
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Xcode version set to 6.4
info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 8.4
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.4","iOSSDKVersion":"8.4","deviceName":"iPhone 5","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5 (8.4 Simulator)'
info: [debug] iOS sim UDID is E43EBCA4-1140-48CF-971F-DCCBECE5F0E2
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info[39m: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/travis/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.5/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...
info: [debug] Dynamic bootstrap path: /Users/travis/Library/Application Support/appium/bootstrap/bootstrap-80c0830cdd605494.js
info: [debug] Creating or overwritting dynamic bootstrap: /Users/travis/Library/Application Support/appium/bootstrap/bootstrap-80c0830cdd605494.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.4","iOSSDKVersion":"8.4","deviceName":"iPhone 5","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5 (8.4 Simulator)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.4","iOSSDKVersion":"8.4","deviceName":"iPhone 5","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5 (8.4 Simulator)'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase E43EBCA4-1140-48CF-971F-DCCBECE5F0E2 and timeout: 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/travis/Library/Developer/CoreSimulator/Devices/E43EBCA4-1140-48CF-971F-DCCBECE5F0E2/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/travis/Library/Developer/CoreSimulator/Devices/E43EBCA4-1140-48CF-971F-DCCBECE5F0E2/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 8.* simulator log capture
info: [debug] Not pre-launching simulator
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone 5 (8.4 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 5 (8.4 Simulator)" /Users/travis/build/fahlo/bkstg_mobile_automation/Fahlo.app -e UIASCRIPT "/Users/travis/Library/Application Support/appium/bootstrap/bootstrap-80c0830cdd605494.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":120000}
info: [debug] [INST] Waiting for device to boot...
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on iPhone 5 (8.4 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 5 (8.4 Simulator)" /Users/travis/build/fahlo/bkstg_mobile_automation/Fahlo.app -e UIASCRIPT "/Users/travis/Library/Application Support/appium/bootstrap/bootstrap-80c0830cdd605494.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":120000}
info: [debug] [INST] Waiting for device to boot...
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #2
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on iPhone 5 (8.4 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 5 (8.4 Simulator)" /Users/travis/build/fahlo/bkstg_mobile_automation/Fahlo.app -e UIASCRIPT "/Users/travis/Library/Application Support/appium/bootstrap/bootstrap-80c0830cdd605494.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":120000}
info: [debug] [INST] Waiting for device to boot...
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #3
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on iPhone 5 (8.4 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 5 (8.4 Simulator)" /Users/travis/build/fahlo/bkstg_mobile_automation/Fahlo.app -e UIASCRIPT "/Users/travis/Library/Application Support/appium/bootstrap/bootstrap-80c0830cdd605494.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":120000}
info: [debug] [INST] Waiting for device to boot...
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase E43EBCA4-1140-48CF-971F-DCCBECE5F0E2 and timeout: 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/travis/Library/Developer/CoreSimulator/Devices/E43EBCA4-1140-48CF-971F-DCCBECE5F0E2/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/travis/Library/Developer/CoreSimulator/Devices/E43EBCA4-1140-48CF-971F-DCCBECE5F0E2/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Instruments never checked in
info: [debug] Error: Instruments never checked in

**Comment by adam-szabo** [comment]
Same here. If I set launch timeout to 10 minutes then it gives the following:

    error: Failed to start an Appium session, err was: Error: Requested a new session but one was in progress
    info: [debug] Error: Requested a new session but one was in progress

So it seems it's not that the Travis CI VM is too slow for the default launch timeout (90 sec).

**Comment by michalmikolajczyk** [comment]
@adam-szabo this was resolved. I got this message from support:


> Hope you are doing well. I'm happy to let you know that we have a fix for you. You can do this manually for now but it will integrated in our base OS X VMs shortly.
> Here is a Gist with the required files and script: https://gist.github.com/cotsog/f2503b93c2e0cd43b6eb
> In brief, you need to call the "instruments-auth.sh" script in your "before_install:" or "before_script:" directive and have both *.plist files in the same directory.

They will add the fix to all their VMs at one point. For now, this should work.

**Comment by adam-szabo** [comment]
@michalmikolajczyk This is awsome, it works now! Many thanks for sharing this, saved me from a lot of additional grey hair! :-) +1
