### ISSUE TITLE
pypy3 build error raised OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by messense** [travis-ci/travis-ci#4306]
https://travis-ci.org/jxtech/wechatpy/jobs/70571186

```
Using worker: worker-linux-docker-6c8f2685.prod.travis-ci.org:travis-linux-3

======================================================================
ERROR: test_shove_storage_access_token (test_session.WeChatSessionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jxtech/wechatpy/tests/test_session.py", line 118, in test_shove_storage_access_token
    client = WeChatClient(self.app_id, self.secret, session=uri)
  File "/home/travis/build/jxtech/wechatpy/wechatpy/client/__init__.py", line 36, in __init__
    super(WeChatClient, self).__init__(access_token, session)
  File "/home/travis/build/jxtech/wechatpy/wechatpy/client/base.py", line 35, in __init__
    from shove import Shove
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/shove/__init__.py", line 6, in <module>
    from shove.core import Shove
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/shove/core.py", line 9, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 436, in load_module
    return self._load_module(fullname)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 141, in decorated
    return fxn(self, module, *args, **kwargs)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 330, in _load_module
    code_object = self.get_code(name)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 423, in get_code
    self.set_data(bytecode_path, data)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 481, in set_data
    _os.mkdir(parent)
OSError: [Errno 13] Permission denied: '/opt/python/pypy3-2.4.0/lib-python/3/concurrent/__pycache__'

======================================================================
ERROR: test_shove_storage_init (test_session.WeChatSessionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jxtech/wechatpy/tests/test_session.py", line 113, in test_shove_storage_init
    client = WeChatClient(self.app_id, self.secret, session=uri)
  File "/home/travis/build/jxtech/wechatpy/wechatpy/client/__init__.py", line 36, in __init__
    super(WeChatClient, self).__init__(access_token, session)
  File "/home/travis/build/jxtech/wechatpy/wechatpy/client/base.py", line 35, in __init__
    from shove import Shove
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 436, in load_module
    return self._load_module(fullname)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 141, in decorated
    return fxn(self, module, *args, **kwargs)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 342, in _load_module
    exec(code_object, module.__dict__)
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/shove/__init__.py", line 6, in <module>
    from shove.core import Shove
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/shove/core.py", line 9, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 436, in load_module
    return self._load_module(fullname)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 141, in decorated
    return fxn(self, module, *args, **kwargs)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 330, in _load_module
    code_object = self.get_code(name)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 423, in get_code
    self.set_data(bytecode_path, data)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 481, in set_data
    _os.mkdir(parent)
OSError: [Errno 13] Permission denied: '/opt/python/pypy3-2.4.0/lib-python/3/concurrent/__pycache__'

Ran 195 tests in 52.781s

FAILED (errors=2)
travis_time:end:38bb0e97:start=1436665720231100137,finish=1436665774314886919,duration=54083786782
[0K
[31;1mThe command "nosetests -v --with-coverage --cover-package=wechatpy" exited with 1.[0m

Done. Your build exited with 1.
```

**Comment by BanzaiMan** [comment]
Not sure why pypy3 is trying to write to `/opt`. Does it happen with `sudo: required`?

**Comment by QuLogic** [comment]
I'd take a guess and say the `pypy3` packages on Travis does not correctly include all compiled bytecode copies of modules.

**Comment by BanzaiMan** [comment]
I dug around a little bit, but not quite sure what is causing the tests to write to `/opt` (as opposed to somewhere in `~/virtualenv`, just with PyPy3. It could very well be that our setup is incorrect, but I'm afraid I don't have expertise to troubleshoot.

@dstufft or @alex may have insight.

We are also happy to spin up a debug VM (on standard infrastructure, which appears to exhibit the same problem; https://travis-ci.org/jxtech/wechatpy/builds/70570941) if you like. Please email support@travis-ci.com.

**Comment by bashu** [comment]
same problem https://travis-ci.org/adamcharnock/django-su/jobs/71874768

**Comment by karolyi** [comment]
+1: https://travis-ci.org/karolyi/django-require/builds/89949692

**Comment by danilobellini** [comment]
+1 https://travis-ci.org/danilobellini/pytest-doctest-custom/jobs/150239928

A few days ago, the same happened to me in Arch Linux, and there I actually found the solution: it was just that some `*.pyc` compiled files were missing in the installation: https://bitbucket.org/danilobellini/bug_pypy3_arch/src

About Ubuntu, I think [this command](https://bitbucket.org/danilobellini/bug_pypy3_arch/src/0d34fa935ccfefc5126339d3da8aad43c8e9f85a/Dockerfile-ubuntu?fileviewer=file-view-default#Dockerfile-ubuntu-13) replacing `/opt/pypy3` by `/opt/python/pypy3-2.4.0` (twice) should fix that.

**Comment by jayvdb** [comment]
I suspect the cause is https://github.com/travis-ci/travis-ci/issues/6304

**Comment by danilobellini** [comment]
[My solution to avoid this issue](https://github.com/danilobellini/pytest-doctest-custom/blob/6166c0245356d832597877c264514f01334d4374/.travis.yml#L126) now includes multiple PyPy versions (the last stable versions available today, and the last PyPy3 alpha release).

#6304 might have something to do with this, but it would be a virtualenv/tox bug if it does. The environment that calls `tox` isn't the testing environment, fixing the Travis environment to include the symlink won't fix the virtualenvs that tox creates. Tox creates a virtualenv for each testing environment instead of using the "pypy3" directly. That should be easy to evaluate: just add a random requirement in tox.ini that the global/system pypy3 doesn't have installed, and import it in the tests.

**Comment by jayvdb** [comment]
It definately isnt a tox bug. I also dont think it is a pyenv bug.  Maybe virtualenv, but as I understand it... the bug is in the Travis setup which is not creating the necessary symlink.

**Comment by danilobellini** [comment]
I really think these are completely distinct issues. The error for the lack of a `pypy3` symlink is `ERROR:   pypy3: InterpreterNotFound: pypy3`. If there's any pypy3 file available, tox would only use it to create its own virtual environments. Try yourself with this tox.ini file:

```ini
[tox]
envlist = pypy3
skipsdist = True
[testenv]
commands = python -c 'print("HW")'
```

As the pypy3 there doesn't include every pre-compiled files, one doesn't need tox to trigger that `OSError: [Errno 13] Permission denied` error. One just need to use an import method that trigger that compilation. For example, if you have docker there, just try:

```shell
$ docker run --rm -u travis quay.io/travisci/travis-python bash -c 'source ~/virtualenv/pypy3/bin/activate && python -V && python -c "import importlib ; importlib.import_module(\"concurrent\")"'
Python 3.2.5 (b2091e973da6, Oct 19 2014, 18:29:55)
[PyPy 2.4.0 with GCC 4.6.3]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/__init__.py", line 124, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 821, in _gcd_import
    loader.load_module(name)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 436, in load_module
    return self._load_module(fullname)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 141, in decorated
    return fxn(self, module, *args, **kwargs)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 330, in _load_module
    code_object = self.get_code(name)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 423, in get_code
    self.set_data(bytecode_path, data)
  File "/opt/python/pypy3-2.4.0/lib-python/3/importlib/_bootstrap.py", line 481, in set_data
    _os.mkdir(parent)
OSError: [Errno 13] Permission denied: '/opt/python/pypy3-2.4.0/lib-python/3/concurrent/__pycache__'
```

The pypy3 binary distribution have to include every standard library file pre-compiled, that's what this issue is about. The easier workaround is to run the test command as root (with `sudo`, you can try `sudo bash -c [...]` instead of `bash -c [...]` in that docker command). Another workaround would be reinstalling pypy3 without sudo in the `.travis.yml` itself, so the user would have enough permission for compiling any missing parts. But the actual solution for that seem to be a pre-compilation to include the missing compiled files in the pre-installed pypy3.

**Comment by jayvdb** [comment]
#6304 wrt pypy3-2.4 is finding the interpreter, but it is finding the one in /opt, nol the one in the venv.
