### ISSUE TITLE
Caching build fails with ruby 2.2.1 and above, works fine with 2.2.0

### ISSUE THREAD

**Issue by jcoyne** [travis-ci/travis-ci#4822]
Here's the build with 2.2.0 where it works: https://travis-ci.org/projecthydra/hydra-editor/jobs/80956101
Fails with 2.2.1 https://travis-ci.org/projecthydra/hydra-editor/builds/80955996
Fails with 2.2.2 https://travis-ci.org/projecthydra/hydra-editor/builds/80955877
Fails with 2.2.3 https://travis-ci.org/projecthydra/hydra-editor/builds/80955667

Works with 2.2.3 if the cache is not on: https://travis-ci.org/projecthydra/hydra-editor/builds/80955336

Trace:

```
bundle exec rake
/home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'railties' (= 4.2.4) among 13 total gem(s) (Gem::LoadError)

Checked in 'GEM_PATH=/home/travis/.rvm/gems/ruby-2.2.3:/home/travis/.rvm/gems/ruby-2.2.3@global', execute `gem env` for more information
    from /home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
    from /home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
    from /home/travis/build/projecthydra/hydra-editor/vendor/bundle/ruby/2.2.0/bin/rails:22:in `<main>'
rake aborted!
Errno::ENOENT: No such file or directory @ sys_fail2 - (/tmp/d20150918-4118-1ycwbgo/internal, ./spec/internal)
/home/travis/build/projecthydra/hydra-editor/vendor/bundle/ruby/2.2.0/gems/engine_cart-0.7.1/lib/engine_cart/tasks/engine_cart.rake:45:in `block (3 levels) in <top (required)>'
/home/travis/build/projecthydra/hydra-editor/vendor/bundle/ruby/2.2.0/gems/engine_cart-0.7.1/lib/engine_cart/tasks/engine_cart.rake:29:in `block (2 levels) in <top (required)>'
/home/travis/build/projecthydra/hydra-editor/vendor/bundle/ruby/2.2.0/gems/engine_cart-0.7.1/lib/engine_cart/tasks/engine_cart.rake:85:in `block (2 levels) in <top (required)>'
/home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => engine_cart:create_test_rails_app
```

**Comment by atz** [comment]
Giving up caching or giving up testing multiple (common) versions of ruby both seem like terrible options.

**Comment by BanzaiMan** [comment]
Sorry for the silence. Is this still an issue?

**Comment by jcoyne** [comment]
I'm no longer able to duplicate it.
