### ISSUE TITLE
Can't use coverage in Python 3.2

### ISSUE THREAD

**Issue by ZuluPro** [travis-ci/travis-ci#4866]
Python 3.2 tests fails since today:
https://travis-ci.org/ZuluPro/django-dbbackup/jobs/82792977

```
$ coverage run setup.py test
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.5/bin/coverage", line 9, in <module>
    load_entry_point('coverage==4.0', 'console_scripts', 'coverage')()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/__init__.py", line 13, in <module>
    from coverage.control import Coverage, process_startup
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/control.py", line 14, in <module>
    from coverage.annotate import AnnotateReporter
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/annotate.py", line 81
    dest.write(u'  ')
                   ^
SyntaxError: invalid syntax
The command "coverage run setup.py test" exited with 1.
```

Here's an old job which succeed and failed after retry: https://travis-ci.org/ZuluPro/django-dbbackup/jobs/80029389

**Comment by BanzaiMan** [comment]
When a build starts failing without your code changing, it is often the underlying dependencies that changed and caused the sudden failure. Please compare the old and the new dependency versions to troubleshoot. Thanks.

**Comment by BanzaiMan** [comment]
Looks like there is a major release of `coverage`, version 4.0.

**Comment by ZuluPro** [comment]
Ok thanks, my fast fix:
```
pip install 'coverage<4'
```

**Comment by lrq3000** [comment]
@ZuluPro Thank's for the fix, the issue was driving me mad, and the error is very unhelpful. What is weird is that the issue only happens with Python 3.2 (I'm testing 2 different libraries against Python from 2.6 to 3.2 and even Pypy and Pypy3, no issue at all with all the others).

**Comment by ale5000-git** [comment]
For those interested I was able to setup codecov (in practice a wrapper for coverage) under all Python versions, look [here](https://github.com/ale5000-git/pycompatlayer/blob/master/.travis/setup_dependencies.sh).
