### ISSUE TITLE
Maven build with launch4j plugin not working

### ISSUE THREAD

**Issue by klaushauschild1984** [travis-ci/travis-ci#5176]
I have a maven build project that uses launch4j to package a binary bundle.
The TravisCI build fails:

[INFO] --- launch4j-maven-plugin:1.7.8:launch4j (default) @ halfnes ---
[INFO] Platform-specific work directory already exists: /home/travis/.m2/repository/net/sf/launch4j/launch4j/3.8.0
[INFO] launch4j: Compiling resources
[INFO] launch4j: Generated resource file...
[INFO] launch4j: LANGUAGE 0, 1
2 RCDATA BEGIN "1.5.0\0" END
18 RCDATA BEGIN "1\0" END
30 RCDATA BEGIN "2\0" END
25 RCDATA BEGIN "128\0" END
27 RCDATA BEGIN "1024\0" END
21 RCDATA BEGIN "http://java.com/download\0" END
20 RCDATA BEGIN "32\0" END
101 RCDATA BEGIN "An error occurred while starting the application.\0" END
102 RCDATA BEGIN "This application was configured to use a bundled Java Runtime Environment but the runtime is missing or corrupted.\0" END
103 RCDATA BEGIN "This application requires a Java Runtime Environment\0" END
104 RCDATA BEGIN "The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted.\0" END
17 RCDATA BEGIN "true\0" END
[ERROR] 
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/travis/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-linux/bin/windres": error=2, No such file or directory
	at net.sf.launch4j.Builder.build(Builder.java:146)
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:336)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/travis/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-linux/bin/windres": error=2, No such file or directory
	at net.sf.launch4j.Util.exec(Util.java:160)
	at net.sf.launch4j.Cmd.exec(Builder.java:212)
	at net.sf.launch4j.Builder.build(Builder.java:96)
	... 22 more
Caused by: java.io.IOException: Cannot run program "/home/travis/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-linux/bin/windres": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at net.sf.launch4j.Util.exec(Util.java:128)
	... 24 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 27 more

Is there a way to fix it?

**Comment by BanzaiMan** [comment]
Does the file exist?

```
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/travis/.m2/repository/net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-linux/bin/windres": error=2, No such file or directory
```

**Comment by klaushauschild1984** [comment]
I don't know. It works at my local mashine (Windows 10) all fine.

**Comment by klaushauschild1984** [comment]
I fieled an issue at launch4j too: https://github.com/lukaszlenart/launch4j-maven-plugin/issues/29

**Comment by klaushauschild1984** [comment]
Yes, the files exists. Here is the jar http://search.maven.org/remotecontent?filepath=net/sf/launch4j/launch4j/3.8.0/launch4j-3.8.0-workdir-linux.jar.

May the jar was not correctly extracted or the extracted files are not allowed the execute?

**Comment by BanzaiMan** [comment]
I'm sorry to say, but this seems like an application issue to me.

You can use the Docker image found at https://quay.io/repository/travisci/travis-jvm, run an interactive bash shell, and `su - travis` emulate the build script.

**Comment by klaushauschild1984** [comment]
Refering to lukaszlenart/launch4j-maven-plugin#29 the problem cause is maybe a missing 32bit glibc library installed in the used distribution.
How can I fix this for my build?

**Comment by pfolta** [comment]
I ran into the same problem. This is what you need to add to your .travis.yml to install the missing 32-bit libs:

```yml
sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install lib32z1 lib32ncurses5
```
