### ISSUE TITLE
Our uml sandbox experiences weird java issues in with JDK8 on GCE

### ISSUE THREAD

**Issue by jamo** [travis-ci/travis-ci#5220]
After the migration to GCE our build started to fail. 
Legacy: https://travis-ci.org/testmycode/tmc-server/builds/93342114
After being automigrated to GCE: https://travis-ci.org/testmycode/tmc-server/builds/95072844

After some troubleshooting we identified the issue to be our sandbox specific problem full log from the sandbox: https://github.com/testmycode/tmc-sandbox/issues/20

Experienced error (not with the java installed in travis, but in [tmc-sandbox](https://github.com/testmycode/tmc-sandbox):

```
An exception has occurred in the compiler (1.8.0_11). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.NullPointerException
    at com.sun.tools.javac.file.ZipFileIndexArchive$ZipFileIndexFileObject.<init>(ZipFileIndexArchive.java:121)
    at com.sun.tools.javac.file.ZipFileIndexArchive.getFileObject(ZipFileIndexArchive.java:76)
    at com.sun.tools.javac.file.JavacFileManager.listArchive(JavacFileManager.java:308)
    at com.sun.tools.javac.file.JavacFileManager.listContainer(JavacFileManager.java:355)
    at com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:624)
    at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2732)
    at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2428)
    at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
    at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:244)
    at com.sun.tools.javac.code.Symbol.complete(Symbol.java:560)
    at com.sun.tools.javac.code.Symbol$PackageSymbol.members(Symbol.java:845)
    at com.sun.tools.javac.comp.MemberEnter.importAll(MemberEnter.java:154)
    at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:523)
    at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
    at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:435)
    at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)
    at com.sun.tools.javac.code.Symbol.complete(Symbol.java:560)
    at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1024)
    at com.sun.tools.javac.comp.Enter.complete(Enter.java:497)
    at com.sun.tools.javac.comp.Enter.main(Enter.java:475)
    at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:985)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
    at com.sun.tools.javac.main.Main.compile(Main.java:381)
    at com.sun.tools.javac.main.Main.compile(Main.java:370)
    at com.sun.tools.javac.main.Main.compile(Main.java:361)
    at com.sun.tools.javac.Main.compile(Main.java:56)
    at com.sun.tools.javac.Main.main(Main.java:42)
```

Now as the GCE finally provides all features needed to build the UML sandbox in travis, we have confirmed this issue occurs also when building the [tmc-sandbox in travis](https://travis-ci.org/testmycode/tmc-sandbox/builds/94969396) don't let the build pass to fool you, it's just incorrect return values / errors from place we didn't prepare for.

However, the sandbox builds well with our Ubuntu 14.04.3 LTS systems.
Thus this issue is really experienced only in the GCE travis.

**Comment by meatballhat** [comment]
@jamox are you able to pin your builds on the legacy infrastructure for now while we dig into the issue?  Thank you! :smiley:

``` yaml
# in .travis.yml
group: legacy
```

**Comment by jamox** [comment]
Thanks @meatballhat - however, it seems that adding
```yml
 group: legacy
``` 
to our .travis.yml with or with out `sudo: true` had no effect: https://travis-ci.org/testmycode/tmc-server/jobs/95286777
> This job ran on our new platform for Legacy Precise builds. Please read our blog post for more information.

**Comment by jamox** [comment]
Since our integration test setup is rather complex I've created the minimal case to reproduce the issue: https://github.com/jamox/create-minimal-case-for-sandbox-gce-bug
https://travis-ci.org/jamox/create-minimal-case-for-sandbox-gce-bug/builds/95290807

**Comment by jamox** [comment]
I tried again forcing us back to the legacy infra and this time it worked: https://travis-ci.org/testmycode/tmc-server/builds/99002472
```yml
sudo: required
dist: precise
group: legacy
```

I'm not sure how to troubleshoot this myself as I'm unable to produce it locally...
However, with docker `--privileged --cap-add=ALL` we get even worse JVM crash. But that's expected since docker in just a container while GCE should be more close to full VM.

**Comment by jamox** [comment]
Hi 

It seems that the `group: legacy` no longer works. It's been a few weeks since our last test run on travis; I just pushed something and presumably by this issue the build broke. I can be sure that it weren't my changes (I only edited readme.. and the errors are more clearly related to other components failing...)
