### ISSUE TITLE
Test creation of an *hard* link fails 

### ISSUE THREAD

**Issue by pditommaso** [travis-ci/travis-ci#5233]
In the new build infrastructure I have a feature testing the creation of an hard link that fails with the message `Invalid cross-device link`. 

The complete stack trace reported is the following: 

    nextflow.extension.FilesExTest > create hard link with default name FAILED
      java.nio.file.FileSystemException: test1164200057240660623txt -> /tmp/test3076064279593455249/test1164200057240660623txt: Invalid cross-device link
            at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
            at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
            at sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:475)
            at java.nio.file.Files.createLink(Files.java:1039)
            at nextflow.extension.FilesEx.createLinkImpl(FilesEx.groovy:1371)
            at nextflow.extension.FilesEx.mklink(FilesEx.groovy:1360)
            at nextflow.extension.FilesEx.mklink(FilesEx.groovy:1400)
            at nextflow.extension.FilesExTest.create hard link with default name(FilesExTest.groovy:1109)

I'm unable to replicate this error in other environments and it passed as well in the legacy Travis build infrastructure.

**Comment by BanzaiMan** [comment]
`/tmp` is on a different file system, so creating a hard link fails.

**Comment by pditommaso** [comment]
Using a path other than `/tmp` solves the issue.
