### ISSUE TITLE
“There was an error while loading data, please try again”

### ISSUE THREAD

**Issue by migurski** [travis-ci/travis-ci#5273]
Builds for openaddresses/machine are showing errors. I see the message “There was an error while loading data, please try again” at these URLs:

* https://travis-ci.org/openaddresses/machine/builds/96319210
* https://travis-ci.org/openaddresses/machine/builds
* https://travis-ci.org/openaddresses/machine

**Comment by migurski** [comment]
Others are telling me that they can see these same results, so I suspect this might be an issue with my account. I have deleted all Travis cookies, logged back in with Github, and still see these errors.

**Comment by BanzaiMan** [comment]
@migurski Could you try logging out and back in?

**Comment by migurski** [comment]
Tried that, still seeing the same error.

**Comment by p** [comment]
Broken for me with a clean browser profile too (firefox). Network requests are all successful.

**Comment by p** [comment]
Works on iceweasel 37.2, broken on firefox 31.7.

**Comment by mattatobin** [comment]
Timestamp: 12/13/2015 5:24:14 PM
Error: The connection to wss://ws.pusherapp.com/app/5df8ac576dcccf4fd076?protocol=7&client=js&version=2.2.4&flash=false was interrupted while the page was loading.
Source File: https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js
Line: 24

On Pale Moon in the toolkit Error Console.. Does this have any baring.

**Comment by migurski** [comment]
My console log in this situation:

```
Attempting URL transition to /openaddresses/machine/builds/96319210
vendor-351b1e277defa2d951d681e6b03e7460.js:12:1043Preparing to transition from '' to ' main.repo.build'
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2370Transition #0: application: calling beforeModel hook
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2370Transition #0: application: calling deserialize hook
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2370Transition #0: application: calling afterModel hook
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2370Transition #0: main: calling beforeModel hook
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2370Transition #0: main: calling deserialize hook
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2370Transition #0: main: calling afterModel hook
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2370Transition #0: repo: calling beforeModel hook
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2370Transition #0: repo: calling deserialize hook
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2406Attempting transition to main.loading
vendor-351b1e277defa2d951d681e6b03e7460.js:12:3487generated -> route:main.loading 
Object
vendor-351b1e277defa2d951d681e6b03e7460.js:11:33754generated -> controller:application 
Object
vendor-351b1e277defa2d951d681e6b03e7460.js:11:33754generated -> controller:main 
Object
vendor-351b1e277defa2d951d681e6b03e7460.js:11:33754generated -> controller:main.loading 
Object
vendor-351b1e277defa2d951d681e6b03e7460.js:12:1792Intermediate-transitioned into 'main.loading'
vendor-351b1e277defa2d951d681e6b03e7460.js:11:33754generated -> controller:footer 
Object
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2406Attempting transition to main.error
vendor-351b1e277defa2d951d681e6b03e7460.js:12:3487generated -> route:main.error 
Object
vendor-351b1e277defa2d951d681e6b03e7460.js:12:1792Intermediate-transitioned into 'main.error'
vendor-351b1e277defa2d951d681e6b03e7460.js:11:55927Error while processing route: build Can't find variable: Symbol l@https://cdn.travis-ci.org/assets/travis-f127ddefb0974467d0a1d9417b7386ee.js:4:30056
l@https://cdn.travis-ci.org/assets/travis-f127ddefb0974467d0a1d9417b7386ee.js:4:30282
l@https://cdn.travis-ci.org/assets/travis-f127ddefb0974467d0a1d9417b7386ee.js:4:30282
l@https://cdn.travis-ci.org/assets/travis-f127ddefb0974467d0a1d9417b7386ee.js:4:30282
_fixReferences@https://cdn.travis-ci.org/assets/travis-f127ddefb0974467d0a1d9417b7386ee.js:5:73
normalizeResponse@https://cdn.travis-ci.org/assets/travis-f127ddefb0974467d0a1d9417b7386ee.js:4:30891
b@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:10:30394
r@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:10:29347
m@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:9:15692
normalizeResponse@https://cdn.travis-ci.org/assets/travis-f127ddefb0974467d0a1d9417b7386ee.js:4:27403
b@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:10:30394
r@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:10:29347
https://cdn.travis-ci.org/assets/travis-f127ddefb0974467d0a1d9417b7386ee.js:3:41868
y@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:19:11519
b@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:19:11614
g@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:19:11422
https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:13:6530
invoke@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:4:27002
flush@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:4:27531
flush@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:4:24666
end@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:4:13120
run@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:4:13639
l@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:10:3394
success@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:20:26412
c@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:2:8597
fireWith@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:2:17833
r@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:3:23331
t@https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:3:29531
vendor-351b1e277defa2d951d681e6b03e7460.js:19:2370Transition #0: build: transition was aborted
```

**Comment by sasrin** [comment]
I am also seeing same error message, when I try to access(with or without signing in using github  username) 

     https://travis-ci.org/cloudfoundry-incubator/cf-abacus

**Comment by idgserpro** [comment]
Same error here.Logged in or not. In Firefox and Chrome.

**Comment by drogus** [comment]
I'm really sorry for the issues, I used a function that's not available in older versions of firefox and chrome. I deployed a possible fix for the issue. Could someone having this problem confirm if it's fixed now?

**Comment by idgserpro** [comment]
@drogus same error:

```javascript
Error while processing route: build Symbol is not defined ReferenceError: Symbol is not defined
    at l (https://cdn.travis-ci.org/assets/travis-a9a4604fb6c5ffad01e51f059796fbee.js:4:30060)
    at l (https://cdn.travis-ci.org/assets/travis-a9a4604fb6c5ffad01e51f059796fbee.js:4:30291)
    at l (https://cdn.travis-ci.org/assets/travis-a9a4604fb6c5ffad01e51f059796fbee.js:4:30291)
    at l (https://cdn.travis-ci.org/assets/travis-a9a4604fb6c5ffad01e51f059796fbee.js:4:30291)
    at e.default.n.default.JSONSerializer.extend._fixReferences (https://cdn.travis-ci.org/assets/travis-a9a4604fb6c5ffad01e51f059796fbee.js:5:72)
    at e.default.n.default.JSONSerializer.extend.normalizeResponse (https://cdn.travis-ci.org/assets/travis-a9a4604fb6c5ffad01e51f059796fbee.js:4:30887)
    at b (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:10:16744)
    at r (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:10:15700)
    at m [as _super] (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:9:15687)
    at n.default.extend.normalizeResponse (https://cdn.travis-ci.org/assets/travis-a9a4604fb6c5ffad01e51f059796fbee.js:4:27407) vendor-351b1e277defa2d951d681e6b03e7460.js:11
Transition #0: build: transition was aborted 
```

I cleared the browser cache. I'm using Firefox 24.8.0 and Chrome 34.

**Comment by drogus** [comment]
Thanks for the info! I'm downloading ubuntu to install on virtual machine in order to properly reproduce it, I'll comment with any updates.

**Comment by drogus** [comment]
OK, now it should work, I've been able to reproduce it on Chrome 34 on Ubuntu and just deployed a fix. Let me know how it looks on your side.

**Comment by n1tehawk** [comment]
A quick check looks good. :sunglasses:  I've been affected by this issue on various platforms/browsers and can now access the build status pages again.

Regards, NiteHawk

**Comment by idgserpro** [comment]
@drogus I'm able to access with Firefox 24 and Chrome 34 on Ubuntu. Thanks!

**Comment by drogus** [comment]
Thanks for the info, closing.

**Comment by migurski** [comment]
:+1: works for me

**Comment by sasrin** [comment]
Thanks for the fix...It works on Safari and Firefox.
