### ISSUE TITLE
"currently running" on Travis CI not working

### ISSUE THREAD

**Issue by cybernet** [travis-ci/travis-ci#5282]
"currently running" on Travis CI is not showing any projects

**Comment by BanzaiMan** [comment]
Please indicate where you see this problem.

**Comment by cybernet** [comment]
on the main page
travis-ci.org

**Comment by BanzaiMan** [comment]
Please attach a screen shot or two, explaining what you are trying to do, what you have tried, and so on.

**Comment by cybernet** [comment]
![travis](https://cloud.githubusercontent.com/assets/125879/11770264/8c547af0-a202-11e5-9b78-7d182f441e69.png)

i don't see any projects there
aren't suppose to be some ?

**Comment by BanzaiMan** [comment]
Do you have any content blockers? Is JavaScript running? Do you see any error message on the console? Have you tried any other browser?

**Comment by Joshua-Anderson** [comment]
@BanzaiMan I have the same issue. Both Chrome and Firefox on linux show the loading animation forever.

JS Error from Chrome:

```
GET https://api.travis-ci.org/repos?include=repository.default_branch%2Cbranch.last_build%2Cbuild.commit 403 (Forbidden)
vendor-351b1e277defa2d951d681e6b03e7460.js:13 Error: Adapter operation failed
    at new Error (native)
    at Error.r (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:9:2103)
    at Error.e (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:20:1016)
    at Qe.extend.handleResponse (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:20:25048)
    at c.error (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:20:25631)
    at c (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:2:8592)
    at Object.d.fireWith (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:2:9409)
    at r (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:3:23345)
    at XMLHttpRequest.t (https://cdn.travis-ci.org/assets/vendor-351b1e277defa2d951d681e6b03e7460.js:3:29530)
```

**Comment by cybernet** [comment]
![firefox](https://cloud.githubusercontent.com/assets/125879/11774100/7d93856e-a23a-11e5-82dd-d0c8f29faac2.png)

tried on firefox, same issue, javascript is enabled


https://api.travis-ci.org/repos?include=repository.default_branch%2Cbranch.last_build%2Cbuild.commit Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by cybernet** [comment]
still not working !
any news ?

**Comment by cybernet** [comment]
you can mark this as fixed
