### ISSUE TITLE
:app:connectedProductionDebugAndroidTest Unable to install

### ISSUE THREAD

**Issue by SandroMachado** [travis-ci/travis-ci#5291]
Sometimes I got this error on Travis, any fix for this? I have a matrix configuration to my Travis project and it happens on both configurations (Android 16 an 19) but not every time. Sometimes it only happens on one configuration and after trying a few more times eventually the tests pass.

Most part of the time the issue happens on the configuration with Android 16.

```
com.android.ddmlib.InstallException: Unknown failure (Error: Could not access the Package Manager.  Is the system running?)
	at com.android.ddmlib.Device.installRemotePackage(Device.java:1160)
	at com.android.ddmlib.Device.installPackage(Device.java:881)
	at com.android.builder.testing.ConnectedDevice.installPackage(ConnectedDevice.java:91)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:124)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by SandroMachado** [comment]
It is fixed now.

**Comment by Nitratz** [comment]
could you tell me what was the error plz ?

**Comment by SandroMachado** [comment]
It was related to `out of memory` issues.
