### ISSUE TITLE
JDK 8 update highly appreciated - JDK 1.8.0_31 has problems

### ISSUE THREAD

**Issue by phax** [travis-ci/travis-ci#5487]
There are known compiler problems which were resolved in later versions.
An example output from https://travis-ci.org/phax/ph-html is e.g.
```
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ ph-html-jquery ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 17 source files to /home/travis/build/phax/ph-html/ph-html-jquery/target/test-classes
An exception has occurred in the compiler (1.8.0_31). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.AssertionError: isSubClass IMPLTYPE
  at com.sun.tools.javac.code.Symbol.isSubClass(Symbol.java:447)
  at com.sun.tools.javac.code.Symbol.isMemberOf(Symbol.java:456)
  at com.sun.tools.javac.code.Symbol$MethodSymbol.overrides(Symbol.java:1469)
  at com.sun.tools.javac.code.Types$ImplementationCache.implementationInternal(Types.java:2671)
  at com.sun.tools.javac.code.Types$ImplementationCache.get(Types.java:2653)
  at com.sun.tools.javac.code.Types.implementation(Types.java:2682)
  at com.sun.tools.javac.code.Symbol$MethodSymbol.implementation(Symbol.java:1529)
  at com.sun.tools.javac.code.Symbol$MethodSymbol.implementation(Symbol.java:1518)
  at com.sun.tools.javac.comp.Resolve.notOverriddenIn(Resolve.java:416)
  at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:402)
  at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:362)
  at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1448)
  at com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1618)
  at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1710)
  at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1662)
  at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker$2.lookup(DeferredAttr.java:1325)
  at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3325)
  at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3310)
  at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker.quicklyResolveMethod(DeferredAttr.java:1333)
  at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker.quicklyResolveMethod(DeferredAttr.java:1302)
  at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker.visitApply(DeferredAttr.java:1223)
  at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
  at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
  at com.sun.tools.javac.comp.DeferredAttr$FilterScanner.scan(DeferredAttr.java:901)
  at com.sun.tools.javac.comp.DeferredAttr.isDeferred(DeferredAttr.java:1088)
  at com.sun.tools.javac.comp.Attr.attribArgs(Attr.java:701)
  at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1834)
  at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
  at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
  at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:656)
  at com.sun.tools.javac.comp.Attr.visitExec(Attr.java:1611)
  at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1296)
  at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
  at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676)
  at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:692)
  at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1142)
  at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
  at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
  at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676)
  at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1035)
  at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
  at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
  at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676)
  at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4342)
  at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4252)
  at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4181)
  at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4156)
  at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
  at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
  at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
  at com.sun.tools.javac.main.Main.compile(Main.java:523)
  at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
  at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
  at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
  at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:153)
  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:483)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

Searching for this error message gives e.g.
https://bugs.openjdk.java.net/browse/JDK-8071783
https://bugs.openjdk.java.net/browse/JDK-8056984

The issue should be fixed with 8u45 as indicated by https://bugs.openjdk.java.net/browse/JDK-8064054

Running a local 1.8.0_66 also does not have this problem.
Thanks for your help.

**Comment by BanzaiMan** [comment]
Thanks for taking the time to open this issue. While we work on updates, please see https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-93881360 for the workaround.

I'm closing this as a duplicate.

**Comment by phax** [comment]
Thanks for the link - I missed that one :(
The workaround suggested in https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338 worked for me!
