### ISSUE TITLE
oraclesdk with java 7 fails

### ISSUE THREAD

**Issue by karussell** [travis-ci/travis-ci#5594]
While building a jar the job is killed due to OOM, so no unit test or similar failures which I could fix :)

See https://travis-ci.org/graphhopper/map-matching/jobs/107799408

Maybe this is a configuration issue on the machine as the other machines are okay or an oraclesdk problem (?). Can I increase the available RAM somehow for this?

```
[INFO] Building jar: /home/travis/build/graphhopper/map-matching/matching-web/target/map-matching-web-0.7-SNAPSHOT-jar-with-dependencies.jar
Cleaning up unclosed ZipFile for archive /home/travis/.m2/repository/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.jar
Exception in thread "pool-17-thread-22" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2052)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by enricopersiani** [comment]
This exact error happens also to our build, using `oraclejdk8` configuration. You can see the build log [here](https://travis-ci.org/wholeplatform/whole) at line 2458. Sadly, this unrecoverable failure behaves as a correctly terminated build.

    [INFO] --- tycho-packaging-plugin:0.23.0:package-plugin (default-package-plugin) @ org.eclipse.gef.lightweight ---
    [INFO] Building jar: /home/travis/build/wholeplatform/whole/whole-java-libs/org.whole.product.ef.releng/gef-build/org.eclipse.gef.lightweight/target/org.eclipse.gef.lightweight-3.10.200-SNAPSHOT.jar
    Exception in thread "pool-32-thread-17" java.lang.OutOfMemoryError: GC overhead limit exceeded
    	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
    	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
    	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by karussell** [comment]
Thanks @enricopersiani 

I'll try (when I get time ;)) to run maven via a shell script and pass:
```bash
export MAVEN_OPTS="-Xmx1g -Xms1g"
```

**Comment by karussell** [comment]
Hmmh, it looks like this is also possible via the pom.xml (?)

```xml
            <plugin>                
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <argLine>-Xmx1g -Xms1g</argLine>
                </configuration>
            </plugin>
```

**Comment by enricopersiani** [comment]
Our build fails during tycho-packaging-plugin:0.23.0:package-plugin, that is executed in the same maven process that is launched during the build. Surefire is only used for testing purposes, so it is launched in a differnt JVM.

**Comment by karussell** [comment]
First I thought my workaround with MAVEN_OPTS and the script worked and I lowered it to 600m (!). The reason behind this, I though, is that there is too few memory and maven uses X MB of RAM and a subprocess uses again X MB of RAM. See this post here: http://stackoverflow.com/a/2761855/194609

But then oraclejdk8 failed!? Now I've updated maven-assembly-plugin to 2.6 and everything seems to work.

**Comment by karussell** [comment]
Looks like they had and have problems with this for earlier versions too: https://issues.apache.org/jira/browse/MASSEMBLY-742 *This unset permission issue seems to be a regression even between 2.5.2 and 2.5.3. I will try to narrow it down and open a new issue.*
