### ISSUE TITLE
trying to work with API token for private dependencies

### ISSUE THREAD

**Issue by tansaku** [travis-ci/travis-ci#5774]
Hi Travis,

I'm just trying to work with a Github API-TOKEN to pull in some code from private repos as part of a build for a public repo:

https://docs.travis-ci.com/user/private-dependencies/#API-Token

The repo is:

https://github.com/saasbook/rag

I can see the before install step operating in the build:

![before install step](https://www.dropbox.com/s/4p0io7r1zv6h6gn/Screenshot%202016-03-10%2018.50.52.png?dl=1)

and I've exported the token from the command line like so:

```
travis env set CI_USER_TOKEN <RAW_TOKEN>--private
```

but I still get a failure which I assume is a permissions failure:

![before install step](https://www.dropbox.com/s/rmidwutyh3md2ml/Screenshot%202016-03-10%2018.51.56.png?dl=1)

```
Cloning into 'temp_repo'...

Warning: Permanently added the RSA host key for IP address '192.30.
25
2.131' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.
```

Is there anything else I should be doing?  Is what I'm trying even possible?

This is the private repo (which the token has access to) that I'm trying to pull code from:

https://github.com/saasbook/saasbook/hw-ruby-intro-ci

Many thanks in advance.

**Comment by tansaku** [comment]
You can find links to the failing travis builds in the experimental pull request below:

https://github.com/saasbook/rag/pull/84

e.g.

https://travis-ci.org/saasbook/rag/builds/115138428

**Comment by BanzaiMan** [comment]
In https://travis-ci.org/saasbook/rag/builds/115138428, I see `CI_USER_TOKEN` is set twice (lines 124 and 127). Are they setting the same value? Or, more precisely, the value set in `.travis.yml` correct?

**Comment by tansaku** [comment]
hi @BanzaiMan I just added the 2nd value as an experiment - originally I only had it in the env variables, but that didn't work, so I thought I'd try the other route too.  I guess I could remove from the env vars and have another go with just the value in .travis.yml, but they are both the same token

**Comment by tansaku** [comment]
my more fundamental question is whether this should all work at all?  We don't need a travis pro account for this?

We're just following the instructions here:

https://docs.travis-ci.com/user/private-dependencies/#API-Token

Is that the right approach?

**Comment by tansaku** [comment]
anyway, I've deleted the env var in travis and re-started the build to see if that helps

**Comment by tansaku** [comment]
Dominic Jodin said:

> 
As said in the GitHub issue, can you try with setting the CI_USER_TOKEN environment variable only in one place? i.e. only in the repository settings or only in the .travis.yml file.

> Also, can you confirm if the value was encrypted in the local directory of your repository? i.e. can you try again encrypting the value doing the following steps:

> 0) travis logout --org
> 1) travis login --org
> 2) cd path/to/saasbook/rag
> 3) travis env set CI_USER_TOKEN <RAW_TOKEN> --private

> or

> 3a) travis encrypt CI_USER_TOKEN=<RAW_TOKEN> --add
> 3b) then commit your .travis.yml file

> Thank you for checking this out and please send us a link to the generated build log so we can have a look.

**Comment by tansaku** [comment]
Hi Dominic,

Thanks.  I did start with the CI_USER_TOKEN only set in the environment variables of the TRAVIS settings (not the .travis.yml) file, and when that didn't work I added it to the travis.yml file via encrypt.  I've now removed it from the TRAVIS web settings, so we've had the failure with all four combinations, i.e. 

1) fails with no token
2) fails with token in .travis.yml
3) fails with token in web settings
4) fails with token in both .travis.yml and web settings.

I can confirm that the value was indeed encrypted in the local directory of the repository.  I've followed the steps you suggest to update the .travis.yml file again and pushed that - here's the command history:

```
→ travis logout --org
Successfully logged out!
[tansaku@Samuels-MBP:~/Documents/GitHub/saasbook/rag (70_testing_with_secure_solutions)]$ 
→ travis login --org
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: tansaku
Password for tansaku: **********
Successfully logged in as tansaku!
→ travis encrypt CI_USER_TOKEN=RAW_TOKEN --add
[tansaku@Samuels-MBP:~/Documents/GitHub/saasbook/rag (70_testing_with_secure_solutions)]$ 
[tansaku@Samuels-MBP:~/Documents/GitHub/saasbook/rag (70_testing_with_secure_solutions)]$ 
→ git commit -am 're-adds token after travis logout --org and travis login --org'
[70_testing_with_secure_solutions 052d7c4] re-adds token after travis logout --org and travis login --org
 1 file changed, 1 insertion(+), 1 deletion(-)
[tansaku@Samuels-MBP:~/Documents/GitHub/saasbook/rag (70_testing_with_secure_solutions)]$ 
→ git push origin 70_testing_with_secure_solutions 
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 497 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To https://github.com/saasbook/rag
   9c06e12..052d7c4  70_testing_with_secure_solutions -> 70_testing_with_secure_solutions
```

so we'll see if that helps.  Can I confirm one thing?  Does the token need to be encased in quotes?  Or just in as a completely raw string as it comes from GitHub?  I've been going with the completely raw string so far ...

**Comment by henrikhodne** [comment]
@tansaku The "Permission denied (pubkey)" error makes it look like you're trying to clone the private repository from its Git URL, not its HTTPS URL. The token is only valid for HTTPS clones. Could you check the URL you're trying to clone and make sure it's `https://github.com/…` and not `git@github.com:…`?

**Comment by tansaku** [comment]
thanks @henrikhodne - great suggestion.  We are indeed working against `git@github.com:` I've changed that around and gotten this error:

```
      expected PutResultException, got 404 => Net::HTTPNotFound for https://github.com/saasbook/hw-ruby-intro-ci -- unhandled response with backtrace:
        # ./vendor/bundle/ruby/2.2.0/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:308:in `fetch'
        # ./vendor/bundle/ruby/2.2.0/gems/mechanize-2.7.3/lib/mechanize.rb:440:in `get'
```

in https://travis-ci.org/saasbook/rag/builds/115820012

which makes me think that perhaps some of our other setup does not support https?  Although I guess it still could be a token permission issue.

Do we have an alternative that would allow us to work with git@github.com?  Is that https://docs.travis-ci.com/user/private-dependencies/#User-Key which only works with Travis Pro?

I'm thinking I might need to set up a small test repo to make progress with all this ...

**Comment by tansaku** [comment]
I've created a simple test repo which also fails even with cloning an https git repo ...

https://travis-ci.org/saasbook/rag-simple/builds/115840287

**Comment by henrikhodne** [comment]
@tansaku Looks like your test project never puts the GitHub token in the .netrc file.

As for the error you get on your main build, it looks like maybe the tools you use to clone the GitHub repo doesn't support using the credentials in .netrc.

Another option for including a private SSH key for the Git repo is to include it in the repository, but encrypt the file: https://docs.travis-ci.com/user/encrypting-files/

**Comment by tansaku** [comment]
Hi @henrikhodne thanks - yes the test project started working as soon as I pulled the .netrc file in and I have the main build working now that I made some changes to ensure that we use https rather than git AND to ensure that cloning an https repo goes via a system call rather than the other mechanism we seem to have in place for handling some fake web addresses.

Thanks so much for your help, and to @BanzaiMan and to Dominic - I really appreciate you all taking the time.

Can I just confirm now how secure the different options are, and how they might work for 3rd party developers:  

1. Encrypted GitHub API token in the travis environment settings (not .travis.yml)

  * pretty secure as no one can see even see the encrypted token at all
  * contributing 3rd party developers can't run the tests locally as they won't have access to private repos, but will get travis builds on PRs they submit

2. Encrypted GitHub API token in the .travis.yml settings

  * not as secure since the encrypted token is publically visible, but presumably hard to crack?
  * contributing 3rd party developers can't run the tests locally as they won't have access to private repos, but can now get travis builds running on their forked repos?  e.g. 3rdPartyDev/saasbook ?

3. Encrypted Private SSH key in the repo

  * security same as 2. above
  * 3rd party dev same as 2. above? but also can run on their local machines?

4. Travis Pro SSH User Key

  * security same as 1. above?
  * 3rd party dev same as 1. above?

If you could correct any misunderstanding on my part about the above pros and cons I would be very grateful indeed.

**Comment by henrikhodne** [comment]
The overview you write looks correct, except that for anything that uses encrypted variables in either the .travis.yml or the repository settings, the only combination that will decrypt the variables is either a build created due to a push to one of the branches on the repository, or a pull request originating from the same repository. So, if someone forks the repository and runs a build on their repository, or opens a pull request from a fork, those will not have access to the encrypted variables. Build will still run, just without the encrypted variables.

The reasoning for this is that if we did decrypt it, there's not really anything stopping a malicious person from submitting a pull request that prints out the secret information.

**Comment by tansaku** [comment]
thanks @henrikhodne that makes sense - once decrypted for that build the token ends up as a plain text environment variable.

So in conclusion it seems that if the build is relying on a something private, there's no way for a 3rd party submission to be validated unless it is actually pulled into the main repo (i.e. by involving someone with push rights on that repo), which is a shame, since it prevents 3rd parties independently validating that they haven't accidentally broken part of the system, but I guess there's no way round that with the current model ...?

**Comment by henrikhodne** [comment]
Correct, the way we recommend doing it is to run all the tests that don't depend on the secure variables if `TRAVIS_SECURE_ENV_VARS=false` (which it is for pull requests), and then when you've verified that it's not doing anything malicious you can pull down the changes locally and push them to a branch to "approve" them and run the full set of builds.
