### ISSUE TITLE
Beanstalk service in container based infrastructure.

### ISSUE THREAD

**Issue by pavanvamsi3** [travis-ci/travis-ci#5865]
I'm running travis on my php 7.0 project. I'm not able to get apt packages when I add them under addons.apt.packages. Facing this issue when I'm moving from legacy to container based infrastructure.

**Comment by pavanvamsi3** [comment]
@Banzaiman: ^

**Comment by BanzaiMan** [comment]
Could you point to a build log URL?

**Comment by pavanvamsi3** [comment]
I am getting the mentioned apt packages and along with that I get this in build.

`  Exception:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/commands/install.py", line 347, in run
      root=options.root_path,
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_set.py", line 549, in install
      **kwargs
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_install.py", line 754, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_install.py", line 963, in move_wheel_files
      isolated=self.isolated,
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/wheel.py", line 234, in move_wheel_files
      clobber(source, lib_dir, True)
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/wheel.py", line 212, in clobber
      shutil.copyfile(srcfile, destfile)
    File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
      with open(dst, 'wb') as fdst:
  IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/virtualenv.py'
before-install.sh: line 5: virtualenv: command not found`

**Comment by BanzaiMan** [comment]
Please point to a build log URL that shows the problem. Thanks.

**Comment by ushuz** [comment]
@BanzaiMan 

Same problem. Related build log below. And we have experienced same `apt-get` problems several times on Travis CI.

```
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/InRelease  
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.15 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.15 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libc-dev-bin libc6-dev
Suggested packages:
  glibc-doc
The following packages will be upgraded:
  libc-dev-bin libc6 libc6-dev
3 upgraded, 0 newly installed, 0 to remove and 152 not upgraded.
Need to get 6,698 kB of archives.
After this operation, 1,024 B of additional disk space will be used.
Get:1 http://security.ubuntu.com/ubuntu/ trusty-security/main libc6-dev amd64 2.19-0ubuntu6.7 [1,910 kB]
Get:2 http://security.ubuntu.com/ubuntu/ trusty-security/main libc-dev-bin amd64 2.19-0ubuntu6.7 [69.0 kB]
Get:3 http://security.ubuntu.com/ubuntu/ trusty-security/main libc6 amd64 2.19-0ubuntu6.7 [4,719 kB]
Get:4 http://security.ubuntu.com/ubuntu/ trusty-security/main libc-dev-bin amd64 2.19-0ubuntu6.7 [69.0 kB]
Fetched 6,676 kB in 2min 39s (41.8 kB/s)
Preconfiguring packages ...
(Reading database ... 135346 files and directories currently installed.)
Preparing to unpack .../libc6-dev_2.19-0ubuntu6.7_amd64.deb ...
Unpacking libc6-dev:amd64 (2.19-0ubuntu6.7) over (2.19-0ubuntu6.6) ...
Preparing to unpack .../libc-dev-bin_2.19-0ubuntu6.7_amd64.deb ...
Unpacking libc-dev-bin (2.19-0ubuntu6.7) over (2.19-0ubuntu6.6) ...
Preparing to unpack .../libc6_2.19-0ubuntu6.7_amd64.deb ...
Unpacking libc6:amd64 (2.19-0ubuntu6.7) over (2.19-0ubuntu6.6) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Not building database; man-db/auto-update is not 'true'.
Setting up libc6:amd64 (2.19-0ubuntu6.7) ...
Setting up libc-dev-bin (2.19-0ubuntu6.7) ...
Setting up libc6-dev:amd64 (2.19-0ubuntu6.7) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...

$ export DEBIAN_FRONTEND=noninteractive
$ sudo -E apt-get -yq update &>> ~/apt-get-update.log

$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install mysql-client-5.6 mysql-client-core-5.6 mysql-server-5.6
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-client-5.6 : Depends: libaio1 (>= 0.3.93) but it is not installable
 mysql-client-core-5.6 : Depends: libaio1 (>= 0.3.93) but it is not installable
 mysql-server-5.6 : Depends: mysql-server-core-5.6 (= 5.6.28-0ubuntu0.14.04.1) but it is not going to be installed
                    Depends: libaio1 (>= 0.3.93) but it is not installable
E: Unable to correct problems, you have held broken packages.

apt-get install failed
$ cat ~/apt-get-update.log
Ign http://dl.google.com stable InRelease
Get:1 http://dl.google.com stable Release.gpg [181 B]
Get:2 http://dl.google.com stable Release [1,189 B]
Get:3 http://dl.google.com stable/main amd64 Packages [1,355 B]
Get:4 http://ppa.launchpad.net trusty InRelease [15.5 kB]
Get:5 https://apt.dockerproject.org ubuntu-trusty InRelease
Ign https://apt.dockerproject.org ubuntu-trusty InRelease
Get:6 https://apt.dockerproject.org ubuntu-trusty Release
Get:7 https://apt.dockerproject.org ubuntu-trusty/main amd64 Packages
Get:8 http://apt.postgresql.org trusty-pgdg InRelease [30.1 kB]
Get:9 https://apt.dockerproject.org ubuntu-trusty/main Translation-en_US
Ign http://dl.google.com stable/main Translation-en_US
Ign http://dl.google.com stable/main Translation-en
Get:10 http://ppa.launchpad.net trusty InRelease [15.4 kB]
Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en_US
Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en
Get:11 http://ppa.launchpad.net trusty InRelease [15.5 kB]
Get:12 http://apt.postgresql.org trusty-pgdg/main amd64 Packages [58.1 kB]
Get:13 http://ppa.launchpad.net trusty InRelease [15.4 kB]
Get:14 http://ppa.launchpad.net trusty InRelease [15.5 kB]
Get:15 http://ppa.launchpad.net trusty/main amd64 Packages [1,773 B]
Get:16 http://apt.postgresql.org trusty-pgdg/9.4 amd64 Packages [1,910 B]
Get:17 http://ppa.launchpad.net trusty/main Translation-en [1,230 B]
Get:18 http://ppa.launchpad.net trusty/main amd64 Packages [3,338 B]
Get:19 http://ppa.launchpad.net trusty/main Translation-en [2,645 B]
Get:20 http://ppa.launchpad.net trusty/main amd64 Packages [5,590 B]
Get:21 http://ppa.launchpad.net trusty/main Translation-en [2,899 B]
Get:22 http://ppa.launchpad.net trusty/main amd64 Packages [703 B]
Get:23 http://ppa.launchpad.net trusty/main Translation-en [464 B]
Get:24 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Get:25 http://ppa.launchpad.net trusty/main amd64 Packages [3,388 B]
Get:26 http://ppa.launchpad.net trusty/main Translation-en [1,556 B]
Get:27 http://security.ubuntu.com trusty-security/main Sources [110 kB]
Get:28 http://security.ubuntu.com trusty-security/universe Sources [35.2 kB]
Get:29 http://security.ubuntu.com trusty-security/main amd64 Packages [455 kB]
Get:30 http://security.ubuntu.com trusty-security/universe amd64 Packages [126 kB]
Ign http://apt.postgresql.org trusty-pgdg/9.4 Translation-en_US
Ign http://apt.postgresql.org trusty-pgdg/9.4 Translation-en
Get:31 http://security.ubuntu.com trusty-security/main Translation-en [250 kB]
Ign http://apt.postgresql.org trusty-pgdg/main Translation-en_US
Ign http://apt.postgresql.org trusty-pgdg/main Translation-en
Get:32 http://security.ubuntu.com trusty-security/universe Translation-en [74.5 kB]
Err http://us.archive.ubuntu.com trusty InRelease
Err http://us.archive.ubuntu.com trusty-updates InRelease
Err http://us.archive.ubuntu.com trusty Release.gpg
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.15 80]
Err http://us.archive.ubuntu.com trusty-updates Release.gpg
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.15 80]
Fetched 1,336 kB in 47s (28.1 kB/s)
Reading package lists...
Ign http://dl.google.com stable InRelease
Hit http://dl.google.com stable Release.gpg
Hit http://dl.google.com stable Release
Hit http://dl.google.com stable/main amd64 Packages
Get:1 https://apt.dockerproject.org ubuntu-trusty InRelease
Ign https://apt.dockerproject.org ubuntu-trusty InRelease
Hit https://apt.dockerproject.org ubuntu-trusty Release.gpg
Hit https://apt.dockerproject.org ubuntu-trusty Release
Hit http://ppa.launchpad.net trusty InRelease
Hit https://apt.dockerproject.org ubuntu-trusty/main amd64 Packages
Get:2 https://apt.dockerproject.org ubuntu-trusty/main Translation-en_US
Ign http://dl.google.com stable/main Translation-en_US
Ign http://dl.google.com stable/main Translation-en
Hit http://apt.postgresql.org trusty-pgdg InRelease
Hit http://ppa.launchpad.net trusty InRelease
Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en_US
Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en
Hit http://ppa.launchpad.net trusty InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://apt.postgresql.org trusty-pgdg/main amd64 Packages
Hit http://ppa.launchpad.net trusty InRelease
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://apt.postgresql.org trusty-pgdg/9.4 amd64 Packages
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Ign http://apt.postgresql.org trusty-pgdg/9.4 Translation-en_US
Ign http://apt.postgresql.org trusty-pgdg/9.4 Translation-en
Ign http://apt.postgresql.org trusty-pgdg/main Translation-en_US
Ign http://apt.postgresql.org trusty-pgdg/main Translation-en
Ign http://us.archive.ubuntu.com trusty InRelease
Get:3 http://us.archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:4 http://us.archive.ubuntu.com trusty Release.gpg [933 B]
Get:5 http://us.archive.ubuntu.com trusty-updates/main Sources [271 kB]
Hit http://security.ubuntu.com trusty-security InRelease
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Err http://us.archive.ubuntu.com trusty Release
Err http://us.archive.ubuntu.com trusty-updates/universe Sources
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty-updates/main amd64 Packages
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty-updates/universe amd64 Packages
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty-updates/main Translation-en
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty-updates/universe Translation-en
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty/main Sources
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty/universe Sources
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty/main amd64 Packages
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty/universe amd64 Packages
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty/main Translation-en_US
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty/main Translation-en
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty/universe Translation-en_US
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com trusty/universe Translation-en
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Fetched 338 kB in 51s (6,530 B/s)
Reading package lists...
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/source/Sources  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/i18n/Translation-en  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/i18n/Translation-en  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/Release  
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/main/source/Sources  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/universe/source/Sources  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/universe/binary-amd64/Packages  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/main/i18n/Translation-en_US  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/universe/i18n/Translation-en_US  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty/universe/i18n/Translation-en  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install mysql-client-5.6 mysql-client-core-5.6 mysql-server-5.6" failed and exited with 100 during .

Your build has been stopped.
```

**Comment by BanzaiMan** [comment]
@ushuz Please point to a build log URL. This log is incomplete. If this is on a private repository and you'd rather not discuss it in public, please send email to support@travis-ci.com. Thanks.

**Comment by pavanvamsi3** [comment]
Thanks for that @BanzaiMan. Although I have another issue, I want to start beanstalkd service which I'm not able to. Any work around for this?

**Comment by BanzaiMan** [comment]
I'm going to close this as it is superseded by #5883.
