### ISSUE TITLE
PATH is not properly set up - caching phase for non-Ruby jobs

### ISSUE THREAD

**Issue by blimmer** [travis-ci/travis-ci#5929]
I'm getting this warning when the cache is set up in the beginning and saved at the end.

```
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.3/bin' is not at first place,
usually this is caused by shell initialization files - check them for 'PATH=...' entries,
it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
```

Example build [here](https://travis-ci.com/Ibotta/partner-portal#L1718).

**Comment by BanzaiMan** [comment]
Looks like on the Trusty image this following line is missing from `/etc/profile`:

```shell
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
```

**Comment by BanzaiMan** [comment]
This is fixed in the edge image.

```yaml
group: edge
```

at the top level of `.travis.yml`.

**Comment by BanzaiMan** [comment]
Some `$PATH` components are improperly set up with Trusty.

**Comment by BanzaiMan** [comment]
Despite this message, caching appears to work.

**Comment by BanzaiMan** [comment]
Ruby jobs do not show this warning.

**Comment by vineus** [comment]
Hello there,

I'm having the exact same issue since today on builds using elastic beanstalk deployment.

Didn't happened on 2016-07-01 though.

```
travis_time:end:1846144e:start=1467646001590828948,finish=1467646003467137742,duration=1876308794
[0Ktravis_fold:end:after_success
[0Ktravis_fold:start:dpl.0
[0Ktravis_time:start:07137bbb
[0KWarning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
Warning, new version of rvm available '1.27.0', you are using older version '1.26.11'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Fetching: dpl-1.8.18.travis.1472.4.gem
Fetching: dpl-1.8.18.travis.1472.4.gem (  3%)
Fetching: dpl-1.8.18.travis.1472.4.gem (  7%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 11%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 15%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 19%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 23%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 27%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 31%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 35%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 39%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 43%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 47%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 71%)
Fetching: dpl-1.8.18.travis.1472.4.gem ( 94%)
Fetching: dpl-1.8.18.travis.1472.4.gem (100%)
Fetching: dpl-1.8.18.travis.1472.4.gem (100%)
Successfully installed dpl-1.8.18.travis.1472.4
1 gem installed

travis_time:end:07137bbb:start=1467646003472280870,finish=1467646005201183719,duration=1728902849
[0Ktravis_fold:end:dpl.0
[0Ktravis_time:start:28ad7673
[0KWarning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- json/pure (LoadError)
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18.travis.1472.4/lib/dpl/provider.rb:4:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18.travis.1472.4/lib/dpl/cli.rb:2:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18.travis.1472.4/bin/dpl:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment]
You are using the `--pre` release with `edge: true`, which was broken for a while. It is unrelated.

**Comment by vineus** [comment]
OK thx! Removing edge fixed the builds indeed, I needed it a while back but not anymore.

**Comment by Wulf** [comment]
https://travis-ci.org/Wulf/nodehun/jobs/167005152

Mac build is failing, and this is a non-ruby project.
