### ISSUE TITLE
cukes fail but not build

### ISSUE THREAD

**Issue by tansaku** [travis-ci/travis-ci#5945]
Hi Travis,

Travis rocks, but I just had a weird issue where the cukes failed but the build didn't:

![](https://www.dropbox.com/s/zbswdyq1c210wec/Screenshot%202016-04-22%2010.19.06.png?dl=1)

https://travis-ci.org/AgileVentures/LocalSupport/builds/124907501

![](https://www.dropbox.com/s/0t1sd59ajg4lowr/Screenshot%202016-04-22%2010.20.39.png?dl=1)

Usually if cukes break the build breaks - any idea why that didn't happen on this occasion?

Many thanks in advance

**Comment by BanzaiMan** [comment]
You are running a custom `rake` task `test_with_coveralls`. If that task does not exit with non-zero status when the test fails, we are unable to fail the build. Please review your `rake` task.

**Comment by tansaku** [comment]
@BanzaiMan thanks for pointing that out - it seems that Cucumber was exiting with zero, even when we have a test failure.  I just fixed that by adding this to our Cucumber env.rb file:

```ruby
After do |s| 
  # Tell Cucumber to quit after this scenario is done - if it failed.
  Cucumber.wants_to_quit = true if s.failed?
end

at_exit do
  exit 1 if Cucumber.wants_to_quit
end
```

which now gives us the exit codes we expect - however for some reason (unrelated) our jasmine:ci is now failing when we try to merge that fix:

https://travis-ci.org/AgileVentures/LocalSupport/builds/151151718

I just tried moving the jasmine:ci to before the other tests, but no joy - that jasmine:ci passes locally and also passes on the branch that I am issuing the PR from, but not on the PR itself - I tried completing the merge locally and jasmine:ci is also fine locally.  Here's the passing feature branch:

https://travis-ci.org/AgileVentures/LocalSupport/builds/151091994

and here's this weird new jasmine error we get:

```
4.13s$ USE_JASMINE_RAKE=true bundle exec rake jasmine:ci
[2016-08-10 08:42:37] INFO  WEBrick 1.3.1
rake aborted!
Errno::EINVAL: Invalid argument - connect(2) for "localhost" port 50603
[2016-08-10 08:42:37] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/base.rb:25:in `initialize'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/base.rb:25:in `open'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/base.rb:25:in `server_is_listening_on'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/base.rb:35:in `wait_for_listener'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/jasmine-2.1.0/lib/jasmine/tasks/jasmine.rake:65:in `block (2 levels) in <top (required)>'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/airbrake-5.2.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
/home/travis/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
/home/travis/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => jasmine:ci
(See full trace by running task with --trace)
```

any ideas?

**Comment by BanzaiMan** [comment]
The latest connexion issue is likely due to the change in our images. Try disabling IPv6

```yaml
before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped
```

or connecting to a numeric IPv4 address, say 127.0.0.1.
