### ISSUE TITLE
Running node on v5.x.x and v6.x.x produces Error: spawn EACCES

### ISSUE THREAD

**Issue by vcernomschi** [travis-ci/travis-ci#6173]
Running node on v5.x.x and v6.x.x produces Error: spawn EACCES

Prerequisites:
  Use node v6.2 or v 5.x

Steps to reproduce:
  1. Use: `sudo: required` in .travis.yml.
  2. Install deepify `npm install deepify`
  3. Run `deepify server ./path/to/source`.
      Expected result: server is up and running.
      Actual result: command fails with Error: spawn EACCES

Please refer to the full stackTrace:
```
19:31:00 GMT+0000 (UTC)  spawn EACCES 
19:31:00 GMT+0000 (UTC)  Error: spawn EACCES
    at exports._errnoException (util.js:1007:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:383:9)
    at b.exports.Exec._createClass.value (/home/travis/.nvm/versions/node/v6.2.1/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:1:1939)
    at b.exports.Exec._createClass.value (/home/travis/.nvm/versions/node/v6.2.1/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:1:1696)
    at a.module.exports [as _action] (/home/travis/.nvm/versions/node/v6.2.1/lib/node_modules/deepify/bin/commands/server.js:66:19)
    at a.exports.Program._createClass.value (/home/travis/.nvm/versions/node/v6.2.1/lib/node_modules/deepify/lib.compiled/Terminal/Program.js:1:4690)
    at a.exports.Program._createClass.value (/home/travis/.nvm/versions/node/v6.2.1/lib/node_modules/deepify/lib.compiled/Terminal/Program.js:1:4316)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v6.2.1/lib/node_modules/deepify/bin/deepify.js:85:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3 
```

Need to take into account that it works fine on node v4.3 in Travis and locally on  v6 and v5.
The full log is located: https://travis-ci.org/MitocGroup/deep-microservices-todo-app/jobs/137606117

**Comment by BanzaiMan** [comment]
What directory is it trying to access? Is it read or read/write?

**Comment by BanzaiMan** [comment]
Recent builds in https://github.com/MitocGroup/deep-microservices-todomvc/ are passing.

I'm closing this, as I do not think there is anything on our side to do.

**Comment by AScripnic** [comment]
@BanzaiMan Hello, I'm getting the same issue for the same repository for the same steps and for node 7.1/7.2 .
I'm making following action on files from project using `node`:
- check if file exists using `fs.existsSync` method
- delete file if exists using `fs.unlinkSync` method
- create new file using `fs. writeFileSync` method

I'm doing this actions for more then 1 file, but one of this files is: 
`${projectPath}/src/deep-todomvc/backend/src/task/create/_config.json` - I'm doing all 3 actions for every file (excepts 2nd action that executes only in case 1st action is true)

**Comment by BanzaiMan** [comment]
@AScripnic I'm sorry, but I do not understand what you are asking. Is there a build problem that you believe we should fix? Is it related to this issue? If so, could you point to a build log URL that shows the problem?

**Comment by AScripnic** [comment]
@BanzaiMan Yes, of course: https://travis-ci.org/MitocGroup/deep-microservices-todomvc/jobs/182719822 . I'm getting the same error:  `Error: spawn EACCES`
