### ISSUE TITLE
travis-build appears to be botching envvar decoding 

### ISSUE THREAD

**Issue by StoneCypher** [travis-ci/travis-ci#6174]
Sorry, I'm pretty sure this belongs in travis-build, but you have issues turned off over there, and this was already closed in [travis-worker](https://github.com/travis-ci/worker/issues/180#issuecomment-226040818)

On allowing the ruby commandline to add encrypted envvars, the export step in decryption is:

1) apparently broken
2) logged wholesale

This means that the exports aren't set correctly, and that once they're fixed, your logs will contain the very same information that the entire purpose of this system is to keep out of logs

```
Setting environment variables from .travis.yml
$ export ABC_KEY={:secure=>
/home/travis/build.sh: eval: line 45: syntax error near unexpected token `newline'
/home/travis/build.sh: eval: line 45: `export ABC_KEY={:secure=>'
$ export 1a2b3c4d="} ABC_KEY={:secure=>"
```

Other than that I've replaced the real name of the environment variable with `ABC_KEY` and the real value of the key with `1a2b3c4d`, this is unedited.  Note that each (ruby hash?) is cut off after their (whatever ruby people call fat arrows.)

The censored key is the encrypted value, not the unencrypted value.

There are two such keys in my `.travis.yml`; only the first appears in the log.  However, using code, I've verified that neither are set in the environment.

Here is an NSA-certified `.travis.yml` for you:

https://gist.github.com/StoneCypher/a5e516889b95c324be5421e1f9a17ce3

The referenced `gulp` deploy steps work locally, but won't work in Travis land because they rely on the envvars for their AWS keys.

I am somewhat confused.  I believe this may be a Travis bug, but I'm open to the possibility that I screwed this up somehow.

![image](https://cloud.githubusercontent.com/assets/77482/16062416/e2ff017e-3247-11e6-9632-159e224afc89.png)

**Comment by StoneCypher** [comment]
actually it occurs to me that if you were using naive `"` splitting and counting out positions, and had one more quote mark than you expected, then this would be the result

**Comment by BanzaiMan** [comment]
Assuming that you want to set both `$THERMOSTAT_FE_AWS_ACCESS_KEY` and `$THERMOSTAT_FE_SECRET_AWS_ACCESS_KEY`, you need to define `env.global` in a sequence, not a map (which is what you have in `.travis.yml` you've shown0. See https://docs.travis-ci.com/user/environment-variables/#Global-Variables

```yaml
env:
  global:
    - THERMOSTAT_FE_AWS_ACCESS_KEY:
      secure: (redacted)
    - THERMOSTAT_FE_SECRET_AWS_ACCESS_KEY:
      secure: (redacted)
```

and it'll work.

**Comment by StoneCypher** [comment]
Thank you for the repair recommendation.  I believe there is progress, though I'm actually set backwards.

Prior to this change, these values were defined, albeit incorrectly.  Post this change, the values are not defined at all.  I have emailed you in our existing thread a link to my build; you can see on line 807 that I have dumped the environment variable keys, and that the relevant two keys are not present.  (If you're searching your email in the future please search for 26886326 .)

I have updated the gist in case I used the presented structure incorrectly, as well as as a cheap platform to make cheaper jokes, but I believe I've followed your instructions.

------------

In the meantime, the config as originally shown was created by the ruby command line gem `travis` that you offer, by using your offered instructions to encrypt an environment variable [from here](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) (as well as a zillion other places.)  Possibly crucially, I did that twice - once for each variable.

That suggests that there remains a second bug: the command line gem is producing invalid configs.

Respectfully, please consider reopening this issue.  Thank you.  :smile_cat:

**Comment by BanzaiMan** [comment]
Oops. You are right, in that my suggestion was still wrong.

Could you try this?

```yaml
env:
  global:
    - secure: (redacted)
    - secure: (redacted)
```

Where `secure` values are what you get back from encrypting `VAR=SECRET`?

**Comment by StoneCypher** [comment]
Then how would it know the names of the envvars?

**Comment by StoneCypher** [comment]
... that appears to sort of work.  are the envvars' names stored with the encrypted versions?

anyway, it's extracting values now, but they're wrong.  when i print the first letters of the relevant keys at this end, they're two letters.  when i check at the far end, they're two equals signs.

predictably, the aws toolkit won't budge.

```
First letters of envvars: =, =
/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^
BadRequest: null
    at Request.extractError (/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/services/s3.js:504:35)
    at Request.callListeners (/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/home/travis/build/kinsahealth/thermostat_fe/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
Script failed with status 1
```

**Comment by StoneCypher** [comment]
oh, lol, i took a look at the first and last three characters instead of the first character, and it appears to be the correct credential with an equals sign stuck on the front

so now we're up to three bugs:

1. `secure` exports are decoded with a spurious symbol on the front
2. ruby gem doesn't handle multiple `secure`s correctly
3. documentation makes no mention of required notation

**Comment by StoneCypher** [comment]
sorry, rephrasing for clarity

if i encode the credential `ABC`, this system will decode it as `=ABC`

**Comment by StoneCypher** [comment]
Nevermind.  It's an artifact of how I registered them.  Your system is fine.

**Comment by StoneCypher** [comment]
Scratch #1.  It's an artifact of how I registered them.  The bug there is mine, not yours

#2 and #3 remain outstanding.

**Comment by BanzaiMan** [comment]
> ruby gem doesn't handle multiple secures correctly

What commands did you try? 

> documentation makes no mention of required notation

What "required notation" do you mean? There is a detailed discussion in https://docs.travis-ci.com/user/encryption-keys#Detailed-Discussion, which shows this example:

```yaml
env:
  - secure: "encrypted string"
```

The one I showed in https://github.com/travis-ci/travis-ci/issues/6174#issuecomment-226286482 is a variation of this.

**Comment by StoneCypher** [comment]
> > ruby gem doesn't handle multiple secures correctly

> What commands did you try?

Like I said earlier, [I did this twice](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) - once for each value.  The end result was the thing in the paste that you said was wrong.

> What "required notation" do you mean?

The second one you gave me.  

> The one I showed ... is a variation of this.

Yeah, it's a variation that your users (and staff apparently) aren't able to intuit through; there is no non-variant example; it is the default case with credentials that you have at least two to encode.

If the tool, on following your instructions, does the wrong thing, then:

1) The instructions need a complete example of the right thing, not a variant, and
2) The tool needs to be repaired to do the right thing on its own

Thanks

**Comment by BanzaiMan** [comment]
Ah, you mean you ran

```sh-session
travis encrypt MY_SECRET_ENV=super_secret --add env.matrix
```

twice? This is a known (but either undocumented or well hidden) issue, indeed; `--add` overwrites existing data.

We'll look into documentation improvements. Thanks.

**Comment by StoneCypher** [comment]
Almost.  I ran that twice, but with different variables in each run.

It shouldn't overwrite, and didn't; instead, it added twice, creating something invalid in the process.

**Comment by StoneCypher** [comment]
So, more like

```
travis encrypt MY_SECRET_ENV=super_secret --add env.matrix
travis encrypt MY_SECRET_ENV=super_secret --add env.matrix

**Comment by BanzaiMan** [comment]
Those commands should resulting in something different from what you initially indicated.

```yaml
env:
  matrix1:
    secure: WjE+s5ACIZrLTcNXvTCWphiPC8c281MUIe2+ngl9G4pXGjldzILVFEBIzUfo7IYvbjRfD+wdi0v4sfsZ5Kj2jqlV75lHF4l7SyX8OSMrokVVPZDGZWQieRQ2MQdCd0BW/csMVqMvyGSddYwj9g36t4uUWoqoMUaAWltW0E6Qb1g=
  matrix2:
    secure: fr5K2/bgjNBMZnW0CABvEgUEygX3mcySW1MMVfHgImmNmXYKNYwO/QpdBdK7sQ2lBdwUMHQFrk7G+m+YY6zeIe5C6V3rvPV29HbPl7ewqyIH4Oq1NDoA5B3EW0j+OIi/1bVV9n9z1aQpTS3Av1+uiOxxiHGU/U38KJQIqzYPKp4=
```

**Comment by StoneCypher** [comment]
not using the jun20 version of the tool.

**Comment by BanzaiMan** [comment]
We haven't had a release since January 12, 2016. https://rubygems.org/gems/travis/versions

**Comment by nikhilo** [comment]
Bump!
Hit this today. @StoneCypher was this ever resolved for you?
I would really like not having to bury my env variable name in the encrypted string. But for making the whole thing work, I might just try that.

**Comment by StoneCypher** [comment]
No, it was not

**Comment by BanzaiMan** [comment]
@nikhilo You can use the Settings page to set the secrets if you want to leave the env var names visible to you. https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by SummerSun** [comment]
This is really annoying.  I just encrypt the key i want to use during deploy:

`travis encrypt api_key=123 --add env.api_key`
```yml
deploy:
  provider: script
  skip_cleanup: true
  script: blabala nuget push $api_key
env:
  api_key:
    secure: blablabla
```

then I want to use it with nuget push, didn't find any document on how to use it, $api_key or $env.api_key. And I tried both, and "$api_key", neither works. 

Really appreciate any help!

**Comment by TimDaub** [comment]
Ran into the same problem and ended up using https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings
