### ISSUE TITLE
Unknown Travis error during Maven install command

### ISSUE THREAD

**Issue by jplu** [travis-ci/travis-ci#6330]
Hello,

Since February/March I encounter the following error in my Travis builds:

```
13:58:58.558 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
Killed
Results :
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:49 min
[INFO] Finished at: 2016-07-18T13:59:20+00:00
[INFO] Final Memory: 74M/1030M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project stanfordNLPRESTAPI: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/travis/build/jplu/stanfordNLPRESTAPI && /usr/lib/jvm/java-8-oracle/jre/bin/java '-javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/jplu/stanfordNLPRESTAPI/target/coverage-reports/jacoco-ut.exec,includes=fr.eurecom.stanfordnlprestapi.*' -jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefirebooter4278188391595446143.jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire6686454170355355078tmp /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire_07734725997220383320tmp
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project stanfordNLPRESTAPI: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/travis/build/jplu/stanfordNLPRESTAPI && /usr/lib/jvm/java-8-oracle/jre/bin/java '-javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/jplu/stanfordNLPRESTAPI/target/coverage-reports/jacoco-ut.exec,includes=fr.eurecom.stanfordnlprestapi.*' -jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefirebooter4278188391595446143.jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire6686454170355355078tmp /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire_07734725997220383320tmp
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/travis/build/jplu/stanfordNLPRESTAPI && /usr/lib/jvm/java-8-oracle/jre/bin/java '-javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/jplu/stanfordNLPRESTAPI/target/coverage-reports/jacoco-ut.exec,includes=fr.eurecom.stanfordnlprestapi.*' -jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefirebooter4278188391595446143.jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire6686454170355355078tmp /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire_07734725997220383320tmp
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/travis/build/jplu/stanfordNLPRESTAPI && /usr/lib/jvm/java-8-oracle/jre/bin/java '-javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/jplu/stanfordNLPRESTAPI/target/coverage-reports/jacoco-ut.exec,includes=fr.eurecom.stanfordnlprestapi.*' -jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefirebooter4278188391595446143.jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire6686454170355355078tmp /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire_07734725997220383320tmp
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:590)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:460)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:229)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:201)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1026)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:862)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
The command "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Denforcer.skip=true -Dcheckstyle.skip=true -B -V -X -e" failed and exited with 1 during .
Your build has been stopped.
```

My ```.travis.yml``` file is located here https://github.com/jplu/stanfordNLPRESTAPI/blob/feature/fixTravis/.travis.yml

I thought at the beginning it was a Java memory error issue, so I modified the ```MAVEN_OPTS``` and ```JAVA_OPTS``` environment variables to give 2GB, but without any effects. Is-there a way to better see what is happening and why my build is killed?

Thanks for any help.

**Comment by BanzaiMan** [comment]
I, too, suspect that the process is running out of memory. Try using `sudo: required` to run the build on GCE, which gives you more memory.

**Comment by jplu** [comment]
Thanks!

Unfortunately, it still doesn't works :-(

I used ```sudo: required``` and increased the memory until 7GB and I still have the same issue:

```
20:35:27.308 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
Killed
Results :
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:44 min
[INFO] Finished at: 2016-07-18T20:35:45+00:00
[INFO] Final Memory: 85M/1796M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project stanfordNLPRESTAPI: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/travis/build/jplu/stanfordNLPRESTAPI && /usr/lib/jvm/java-8-oracle/jre/bin/java '-javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/jplu/stanfordNLPRESTAPI/target/coverage-reports/jacoco-ut.exec,includes=fr.eurecom.stanfordnlprestapi.*' -jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefirebooter4076978553824932295.jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire2455271564732307469tmp /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire_03727984141351499837tmp
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project stanfordNLPRESTAPI: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/travis/build/jplu/stanfordNLPRESTAPI && /usr/lib/jvm/java-8-oracle/jre/bin/java '-javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/jplu/stanfordNLPRESTAPI/target/coverage-reports/jacoco-ut.exec,includes=fr.eurecom.stanfordnlprestapi.*' -jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefirebooter4076978553824932295.jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire2455271564732307469tmp /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire_03727984141351499837tmp
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/travis/build/jplu/stanfordNLPRESTAPI && /usr/lib/jvm/java-8-oracle/jre/bin/java '-javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/jplu/stanfordNLPRESTAPI/target/coverage-reports/jacoco-ut.exec,includes=fr.eurecom.stanfordnlprestapi.*' -jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefirebooter4076978553824932295.jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire2455271564732307469tmp /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire_03727984141351499837tmp
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/travis/build/jplu/stanfordNLPRESTAPI && /usr/lib/jvm/java-8-oracle/jre/bin/java '-javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/travis/build/jplu/stanfordNLPRESTAPI/target/coverage-reports/jacoco-ut.exec,includes=fr.eurecom.stanfordnlprestapi.*' -jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefirebooter4076978553824932295.jar /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire2455271564732307469tmp /home/travis/build/jplu/stanfordNLPRESTAPI/target/surefire/surefire_03727984141351499837tmp
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:590)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:460)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:229)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:201)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1026)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:862)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
The command "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Denforcer.skip=true -B -V -e" failed and exited with 1 during .
Your build has been stopped.
```

How can we check with more details what is happening? Because on my computer I don't specify any memory extension to maven, so I start to doubt it is coming from a memory problem.

**Comment by BanzaiMan** [comment]
Quite possibly some configuration issues. Please email support@travis-ci.com; we'll set you up for a debug VM.

**Comment by jplu** [comment]
I just sent an email!

**Comment by jplu** [comment]
After a long run of debugging I still did not succeed to find out what is happening. And it is impossible to reproduce this behavior locally and I have
tested on exactly 17 different machine most with a different OS (Windows, OS X and Linux), with different version of Java and Maven, but every
time I succeed to compile it, and when I try on this VM, it crashs doesn’t matter the amount of memory I give…

Do you know if there is any scripts or commands initialized on the VM that can trigger the process?

**Comment by jplu** [comment]
After again a whole day of testing, it is just impossible to run my tests over Travis :-( And I don't know what to test more to figure out if it is a machine resource issue or something else.

**Comment by jplu** [comment]
I successfully fixed the issue thanks to the Travis support. The issue was that surefire were run without an "-Xmx" option.
