### ISSUE TITLE
ImportError: no module named py when running python script

### ISSUE THREAD

**Issue by deltaskelta** [travis-ci/travis-ci#6562]
I am getting this error and I cannot see why it is looking for a module when it should be looking for the python file as far as I can see. My script file contains this line...

```
script:
  - python manage.py migrate
```

And it gives this error in the output...

```
$ ./travis-build.sh
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/python/2.7.9/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named py
```

In this instance I tried running the commands in a shell script but that didn't work either. I have been searching the documentation and I cannot find anything. I have also found examples where other people were running scripts like this... https://gist.github.com/ndarville/3625246

**Comment by Monkeyboy2805** [comment]
You can't import files with a file extension

**Comment by deltaskelta** [comment]
right...but aren't these all shell commands? on the shell that should work, and all the other commands seem to be working like a bash command

**Comment by Monkeyboy2805** [comment]
@deltaskelta yes but it doesn't have any third party modules and you can't add file extensions. I learnt that the hard way😋

**Comment by deltaskelta** [comment]
right, but I was calling it as a python argv. Anyway I managed to get the thing to build properly, but I am not sure how I did it in the end. For anyone else who may stumble upon this. My script looks like this.
```
sudo: required

language: python
python:
  - "2.7"

# Database services needed by the project
services: postgresql

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  # Updating the packages and installing what I need for the build and test process
  - sudo apt-get update
  - sudo apt-get install vorbis-tools
  - sudo apt-get install sox libsox-fmt-mp3
  - sudo apt-get install wordnet
  - sudo apt-get install lame

script:
  - coverage run --source=blog,define,lang_api,main,study manage.py test blog define lang_api main study

after_success:
  - coveralls
```

**Comment by Monkeyboy2805** [comment]
sorted

**Comment by arycloud** [comment]
any solution?
