### ISSUE TITLE
EACCES: permission denied, scandir '/home/travis/build/blockai/cloud-cache/test/.minio/config/certs'

### ISSUE THREAD

**Issue by olalonde** [travis-ci/travis-ci#6583]
My travis build mysteriously started failing with the following error:

```
> cloud-cache@1.0.3 lint /home/travis/build/blockai/cloud-cache
> eslint src/ test/
EACCES: permission denied, scandir '/home/travis/build/blockai/cloud-cache/test/.minio/config/certs'
Error: EACCES: permission denied, scandir '/home/travis/build/blockai/cloud-cache/test/.minio/config/certs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at GlobSync._readdir (/home/travis/build/blockai/cloud-cache/node_modules/eslint/node_modules/glob/sync.js:276:41)
    at GlobSync._readdir (/home/travis/build/blockai/cloud-cache/node_modules/eslint/lib/util/glob.js:59:36)
    at GlobSync._readdirInGlobStar (/home/travis/build/blockai/cloud-cache/node_modules/eslint/node_modules/glob/sync.js:255:20)
    at GlobSync._readdir (/home/travis/build/blockai/cloud-cache/node_modules/eslint/node_modules/glob/sync.js:264:17)
    at GlobSync._readdir (/home/travis/build/blockai/cloud-cache/node_modules/eslint/lib/util/glob.js:59:36)
    at GlobSync._processReaddir (/home/travis/build/blockai/cloud-cache/node_modules/eslint/node_modules/glob/sync.js:136:22)
    at GlobSync._process (/home/travis/build/blockai/cloud-cache/node_modules/eslint/node_modules/glob/sync.js:131:10)
    at GlobSync._processGlobStar (/home/travis/build/blockai/cloud-cache/node_modules/eslint/node_modules/glob/sync.js:368:10)
```

The build was working correctly previously which is weird (this is the commit that broke the build: https://github.com/blockai/cloud-cache/compare/27462938a00f...2ad3bb095b67 - simple edit to `README.md`).

https://travis-ci.org/blockai/cloud-cache/jobs/158835118

**Comment by olalonde** [comment]
Ended up fixing it with a `.eslintignore` on `/test/.minio/**`. still not sure why i started getting that error suddenly though
