### ISSUE TITLE
Build fails when adding bugger as a dependency

### ISSUE THREAD

**Issue by delijah** [travis-ci/travis-ci#6757]
When i try to run a build on Travis CI, i always get an error as soon as i add [bugger 2.3.0](https://github.com/buggerjs/bugger) to my package.json.

I am using node v6.7 with npm v3.10.3 on a linux machine (default Travis CI environment for node js projects).

```
> v8-profiler@5.6.5 preinstall /home/travis/build/DND-IT/cms-frontend/node_modules/.staging/v8-profiler-a67146e1
> node -e 'process.exit(0)'
> bufferutil@1.2.1 install /home/travis/build/DND-IT/cms-frontend/node_modules/bufferutil
> node-gyp rebuild
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/travis/build/DND-IT/cms-frontend/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:0:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from ../src/bufferutil.cc:7:0:
/home/travis/.node-gyp/6.7.0/include/node/v8.h:345:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/6.7.0/include/node/v8.h:481:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/6.7.0/include/node/v8.h:882:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/6.7.0/include/node/v8.h:5431:35: error: ‘virtual v8::EmbedderHeapTracer::~EmbedderHeapTracer()’ declared virtual cannot be defaulted in the class body
In file included from ../../nan/nan.h:190:0,
                 from ../src/bufferutil.cc:16:
../../nan/nan_maybe_43_inl.h:13:1: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16:1: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:24:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:31:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:36:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:41:1: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:46:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:51:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:59:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:64:8: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:69:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:76:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:83:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:91:8: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:98:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:108:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:114:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:118:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:125:1: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:130:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:135:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:139:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:145:8: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:150:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:156:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:162:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:168:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:174:8: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:180:8: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:186:8: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:194:8: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:201:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:205:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:209:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:213:8: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:217:8: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:237:8: error: ‘MaybeLocal’ does not name a type
In file included from ../../nan/nan.h:195:0,
                 from ../src/bufferutil.cc:16:
../../nan/nan_converters.h:14:11: error: ‘MaybeLocal’ does not name a type
../../nan/nan_converters.h:16:56: error: ‘Maybe’ does not name a type
../../nan/nan_converters.h:26:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:27:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:28:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:29:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:30:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:31:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:32:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:42:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:43:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:44:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:45:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:46:1: error: ‘return_t’ does not name a type
In file included from ../../nan/nan_converters.h:59:0,
                 from ../../nan/nan.h:195,
                 from ../src/bufferutil.cc:16:
../../nan/nan_converters_43_inl.h:18:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Boolean>’ does not name a type
../../nan/nan_converters_43_inl.h:19:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Number>’ does not name a type
../../nan/nan_converters_43_inl.h:20:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::String>’ does not name a type
../../nan/nan_converters_43_inl.h:21:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Object>’ does not name a type
../../nan/nan_converters_43_inl.h:22:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Integer>’ does not name a type
../../nan/nan_converters_43_inl.h:23:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Uint32>’ does not name a type
../../nan/nan_converters_43_inl.h:24:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Int32>’ does not name a type
../../nan/nan_converters_43_inl.h:34:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<bool>’ does not name a type
../../nan/nan_converters_43_inl.h:35:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<double>’ does not name a type
../../nan/nan_converters_43_inl.h:36:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<long int>’ does not name a type
../../nan/nan_converters_43_inl.h:37:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<unsigned int>’ does not name a type
../../nan/nan_converters_43_inl.h:38:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<int>’ does not name a type
In file included from ../../nan/nan.h:196:0,
                 from ../src/bufferutil.cc:16:
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
../../nan/nan_new.h:21:32: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h:21:32: note: candidate is:
../../nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Local<v8::Value>)
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Int32]’:
../../nan/nan_new.h:28:30: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h:28:30: note: candidate is:
../../nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Local<v8::Value>)
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Uint32]’:
../../nan/nan_new.h:35:31: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h:35:31: note: candidate is:
../../nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Local<v8::Value>)
../../nan/nan_new.h: At global scope:
../../nan/nan_new.h:43:11: error: ‘MaybeLocal’ does not name a type
../../nan/nan_new.h:75:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:141:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:147:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:148:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:160:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:161:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:162:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:163:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:165:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:166:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:182:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:183:17: error: ‘return_t’ does not name a type
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:196,
                 from ../src/bufferutil.cc:16:
../../nan/nan_implementation_12_inl.h:61:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::Date>’ does not name a type
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:95:46: error: ‘NewInstance’ was not declared in this scope
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::FunctionTemplate>::return_t Nan::imp::Factory<v8::FunctionTemplate>::New(Nan::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>)’:
../../nan/nan_implementation_12_inl.h:123:48: error: ‘NewInstance’ was not declared in this scope
../../nan/nan_implementation_12_inl.h: At global scope:
../../nan/nan_implementation_12_inl.h:202:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::RegExp>’ does not name a type
../../nan/nan_implementation_12_inl.h:221:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::Script>’ does not name a type
../../nan/nan_implementation_12_inl.h:227:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::Script>’ does not name a type
../../nan/nan_implementation_12_inl.h:259:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:267:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:273:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:280:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:286:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:291:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:352:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::UnboundScript>’ does not name a type
../../nan/nan_implementation_12_inl.h:359:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::UnboundScript>’ does not name a type
In file included from ../../nan/nan.h:196:0,
                 from ../src/bufferutil.cc:16:
../../nan/nan_new.h:293:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:299:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:305:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:311:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:317:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:323:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:329:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:335:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::RegExp>’ does not name a type
In file included from ../src/bufferutil.cc:16:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::Error(const char*)’:
../../nan/nan.h:655:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowError(const char*)’:
../../nan/nan.h:655:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::RangeError(const char*)’:
../../nan/nan.h:656:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowRangeError(const char*)’:
../../nan/nan.h:656:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::ReferenceError(const char*)’:
../../nan/nan.h:657:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowReferenceError(const char*)’:
../../nan/nan.h:657:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::SyntaxError(const char*)’:
../../nan/nan.h:658:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowSyntaxError(const char*)’:
../../nan/nan.h:658:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::TypeError(const char*)’:
../../nan/nan.h:659:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowTypeError(const char*)’:
../../nan/nan.h:659:3: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: At global scope:
../../nan/nan.h:667:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h:689:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h:705:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h:718:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h:735:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h:741:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h:749:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h:756:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h:762:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1507:41: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../../nan/nan.h:1525:45: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In member function ‘virtual void Nan::AsyncWorker::HandleErrorCallback()’:
../../nan/nan.h:1559:58: error: no matching function for call to ‘New(const char*)’
../../nan/nan.h:1559:58: note: candidates are:
../../nan/nan_implementation_12_inl.h:395:21: note: template<class T, class M> v8::Local<T> Nan::New(const v8::Persistent<S, M>&)
../../nan/nan_implementation_12_inl.h:400:21: note: template<class T, class M> v8::Local<T> Nan::New(const Nan::Persistent<T, M>&)
../../nan/nan_implementation_12_inl.h:405:21: note: template<class T> v8::Local<T> Nan::New(const Nan::Global<T>&)
../../nan/nan_new.h:201:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New()
../../nan/nan_new.h:207:1: note: template<class T, class A0> typename Nan::imp::Factory<T>::return_t Nan::New(A0)
../../nan/nan_new.h:213:1: note: template<class T, class A0, class A1> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1)
../../nan/nan_new.h:219:1: note: template<class T, class A0, class A1, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2)
../../nan/nan_new.h:225:1: note: template<class T, class A0, class A1, class A2, class A3> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2, A3)
../../nan/nan_new.h:237:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>)
../../nan/nan_new.h:245:1: note: template<class T, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>, A2)
../../nan/nan.h: In function ‘void Nan::imp::SetMethodAux(T, v8::Local<v8::String>, v8::Local<v8::FunctionTemplate>, ...)’:
../../nan/nan.h:1870:34: error: there are no arguments to ‘GetFunction’ that depend on a template parameter, so a declaration of ‘GetFunction’ must be available [-fpermissive]
../../nan/nan.h:1870:34: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../../nan/nan.h: In function ‘void Nan::SetMethod(HandleType<T>, const char*, Nan::FunctionCallback)’:
../../nan/nan.h:1882:45: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::SetPrototypeMethod(v8::Local<v8::FunctionTemplate>, const char*, Nan::FunctionCallback)’:
../../nan/nan.h:1897:45: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:
../../nan/nan.h:1922:47: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../../nan/nan.h:1965:51: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘void Nan::SetNamedPropertyHandler(v8::Local<v8::ObjectTemplate>, Nan::PropertyGetterCallback, Nan::PropertySetterCallback, Nan::PropertyQueryCallback, Nan::PropertyDeleterCallback, Nan::PropertyEnumeratorCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2024:47: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘void Nan::SetIndexedPropertyHandler(v8::Local<v8::ObjectTemplate>, Nan::IndexGetterCallback, Nan::IndexSetterCallback, Nan::IndexQueryCallback, Nan::IndexDeleterCallback, Nan::IndexEnumeratorCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2094:47: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘void Nan::SetCallHandler(v8::Local<v8::FunctionTemplate>, Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2149:47: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘void Nan::SetCallAsFunctionHandler(v8::Local<v8::ObjectTemplate>, Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2171:47: error: ‘NewInstance’ was not declared in this scope
In file included from ../src/bufferutil.cc:16:0:
../../nan/nan.h: In function ‘void Nan::Export(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE, const char*, Nan::FunctionCallback)’:
../../nan/nan.h:2198:35: error: no matching function for call to ‘New(const char*&)’
../../nan/nan.h:2198:35: note: candidates are:
../../nan/nan_implementation_12_inl.h:395:21: note: template<class T, class M> v8::Local<T> Nan::New(const v8::Persistent<S, M>&)
../../nan/nan_implementation_12_inl.h:400:21: note: template<class T, class M> v8::Local<T> Nan::New(const Nan::Persistent<T, M>&)
../../nan/nan_implementation_12_inl.h:405:21: note: template<class T> v8::Local<T> Nan::New(const Nan::Global<T>&)
../../nan/nan_new.h:201:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New()
../../nan/nan_new.h:207:1: note: template<class T, class A0> typename Nan::imp::Factory<T>::return_t Nan::New(A0)
../../nan/nan_new.h:213:1: note: template<class T, class A0, class A1> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1)
../../nan/nan_new.h:219:1: note: template<class T, class A0, class A1, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2)
../../nan/nan_new.h:225:1: note: template<class T, class A0, class A1, class A2, class A3> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2, A3)
../../nan/nan_new.h:237:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>)
../../nan/nan_new.h:245:1: note: template<class T, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>, A2)
../../nan/nan.h:2199:47: error: ‘GetFunction’ was not declared in this scope
../../nan/nan.h:2199:65: error: ‘Set’ was not declared in this scope
../../nan/nan.h:2199:65: note: suggested alternative:
/home/travis/.node-gyp/6.7.0/include/node/v8.h:3087:17: note:   ‘v8::Set’
../../nan/nan.h: In constructor ‘Nan::Tap::Tap(v8::Local<v8::Value>)’:
../../nan/nan.h:2206:30: error: no matching function for call to ‘To(v8::Local<v8::Value>&)’
../../nan/nan.h:2206:30: note: candidate is:
../../nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Local<v8::Value>)
../../nan/nan.h: In member function ‘void Nan::Tap::ok(bool, const char*)’:
../../nan/nan.h:2219:33: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In member function ‘void Nan::Tap::pass(const char*)’:
../../nan/nan.h:2225:30: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t’ has no member named ‘ToLocalChecked’
../../nan/nan.h: At global scope:
../../nan/nan.h:2249:10: error: ‘MaybeLocal’ does not name a type
../../nan/nan.h:2254:40: error: ‘MaybeLocal’ was not declared in this scope
../../nan/nan.h:2254:40: note: suggested alternative:
/home/travis/.node-gyp/6.7.0/include/node/v8.h:115:7: note:   ‘v8::MaybeLocal’
../../nan/nan.h:2254:52: error: template argument 1 is invalid
../../nan/nan.h:2254:54: error: expected unqualified-id before ‘>’ token
../../nan/nan.h:2263:1: error: ‘MaybeLocal’ does not name a type
../src/bufferutil.cc:25:30: error: ‘v8::Handle’ has not been declared
../src/bufferutil.cc:25:36: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/bufferutil.cc: In static member function ‘static void BufferUtil::Initialize(int)’:
../src/bufferutil.cc:33:5: error: ‘Set’ is not a member of ‘Nan’
../src/bufferutil.cc:33:5: note: suggested alternatives:
/home/travis/.node-gyp/6.7.0/include/node/v8.h:3087:17: note:   ‘v8::Set’
/home/travis/.node-gyp/6.7.0/include/node/v8.h:3087:17: note:   ‘v8::Set’
../src/bufferutil.cc:33:14: error: ‘target’ was not declared in this scope
../src/bufferutil.cc:33:51: error: no matching function for call to ‘New(const char [11])’
../src/bufferutil.cc:33:51: note: candidates are:
../../nan/nan_implementation_12_inl.h:395:21: note: template<class T, class M> v8::Local<T> Nan::New(const v8::Persistent<S, M>&)
../../nan/nan_implementation_12_inl.h:400:21: note: template<class T, class M> v8::Local<T> Nan::New(const Nan::Persistent<T, M>&)
../../nan/nan_implementation_12_inl.h:405:21: note: template<class T> v8::Local<T> Nan::New(const Nan::Global<T>&)
../../nan/nan_new.h:201:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New()
../../nan/nan_new.h:207:1: note: template<class T, class A0> typename Nan::imp::Factory<T>::return_t Nan::New(A0)
../../nan/nan_new.h:213:1: note: template<class T, class A0, class A1> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1)
../../nan/nan_new.h:219:1: note: template<class T, class A0, class A1, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2)
../../nan/nan_new.h:225:1: note: template<class T, class A0, class A1, class A2, class A3> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2, A3)
../../nan/nan_new.h:237:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>)
../../nan/nan_new.h:245:1: note: template<class T, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>, A2)
../src/bufferutil.cc: At global scope:
../src/bufferutil.cc:114:12: error: variable or field ‘init’ declared void
../src/bufferutil.cc:114:12: error: ‘Handle’ was not declared in this scope
../src/bufferutil.cc:114:25: error: expected primary-expression before ‘>’ token
../src/bufferutil.cc:114:27: error: ‘target’ was not declared in this scope
../src/bufferutil.cc:120:1: error: ‘init’ was not declared in this scope
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory `/home/travis/build/DND-IT/cms-frontend/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v6.7.0/bin/node" "/home/travis/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/DND-IT/cms-frontend/node_modules/bufferutil
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1
```

**Comment by BanzaiMan** [comment]
Have you added a C++11 compatible compiler? https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

**Comment by delijah** [comment]
Thank you for your quick response. I was sure i've already tried that and it didn't work. Anyways i've tried again and it works now. Thx a lot!
