### ISSUE TITLE
Caching fails with a `File exists` error

### ISSUE THREAD

**Issue by karalabe** [travis-ci/travis-ci#6889]
One of our builds are using 3 android platforms. I'm trying to cache them between builds so they aren't constantly retrieved, however the cache building step always fails with:

```
1.67s/Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': File exists @ dir_s_mkdir - /Users/travis/.android.platforms (Errno::EEXIST)
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/fileutils.rb:210:in `each'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
	from /Users/travis/.casher/bin/casher:118:in `block in push'
	from /Users/travis/.casher/bin/casher:118:in `map'
	from /Users/travis/.casher/bin/casher:118:in `push'
	from /Users/travis/.casher/bin/casher:52:in `block in run'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/timeout.rb:32:in `catch'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/timeout.rb:32:in `catch'
	from /Users/travis/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
	from /Users/travis/.casher/bin/casher:52:in `run'
	from /Users/travis/.casher/bin/casher:240:in `<main>'
```

Here's our travis.yml file that showcases this: https://github.com/karalabe/go-ethereum/blob/66703e220efad1d9b3d3e329c4d63c0d2cf4590a/.travis.yml#L62

Any ideas of what might be wrong?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by karalabe** [comment]
Sure https://travis-ci.org/ethereum/go-ethereum/jobs/176643374

**Comment by BanzaiMan** [comment]
Is this still an issue?
