### ISSUE TITLE
Failed to connect archive.apache.org (503) many times

### ISSUE THREAD

**Issue by 1ambda** [travis-ci/travis-ci#6950]
Hi all. 

While building project i got so many 503 from archive.apache.org. (even if retried 30 times)
But the weird thing is, it is possible to connect from local without errors. 

This is build result https://travis-ci.org/apache/zeppelin/builds/179756311 and you can see many failed builds due to 503 while trying to get files from archive.apache.org

Actually, these files were cached before, however cache miss occurred from some reason i cannot guess. (This doesn't matter anyway if we are able to download them)

- http://archive.apache.org/dist/spark/spark-1.4.1/spark-1.4.1-bin-without-hadoop.tgz
- http://archive.apache.org/dist/spark/spark-1.5.2/spark-1.5.2-bin-without-hadoop.tgz
- http://archive.apache.org/dist/spark/spark-1.6.1/spark-1.6.1-bin-without-hadoop.tgz
- http://archive.apache.org/dist/spark/spark-2.0.1/spark-2.0.1-bin-without-hadoop.tgz
- http://archive.apache.org/dist/spark/spark-2.0.1/spark-2.0.1.tgz

Is there a connection problem from travis CI to archive.apache.org?(https://issues.apache.org/jira/browse/INFRA-12996) 

Here is `.travis.yml` ([the entire file](https://github.com/1ambda/zeppelin/blob/8ae33a62badf5363c69300aa2efe5a3b8f88ea15/.travis.yml))

```
language: java

sudo: false

cache:
  apt: true
  directories:
    - .spark-dist
    - ${HOME}/.m2/repository/.cache/maven-download-plugin # cache directory for those files
```

```
[WARNING] Retrying (29 more)
...
...
[WARNING] Retrying (2 more)
[INFO] Read Timeout is set to 1800000 milliseconds (apprx 30 minutes)
[WARNING] Could not get content
org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://archive.apache.org/dist/spark/spark-1.6.1/spark-1.6.1-bin-without-hadoop.tgz. Return code is: 503 , ReasonPhrase:Service Unavailable.
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1039)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:977)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at com.googlecode.download.maven.plugin.internal.WGet.doGet(WGet.java:377)
	at com.googlecode.download.maven.plugin.internal.WGet.execute(WGet.java:282)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] Retrying (1 more)
```

Thanks!

**Comment by 1ambda** [comment]
Additionally, failed to access http://d3kbcqa49mib13.cloudfront.net/spark-1.6.1.tgz also. 

```
// https://travis-ci.org/1ambda/zeppelin/builds/179966656
// https://api.travis-ci.org/jobs/179966659/log.txt?deansi=true

[WARNING] Could not get content
org.apache.maven.wagon.TransferFailedException: GET request of: spark-1.6.1.tgz from http://d3kbcqa49mib13.cloudfaront.net failed
	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:363)
```

**Comment by 1ambda** [comment]
We also asked apache infra team [INFRA-12996]

**Comment by bzz** [comment]
@1ambda May be this is worth closing now, as the issue was due to unfortunate set of curcamstanses, not related to TravisCI:
 - http://archive.apache.org/dist was rate-limiting downloar with HTTP 503
 - then `download-maven-plugin` was failing with miss-leading error report inplying networkgin issue but actually, due to local-non-existing target path in FS

**Comment by 1ambda** [comment]
As @bzz summurized, this issue was resolved. I will close this issue. Thanks all!
