### ISSUE TITLE
Travis failing on geckodriver with Selenium 3

### ISSUE THREAD

**Issue by marcysutton** [travis-ci/travis-ci#7068]
Travis is having trouble running tests using Selenium 3, which require the latest geckodriver:
https://travis-ci.org/dequelabs/axe-webdriverjs/builds/185874513

```
  1) doc-dylang.html "before all" hook:
     Error: The geckodriver executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/WebDriver and ensure it can be found on your PATH.
    at Error (native)
    at findGeckoDriver (node_modules/selenium-webdriver/firefox/index.js:298:11)
    at ServiceBuilder (node_modules/selenium-webdriver/firefox/index.js:410:22)
    at createGeckoDriver (node_modules/selenium-webdriver/firefox/index.js:515:19)
    at Function.createSession (node_modules/selenium-webdriver/firefox/index.js:631:14)
    at createDriver (node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (node_modules/selenium-webdriver/index.js:642:16)
    at runWebdriver (test/run-webdriver.js:13:4)
    at Context.<anonymous> (test/integration/doc-dylang.js:25:12)
  
  2) doc-dylang.html "after all" hook:
     TypeError: Cannot read property 'quit' of undefined
    at Context.<anonymous> (test/integration/doc-dylang.js:33:9)
  
  3) doc-lang.html "before all" hook:
     Error: The geckodriver executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/WebDriver and ensure it can be found on your PATH.
    at Error (native)
    at findGeckoDriver (node_modules/selenium-webdriver/firefox/index.js:298:11)
    at ServiceBuilder (node_modules/selenium-webdriver/firefox/index.js:410:22)
    at createGeckoDriver (node_modules/selenium-webdriver/firefox/index.js:515:19)
    at Function.createSession (node_modules/selenium-webdriver/firefox/index.js:631:14)
    at createDriver (node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (node_modules/selenium-webdriver/index.js:642:16)
    at runWebdriver (test/run-webdriver.js:13:4)
    at Context.<anonymous> (test/integration/doc-lang.js:15:12)
  
  4) doc-lang.html "after all" hook:
     TypeError: Cannot read property 'quit' of undefined
    at Context.<anonymous> (test/integration/doc-lang.js:24:9)
  
  5) outer-frame.html "before all" hook:
     Error: The geckodriver executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/WebDriver and ensure it can be found on your PATH.
    at Error (native)
    at findGeckoDriver (node_modules/selenium-webdriver/firefox/index.js:298:11)
    at ServiceBuilder (node_modules/selenium-webdriver/firefox/index.js:410:22)
    at createGeckoDriver (node_modules/selenium-webdriver/firefox/index.js:515:19)
    at Function.createSession (node_modules/selenium-webdriver/firefox/index.js:631:14)
    at createDriver (node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (node_modules/selenium-webdriver/index.js:642:16)
    at runWebdriver (test/run-webdriver.js:13:4)
    at Context.<anonymous> (test/integration/frames.js:15:12)
  
  6) outer-frame.html "after all" hook:
     TypeError: Cannot read property 'quit' of undefined
    at Context.<anonymous> (test/integration/frames.js:26:9)
```

I even went through the steps of adding geckodriver to the PATH: 
```
language: node_js
node_js:
  - '6'
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - npm install selenium-webdriver@^3.0.0
  - npm install
script:
  - npm run test
```

I'd love to know if I missed something. Thanks!

**Comment by marcysutton** [comment]
I did miss something–the addon.

This almost works but I get timeout issues in my before all and after all hooks. I'm guessing that is unrelated, so I will close this issue.

```
language: node_js
node_js:
  - '6'
addons:
  firefox: "49.0.2"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - npm install selenium-webdriver@^3.0.0
  - npm install
script:
  - npm run test
```
