### ISSUE TITLE
python site.py raises a warning in Python >= 3.4

### ISSUE THREAD

**Issue by dvarrazzo** [travis-ci/travis-ci#7261]
this makes impossible to use `PYTHONWARNINGS=error` (e.g. to be stricter in the test suite): the interpreter fails to start.

```
Failed to import the site module
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site.py", line 703, in <module>
    main()
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site.py", line 165, in addpackage
    f = open(fullname, "rU")
DeprecationWarning: 'U' mode is deprecated
```

See https://travis-ci.org/psycopg/psycopg2/builds/197878865

Adding `-S` is not an option either (https://travis-ci.org/psycopg/psycopg2/builds/197880610)

**Comment by BanzaiMan** [comment]
Thanks for the report.

I looked at our archiving process, and thus far I have been unable to explain why this is happening. For example, [this](https://travis-ci.org/travis-ci/cpython-builder/jobs/153653582) is the build that packaged Python 3.5.2 for Precise. It uses [python-build](https://github.com/yyuu/pyenv/tree/master/plugins/python-build/share/python-build) to do the job. In the log, you see that it grabs https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz, installs it in `/opt/python/3.5.2` and creates a virtualenv which is later archived and uploaded.

I checked the 3.5.2 archive content, and it appears to have the right file. https://hg.python.org/cpython/file/v3.5.2/Lib/site.py#l158
