### ISSUE TITLE
Build logs not loading properly ("Error while loading data")

### ISSUE THREAD

**Issue by cgranade** [travis-ci/travis-ci#7278]
Similar to the previous issue #5273, when I try to view [any builds of QInfer/python-qinfer](https://travis-ci.org/QInfer/python-qinfer/branches), I get the message "There was an error while loading data, please try again" instead of the build log. If I manually click on Pull Request or Branches, then I can get somewhat further, with the metadata about each build showing up, but the loading indicator is never replaced with the actual build log. For example, if I navigate to [QInfer/python-qinfer build 429](https://travis-ci.org/QInfer/python-qinfer/builds/197541301) from the Pull Requests tab, I get the screenshot shown below.

![image](https://cloud.githubusercontent.com/assets/31516/22637926/0681839a-ec99-11e6-8d63-c785186781b7.png)

This behavior is consistent whether or not I'm logged in, from multiple computers on both Linux and Windows, and with multiple browsers (Chrome 55.0, Firefox 51.0.1 and Edge 38). Comparing the output on Chrome's developer console to a working build (ex: ), the following errors occur only for the broken build status:

```
raven.js:1112 GET https://api.travis-ci.org/builds/197541301 500 (Internal Server Error)

Error while processing route: build.index The adapter operation was aborted Error
    at r.i (https://cdn.travis-ci.org/assets/vendor-bd8e80d255873763d68928a1fa970462.js:34:18340)
    at r (https://cdn.travis-ci.org/assets/vendor-bd8e80d255873763d68928a1fa970462.js:34:18565)
    at l (https://cdn.travis-ci.org/assets/vendor-bd8e80d255873763d68928a1fa970462.js:34:21742)
    at i.c.error (https://cdn.travis-ci.org/assets/vendor-bd8e80d255873763d68928a1fa970462.js:34:25187)
    at l (https://cdn.travis-ci.org/assets/vendor-bd8e80d255873763d68928a1fa970462.js:4:13380)
    at Object.fireWith [as rejectWith] (https://cdn.travis-ci.org/assets/vendor-bd8e80d255873763d68928a1fa970462.js:4:14151)
    at n (https://cdn.travis-ci.org/assets/vendor-bd8e80d255873763d68928a1fa970462.js:5:18136)
    at XMLHttpRequest.<anonymous> (https://cdn.travis-ci.org/assets/vendor-bd8e80d255873763d68928a1fa970462.js:5:22946)
    at XMLHttpRequest.n (https://cdn.travis-ci.org/assets/vendor-bd8e80d255873763d68928a1fa970462.js:22:27546)

XMLHttpRequest cannot load https://api.travis-ci.org/builds/163289068. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://travis-ci.org' is therefore not allowed access. The response had HTTP status code 500.
```

The JSON payload for the affected API endpoint consists only of the following:

```
{error: "Travis encountered an error, sorry :("}
```

Thank you for the help!

**Comment by cgranade** [comment]
As a quick follow-up, I also get server errors when attempting to access build logs from the command line interface:

```
$ travis logs fix-qutip-doctest
server error (500: "{\"error\":\"Travis encountered an error, sorry :(\"}")
```

**Comment by BanzaiMan** [comment]
I've identified a bug in our API code. It is not immediately obvious to me how we got to this state; some decryption results in a `nil`. Does this repository have any defined in the Settings page?

**Comment by cgranade** [comment]
There's two encrypted environment variables (``PYPI_USERNAME`` and ``PYPI_PASSWORD``) for enabling PyPI upload integration, should I remove and re-enter them? Thanks for the help!

**Comment by RTLcoil** [comment]
Not working at all. Every time when I try to load log, i get server 500 error. Please fix.

**Comment by divtjurczak** [comment]
The same for me. 500 for https://api.travis-ci.org/jobs/206612138
