### ISSUE TITLE
mariaDB4j build issue

### ISSUE THREAD

**Issue by mhewedy** [travis-ci/travis-ci#7383]
I am using mariaDB4j to run in-memory mysql, although the build success on my machine, It success (with error1) on travis-ci.

```
[main] INFO ch.vorburger.exec.ManagedProcess - Successfully destroyed Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3307, --port=3307, --socket=/tmp/MariaDB4j.3307.sock] (in working directory /tmp/MariaDB4j/base)
[main] INFO ch.vorburger.mariadb4j.DB - Database stopped.
Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 16.377 sec <<< FAILURE!
MYSQL : create customer using the caller interface(spwrap.CallerIntTest)  Time elapsed: 0.28 sec  <<< ERROR!
spwrap.CallException: Table 'test.CUSTOMERS' doesn't exist
	at spwrap.Caller.call(Caller.java:276)
	at spwrap.Caller.call(Caller.java:159)
	at spwrap.CallerIntTest.#testDB : create customer using the caller interface(CallerIntTest.groovy:45)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'test.CUSTOMERS' doesn't exist
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.Util.getInstance(Util.java:360)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199)
	at com.mysql.jdbc.CallableStatement.execute(CallableStatement.java:870)
	at spwrap.db.GenericDatabase.executeCall(GenericDatabase.java:24)
	at spwrap.Caller.call(Caller.java:241)
	... 2 more

MYSQL : create customer using the caller interface and Persistable(spwrap.CallerIntTest)  Time elapsed: 0.041 sec  <<< ERROR!
spwrap.CallException: Table 'test.CUSTOMERS' doesn't exist
	at spwrap.Caller.call(Caller.java:276)
	at spwrap.Caller.call(Caller.java:159)
	at spwrap.CallerIntTest.#testDB : create customer using the caller interface and Persistable(CallerIntTest.groovy:63)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'test.CUSTOMERS' doesn't exist
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.Util.getInstance(Util.java:360)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199)
	at com.mysql.jdbc.CallableStatement.execute(CallableStatement.java:870)
	at spwrap.db.GenericDatabase.executeCall(GenericDatabase.java:24)
	at spwrap.Caller.call(Caller.java:241)
	... 2 more

```

Log file: https://api.travis-ci.org/jobs/205269271/log.txt?deansi=true 
project: https://github.com/mhewedy/spwrap

**Comment by mhewedy** [comment]
It is my issue, because I thought what is applicable to mac will be applicable to linux, however mysql (and hence maridadb) is case sensitive in linux (not MAC)
