### ISSUE TITLE
Deploy via Github using CodeDeploy 

### ISSUE THREAD

**Issue by waghanza** [travis-ci/travis-ci#7458]
Hi,
I am trying to deploy a simple `php` **app** on aws using `codedeploy` and **github** strategy.

On my aws consolde, I have create a user (to have credentials) with **AWSCodeDeployRole** policy.

Here is my `deploy` section :

~~~yaml
deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    application: BlueGreenDemoApplication
    deployment_group_name: DeploymentRole
    on:
      branch: master
~~~

But I have problem using it => https://travis-ci.org/waghanza/ideal-giggle/builds/210624213, on deployment I have :

~~~
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.50/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Applications not found for 740940901382 (Aws::CodeDeploy::Errors::ApplicationDoesNotExistException)

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.50/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.50/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.50/lib/seahorse/client/plugins/response_target.rb:21:in `call'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.50/lib/seahorse/client/request.rb:70:in `send_request'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.6.50/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider/code_deploy.rb:64:in `push_app'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider.rb:146:in `block in deploy'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/cli.rb:41:in `fold'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider.rb:146:in `deploy'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/cli.rb:32:in `run'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/cli.rb:7:in `run'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/bin/dpl:5:in `<top (required)>'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'

	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'

failed to deploy
~~~

Has anybody succeed deploying via github ?

**Comment by waghanza** [comment]
@BanzaiMan it was a region pb
