### ISSUE TITLE
SonarQube: /home/travis/.gitconfig (Permission denied)

### ISSUE THREAD

**Issue by LebedevRI** [travis-ci/travis-ci#7546]
Hello. With following `.travis.yml`:
```
language: cpp

os:
  - linux

dist: trusty # *sigh*
group: unstable
sudo: required

git:
  depth: 9999999

services:
  - docker

before_install:
  - if [[ "$EXTRA" == "NODOCKER" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -q;
      sudo apt-get upgrade -q cmake g++-4.8 g++-6 git libjpeg-dev libpugixml-dev libxml2-utils make ninja-build zlib1g-dev;
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull darktable/rawspeed;
      if [[ "$FLAVOR" == "Coverage" ]]; then
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
        sudo apt-get update -q;
        sudo apt-get upgrade -q g++-6;
      fi;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew tap Homebrew/bundle && cd .ci && brew bundle --verbose; fi

env:
  global:
    - SRC_DIR=/build/rawspeed
    - BUILD_DIR=/build/rawspeed-build
    - INSTALL_PREFIX=/build/rawspeed-install
    - CFLAGS="-pipe" CXXFLAGS="-pipe"
    - TARGET=build
  matrix:
    - CC=cc CXX=c++

matrix:
  fast_finish: true
  include:
  - os: linux
    env: CC=gcc-6 CXX=g++-6 EXTRA=NODOCKER SONARQUBE=ON
    addons:
      sonarqube:
        organization: "darktable-org"
        branches:
          - develop
          - sonarqube
    cache:
      directories:
        - '$HOME/.sonar/cache'

script:
  - if [[ "$EXTRA" == "NODOCKER" ]]; then
      export SRC_DIR="$TRAVIS_BUILD_DIR";
      export BUILD_DIR="$SRC_DIR/build";
      export INSTALL_PREFIX="$SRC_DIR/install";
      export ECO="$ECO -DALLOW_DOWNLOADING_GOOGLETEST=ON";
      mkdir "$BUILD_DIR";
      mkdir "$INSTALL_PREFIX";
      if [[ "$SONARQUBE" == "ON" ]]; then
        build-wrapper-linux-x86-64 --out-dir "$SRC_DIR/bw-output/" "$SRC_DIR/.ci/ci-script.sh";
        cd "$SRC_DIR";
        sonar-scanner -X;
      else
        "$SRC_DIR/.ci/ci-script.sh";
      fi;
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mkdir "$TRAVIS_BUILD_DIR/build";
      docker run --read-only --tmpfs /tmp --volume $TRAVIS_BUILD_DIR:$SRC_DIR:ro --volume "$TRAVIS_BUILD_DIR/build":$BUILD_DIR --workdir $BUILD_DIR --tmpfs $INSTALL_PREFIX $EXTRA_TMPFS --env CC --env CXX --env CFLAGS --env CXXFLAGS --env SRC_DIR --env BUILD_DIR --env INSTALL_PREFIX --env TARGET --env FLAVOR --env ECO darktable/rawspeed sh -c "$SRC_DIR/.ci/ci-script.sh";
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export SRC_DIR="$TRAVIS_BUILD_DIR";
      export BUILD_DIR="$SRC_DIR/build";
      export INSTALL_PREFIX="$SRC_DIR/install";
      export ECO="$ECO -DALLOW_DOWNLOADING_GOOGLETEST=ON";
      mkdir "$BUILD_DIR";
      mkdir "$INSTALL_PREFIX";
      "$SRC_DIR/.ci/ci-script.sh";
    fi
```

I get:
```
13:14:28.191 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to open Git repository
	at org.sonarsource.scm.git.JGitBlameCommand.buildRepository(JGitBlameCommand.java:104)
	at org.sonarsource.scm.git.JGitBlameCommand.blame(JGitBlameCommand.java:57)
	at org.sonar.scanner.scm.ScmPublisher.publish(ScmPublisher.java:82)
	at org.sonar.scanner.phases.PublishPhaseExecutor.afterSensors(PublishPhaseExecutor.java:58)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:76)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.io.FileNotFoundException: /home/travis/.gitconfig (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.eclipse.jgit.util.IO.readFully(IO.java:141)
	at org.eclipse.jgit.util.IO.readFully(IO.java:81)
	at org.eclipse.jgit.storage.file.FileBasedConfig.load(FileBasedConfig.java:144)
	at org.eclipse.jgit.internal.storage.file.FileRepository.loadUserConfig(FileRepository.java:252)
	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:196)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:580)
	at org.sonarsource.scm.git.JGitBlameCommand.buildRepository(JGitBlameCommand.java:99)
	... 30 more
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by LebedevRI** [comment]
Yep. https://travis-ci.org/darktable-org/rawspeed/jobs/217160398#L2827
It appears i'm able to workaround it via `sudo chmod 0777 "$HOME/.gitconfig";`

**Comment by BanzaiMan** [comment]
A couple of things.

1. That file should exist, and
1. That file should be [owned by `travis:travis`](https://travis-ci.org/BanzaiMan/travis_production_test/builds/217229275#L288)

@dmeneses Does SonarQube run as `travis` user, or something else?
