### ISSUE TITLE
Google Cloud Datastore DatastoreException 

### ISSUE THREAD

**Issue by jens-meiss** [travis-ci/travis-ci#7598]
Hi all,

i've problems getting Google Cloud Datastore working on the build system. I need the Datastore in the tests, it works locally but not on travis-ci. I tried both the Datastore Emulator and the Datastore provided by gcloud. I didn't found a solution on stackoverflow.

I also updated the gcloud installation, but i still end in the same error. Does anyone has the same problems? What can i do to fix the problem? 

Here's my travis config: 

* https://github.com/jens-meiss/blog/blob/master/.travis.yml

And here the log file with the error at the end

* https://s3.amazonaws.com/archive.travis-ci.org/jobs/220254212/log.txt

Datastore startup:

```
Executing: /home/travis/google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator start --host=localhost --port=8410 --store_on_disk=False --consistency=0.9 --allow_remote_shutdown /home/travis/google-cloud-sdk/data
[datastore] Apr 09, 2017 12:57:38 PM com.google.cloud.datastore.emulator.CloudDatastore$FakeDatastoreAction$7 apply
[datastore] INFO: Provided --allow_remote_shutdown to start command which is no longer necessary.
[datastore] Apr 09, 2017 12:57:38 PM com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub <init>
[datastore] INFO: Local Datastore initialized:
[datastore] 	Type: High Replication
[datastore] 	Storage: In-memory
[datastore] Apr 09, 2017 12:57:38 PM io.grpc.internal.ManagedChannelImpl <init>
[datastore] INFO: [ManagedChannelImpl@192d3247] Created with target localhost:8410
[datastore] Apr 09, 2017 12:57:39 PM io.gapi.emulators.netty.NettyUtil applyJava7LongHostnameWorkaround
[datastore] INFO: Applied Java 7 long hostname workaround.
[INFO] Scanning for projects...
[datastore] API endpoint: http://localhost:8410
[datastore] If you are using a library that supports the DATASTORE_EMULATOR_HOST environment variable, run:
[datastore] 
[datastore]   export DATASTORE_EMULATOR_HOST=localhost:8410
[datastore] 
[datastore] Dev App Server is now running.
[datastore]
```

It looks like the datastore is running, but in the tests i got this exception:

```
com.google.cloud.datastore.DatastoreException: I/O error
	at com.google.auth.oauth2.ComputeEngineCredentials.refreshAccessToken(ComputeEngineCredentials.java:111)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:149)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:135)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
	at com.google.cloud.HttpServiceOptions$1.initialize(HttpServiceOptions.java:224)
	at com.google.cloud.datastore.DatastoreOptions$1.initialize(DatastoreOptions.java:110)
	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:85)
	at com.google.datastore.v1.client.Datastore.commit(Datastore.java:84)
	at com.google.cloud.datastore.spi.DefaultDatastoreRpc.commit(DefaultDatastoreRpc.java:135)
	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:390)
	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:387)
	at com.google.cloud.RetryHelper.doRetry(RetryHelper.java:179)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:244)
	at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:386)
	at com.google.cloud.datastore.DatastoreImpl.commitMutation(DatastoreImpl.java:380)
	at com.google.cloud.datastore.DatastoreImpl.put(DatastoreImpl.java:340)
	at com.google.cloud.datastore.DatastoreHelper.put(DatastoreHelper.java:55)
	at com.google.cloud.datastore.DatastoreImpl.put(DatastoreImpl.java:315)
	at com.github.jens_meiss.blog.persistence.repository.gcloud.datastore.UserRepositoryImpl.add(UserRepositoryImpl.java:115)
	at com.github.jens_meiss.blog.persistence.repository.gcloud.datastore.UserRepositoryImpl$$FastClassBySpringCGLIB$$f5952645.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.github.jens_meiss.blog.persistence.repository.gcloud.datastore.UserRepositoryImpl$$EnhancerBySpringCGLIB$$2e899f73.add(<generated>)
	at com.github.jens_meiss.blog.persistence.repository.gcloud.datastore.UserRepositoryImplITCase.save(UserRepositoryImplITCase.java:84)
```

**Comment by jens-meiss** [comment]
hi,

i sovled it by myselve. if i use the LocalDatastoreHelper as Datastore implementation the tests are working.

* https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/TESTING.md#testing-code-that-uses-datastore

thx :)
