### ISSUE TITLE
CloudFiles deployment is broken

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#7674]
The error:

```
Installing deploy dependencies
Fetching: net-ssh-2.9.4.gem (100%)
Successfully installed net-ssh-2.9.4
1 gem installed
Fetching: mime-types-2.6.2.gem (100%)
Successfully installed mime-types-2.6.2
1 gem installed
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: nokogiri-1.6.8.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.8.1
2 gems installed
Fetching: ipaddress-0.8.3.gem (100%)
Successfully installed ipaddress-0.8.3
Fetching: xmlrpc-0.3.0.gem (100%)
ERROR:  Error installing fog-rackspace:
	xmlrpc requires Ruby version >= 2.3.

/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fog/rackspace (LoadError)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider.rb:77:in `requires'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider/cloud_files.rb:9:in `<class:CloudFiles>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider/cloud_files.rb:5:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider/cloud_files.rb:4:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider/cloud_files.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider.rb:59:in `const_get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider.rb:59:in `block in new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/provider.rb:56:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.31/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

I suspect the error came from `fog-core` 1.44.0 (https://github.com/fog/fog-core/issues/206).

**Comment by BanzaiMan** [comment]
To get around this problem (until we either update `dpl` to recognize this problem, or the `fog` team addresses the dependency issue), one can pre-install `fog-core` 1.43.0 in `before_install`:

```yaml
before_deploy:
  - rvm $(travis_internal_ruby) do gem install fog-core -v 1.43.0
```

**Comment by dtilchin** [comment]
Should be resolved: https://github.com/fog/fog-core/issues/206

**Comment by iriberri** [comment]
It seems to be working now, it's installing `fog-core-1.44.1`:

```
 gem install fog-core
Fetching: formatador-0.2.5.gem (100%)
Successfully installed formatador-0.2.5
Fetching: excon-0.55.0.gem (100%)
Successfully installed excon-0.55.0
Fetching: builder-3.2.3.gem (100%)
Successfully installed builder-3.2.3
Fetching: fog-core-1.44.1.gem (100%)
Successfully installed fog-core-1.44.1
4 gems installed
```
