### ISSUE TITLE
deploy failure: twine not found

### ISSUE THREAD

**Issue by steenzout** [travis-ci/travis-ci#7735]
job error example [here](https://travis-ci.org/Storj/storj-python-sdk/jobs/230454780) is a fresh new problem:

```
Collecting requests>=2.5.0 (from twine)
  Using cached requests-2.14.0-py2.py3-none-any.whl
  Exception:
  Traceback (most recent call last):
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/req/req_set.py", line 436, in prepare_files
      req_to_install.extras):
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2496, in requires
      dm = self._dep_map
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2697, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2730, in _compute_dependencies
      common = frozenset(reqs_for_extra(None))
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2727, in reqs_for_extra
      if req.marker_fn(override={'extra':extra}):
    File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/_vendor/_markerlib/markers.py", line 113, in marker_fn
      return eval(compiled_marker, environment)
    File "<environment marker>", line 1, in <module>
  NameError: name 'platform_system' is not defined
```

```
sh: 1: twine: not found
```

**Comment by steenzout** [comment]
discussion reference #6891

**Comment by steenzout** [comment]
from BanzaiMan
```
Right. pypi deployment requires sudo at the moment, and your build is running on a container, which does not allow use of it (https://travis-ci.org/Storj/storj-python-sdk/jobs/230454780#L295). This I think is a separate issue from this one, however; please open a new issue.
```

**Comment by steenzout** [comment]
job first error [here](https://travis-ci.org/Storj/storj-python-sdk/jobs/230454780#L295)

**Comment by BanzaiMan** [comment]
I've pushed an experimental fix to address this issue. Please try it with:

```yaml
deploy:
  provider: pypi
  edge:
    branch: twine-user-install
  ⋮ # rest
```

and report the results.

Thank you!

**Comment by jaraco** [comment]
Sadly, the [workaround seems not to work for me](https://travis-ci.org/jaraco/jaraco.mongodb/jobs/252014967).

**Comment by BanzaiMan** [comment]
Thanks for testing, and sorry to hear that it didn't work. I'll look into this in more detail soon.

**Comment by BanzaiMan** [comment]
I've brought the `twine-user-install` branch up to date (though I don't think there was significant change by doing this), and tested it again.

I _think_ https://travis-ci.org/BanzaiMan/travis_production_test/builds/252545641#L527 shows that `twine` was installed and available for deployment.

Has anyone else tested this?
