### ISSUE TITLE
SonarQube addon failing for authorization, but auth token is present

### ISSUE THREAD

**Issue by jlengstorf** [travis-ci/travis-ci#7814]
Hey, all!

I'm having a really frustrating time getting SonarQube set up, and I think it has something to do with the fact that I'm on enterprise versions of GitHub and Travis, plus a privately-hosted instance of SonarQube.

I've set both `SONAR_TOKEN` and `SONAR_GITHUB_TOKEN` (encrypted) in `.travis.yml`, but I keep getting errors like this:

```sh
$ sonar-scanner -X -D sonar.login=$SONAR_TOKEN
13:14:39.748 INFO: Scanner configuration file: /home/travis/.sonarscanner/sonar-scanner-2.8/conf/sonar-scanner.properties
13:14:39.758 INFO: Project root configuration file: /home/travis/build/Bluemix/account-usage-dashboard/sonar-project.properties
13:14:39.835 INFO: SonarQube Scanner 2.8
13:14:39.835 INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
13:14:39.836 INFO: Linux 4.4.0-62-generic amd64
13:14:40.215 DEBUG: keyStore is : 
13:14:40.215 DEBUG: keyStore type is : jks
13:14:40.216 DEBUG: keyStore provider is : 
13:14:40.216 DEBUG: init keystore
13:14:40.218 DEBUG: init keymanager of type SunX509
13:14:40.403 INFO: User cache: /home/travis/.sonar/cache
13:14:40.404 DEBUG: Create : /home/travis/.sonar/cache/_tmp
13:14:40.406 DEBUG: Extract sonar-scanner-api-batch in temp...
13:14:40.421 DEBUG: Get bootstrap index...
13:14:40.421 DEBUG: Download: https://sonarqube.com/batch_bootstrap/index
13:14:41.135 DEBUG: Get bootstrap completed
13:14:41.138 DEBUG: Download https://sonarqube.com/batch/sonar-scanner-engine-shaded-6.3.2.jar to /home/travis/.sonar/cache/_tmp/fileCache2013782077103200356.tmp
13:14:42.820 DEBUG: Create isolated classloader...
13:14:42.840 DEBUG: Start temp cleaning...
13:14:42.863 DEBUG: Temp cleaning done
13:14:42.863 DEBUG: Execution getVersion
13:14:42.867 DEBUG: Execution start
13:14:43.153 DEBUG: Issues global mode
13:14:43.272 INFO: Load global settings
13:14:43.511 DEBUG: GET 401 https://sonarqube.com/api/settings/values.protobuf | time=233ms
13:14:43.513 INFO: ------------------------------------------------------------------------
13:14:43.513 INFO: EXECUTION FAILURE
13:14:43.513 INFO: ------------------------------------------------------------------------
13:14:43.513 INFO: Total time: 3.823s
13:14:43.565 INFO: Final Memory: 8M/143M
13:14:43.565 INFO: ------------------------------------------------------------------------
13:14:43.566 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.bootstrap.ScannerPluginInstaller
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:70)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.instantiateComponentAsIsStartable(DefaultPicoContainer.java:1034)
	at org.picocontainer.DefaultPicoContainer.addAdapterIfStartable(DefaultPicoContainer.java:1026)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1003)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.batch.bootstrapper.Batch.start(Batch.java:101)
	at org.sonar.batch.bootstrapper.Batch.start(Batch.java:90)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.start(BatchIsolatedLauncher.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.start(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doStart(EmbeddedScanner.java:220)
	at org.sonarsource.scanner.api.EmbeddedScanner.start(EmbeddedScanner.java:156)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.home.cache.FileCache
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:70)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:68)
	... 29 more
Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.bootstrap.GlobalSettings
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:70)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.SingleMemberInjector.getMemberArguments(SingleMemberInjector.java:61)
	at org.picocontainer.injectors.MethodInjector.getMemberArguments(MethodInjector.java:100)
	at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:112)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120)
	at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58)
	at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142)
	at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:68)
	... 43 more
Caused by: Not authorized. Please check the properties sonar.login and sonar.password.
```

I've tried without setting the `sonar.login`. It does look like I'm getting a 401 from `https://sonarqube.com/api/settings/values.protobuf` — but that's the wrong host. How can I change this value? `sonar.host.url` doesn't appear to affect it. 😕

For reference, my `.travis.yml` looks like this:

```yaml
group: # ...

dist: trusty
sudo: required

language: node_js
node_js:
  - 6.9.0

jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: default

install:
  - npm i -g npm@3
  - npm install

script:
  - npm run lint
  - npm run build-prod
  - npm run test -- --coverage=80
  - sonar-scanner -X

cache:
  directories:
    - node_modules
    - '$HOME/.sonar/cache'

branches:
  only:
    - master

env:
  global:
    - secure: Yknz...Z9Ys=
    - secure: eDuX...ETQ=
    - secure: X4w2...rxo=
    - secure: P47k...UGY=

notifications:
  slack:
    rooms:
      - # ...
    on_success: never
    on_failure: always
```

Let me know if there's something else I can add for debugging. Thanks!

**Comment by jlengstorf** [comment]
Okay — looks like I opened this issue too soon.

For future enterprise Googlers, here’s what worked:

### 1. Define the following env variables:

- `SONAR_TOKEN` — your SonarQube token
- `SONAR_GITHUB_TOKEN` — a GitHub personal access token
- `SONAR_HOST_URL` — the URL of your SonarQube instance
- `GITHUB_API_URL` — your GitHub Enterprise API URL
  - You can make sure you have the right one in your browser. Head to `https://github.YOUR_COMPANY.com/api/v3/users/YOUR_USERNAME?access_token=SONAR_GITHUB_TOKEN`, then take everything before `/users...`.

### 2. Customize the `sonar-scanner` command

Several of the properties weren't honored from `sonar-project.properties`, so I had to declare them explicitly:

```
sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.github.endpoint=$GITHUB_API_URL -D sonar.github.oauth=$SONAR_GITHUB_TOKEN
```

This got it running for me.

**Comment by JuKu** [comment]
@jlengstorf Is there also an possibility to do this without Github Enterprise?

**Comment by jlengstorf** [comment]
@JuKu I haven't tried — I know there was an update to the plugin name, though, so maybe that's what you're running into? https://docs.travis-ci.com/user/sonarcloud/

**Comment by JuKu** [comment]
@jlengstorf Thanks for your answer!
I have resolved the problem. Here is my working configuration:
https://github.com/2D-MMORPG/client/blob/2822ec34fac81d7abb6df04877b3334289f38357/.travis.yml

**Comment by bellingard** [comment]
The tag `secure` works perfectly. We have sample repositories that we build every week to catch potential regressions - like https://github.com/SonarSource/sq-com_example_standard-sqscanner-travis, and those projects are analysed successfully.

My feeling is that you guys are not encrypting correctly your tokens. A common mistake is to encrypt more than the token because the Travis documentation gives the following example:

`travis encrypt MY_SECRET_ENV=super_secret`

As mentioned in the SonarCloud extension documentation, only the token must be encrypted, without "SONAR_TOKEN=":

`travis encrypt 309473973909Z09R830 -r my-org/my-repo`

**Comment by ron190** [comment]
That's exactly the case. I used the doc from Travis only to encrypt the token, I didn't even know there was a doc for the plugin so I tried anything like `travis encrypt TRAVIS_TOKEN="..."`, with quote, without quote, `travis encrypt sonar.login=`, etc.

It's now working.

**Comment by JuKu** [comment]
@ron190 Maybe, i to. :D
@jlengstorf I think the wrong documentation is the real problem of this issue.
Please add more example code directly in documentation! Or better:
Add a option to encrypt these values **online**.

**Comment by Bouke** [comment]
Can't get this to work. So far I've tried these, and variations:

```
travis encrypt 188...bc8 --add addons.sonarcloud.token
travis encrypt 188...bc8 -r Bouke/INI
```

When I add the token as an ENV variable, it works immediately.

**Comment by Bouke** [comment]
`travis encrypt [token]` is also not working for me. I've resorted to setting an ENV variable.

**Comment by JuKu** [comment]
Maybe "travis encrypt" is platform dependent?

**Comment by gavarava** [comment]
Using the below instead of the secure section works. So I set SONAR_TOKEN as an environment variable in Travis with the token value I got generated from my  Sonarcloud account.

**token: $SONAR_TOKEN**
