### ISSUE TITLE
Slack Notifications not working

### ISSUE THREAD

**Issue by ayyrickay** [travis-ci/travis-ci#7837]
My company recently switched some repositories from private to public, and in the process, we used `travis-ci.org` instead of `travis-ci.com`. Pretty much every part of the transition has gone smoothly, except for the integration for slack notifications. They were working when it was a private repository, but despite builds passing on travis, we don't get any notifications.

I've tried a few different strategies to try and fix this. For example, some command line prompts I've run include:

`travis encrypt "<ORG>:<KEY>#<SLACK-ROOM>" --add notifications.slack.room`
`travis encrypt "<ORG>:<KEY>#<SLACK-ROOM>" --add notifications.slack`
`travis encrypt "<ORG>:<KEY>" --add notifications.slack`
`travis encrypt "<ORG>:<KEY>" --add notifications.slack -r <ORG>/<REPO>`

I've run `travis sync`, and also changed the `on_success` parameter to  `always`. I've even tried running the encrypt command like so:

`travis encrypt "<ORG>:<KEY>#<SLACK-ROOM>" --add notifications.slack.room -e --org`

Which gets me the following error:

`/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/uri/generic.rb:1479:in `find_proxy': relative URI: --org (URI::BadURIError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/connection.rb:88:in `block in initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/options.rb:75:in `fetch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/connection.rb:83:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday.rb:67:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday.rb:67:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:60:in `uri='
	from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/methods.rb:30:in `api_endpoint='
	from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/cli/parser.rb:24:in `public_send'
	from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/cli/parser.rb:24:in `block in on'
	from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/cli/parser.rb:29:in `block (2 levels) in on'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1584:in `block in parse_in_order'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1538:in `catch'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1538:in `parse_in_order'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1532:in `order!'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1626:in `permute!'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1648:in `parse!'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1637:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/cli/command.rb:123:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/cli.rb:63:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:22:in `load'
	from /usr/local/bin/travis:22:in `<main>'`

I get the same error if I replace --org with --pro, or use the `api.travis` endpoints.

No matter what, notifications don't seem to be working, and at this point I'm trying to compare public keys to try and understand what's going on. Have I missed a part of the documentation that says Slack notifications for public repositories aren't supported? Am I misunderstanding the commands I should be using, or steps I should be taking to keep Travis happy as I move a repository from closed to open source? Or... Could this actually be a bug?

Any help is much appreciated. Thanks in advance!

**Comment by BanzaiMan** [comment]
Try dropping `-e` from your invocation. `--org` is a shortcut for `-e https://api.travis-ci.org`. I believe that `-e --org` is actually trying to use the string `--org` as the API endpoint; it is obviously not a usable URI, resulting in the error you are seeing.

**Comment by ayyrickay** [comment]
Yes! That worked!

As a follow-up question, I had tried setting the default endpoint to `--org`, but it looks like the CLI still defaults to using `.com` as the endpoint for encryption. Is this the expected behavior?

**Comment by BanzaiMan** [comment]
Check `~/.travis/config.yml` for the endpoints configured for each repo.

**Comment by BanzaiMan** [comment]
I checked with my own repos; it seems that the rep's `.git/config` has `[travis]` configurations.

**Comment by ayyrickay** [comment]
That's correct. But, in my repos, the only travis configs are a slug, which is the name of the repository. Do you see an endpoint in yours?

**Comment by BanzaiMan** [comment]
Oh, you're right about what's in that file. Not sure where the endpoint is inferred. :-/

Have you tried deleting `[travis]` in `.git/config`?

**Comment by ayyrickay** [comment]
I tried deleting a few days ago, and then added it back when the CLI showed the new prompt for adding the slug. It didn't solve the issue, but I wasn't very systematic about it - it just didn't seem like that small of a configuration problem was the issue.

I'm a little scared to test it out now because notifications are running properly now, but if it would be helpful for your team (especially if you're having problems reproducing this issue) I can see about setting up a new test case later today.
