### ISSUE TITLE
Travis build fails when gradle launches background java process

### ISSUE THREAD

**Issue by rahulsom** [travis-ci/travis-ci#7906]
It appears that when travis builds my project, it always fails in the exact same way. However, building locally or using shippable or codeship, the builds runs just fine.

My guess would be there's something different happening on travis. I can't pin point what the difference is.

----

Take a look at this PR (commit 03e883f)
GIthub page: https://github.com/rahulsom/grooves/pull/20

Travis/push page: https://travis-ci.org/rahulsom/grooves/builds/242295004
Travis/pr page: https://travis-ci.org/rahulsom/grooves/builds/242295010

The same commit builds fine on shippable and codeship.
![image](https://user-images.githubusercontent.com/193047/27113388-545b5c8a-5071-11e7-84e3-4298169431fa.png)

----

Is there any way to get travis's exact container image for this build and try running the build locally on it?

**Comment by BanzaiMan** [comment]
See https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally

**Comment by rahulsom** [comment]
Thanks @BanzaiMan 

I was able to get the container to run locally.

One thing that stood out was, travis uses `jdk_switcher`, and I had to install it manually.
This is what I did

```bash
docker run --name travis-debug -dit quay.io/travisci/travis-jvm /sbin/init
docker exec -it travis-debug bash -l
```
Wait till you're inside the docker container

```bash
su - travis

curl https://raw.githubusercontent.com/michaelklishin/jdk_switcher/master/jdk_switcher.sh > jdk_switcher.sh
. ./jdk_switcher.sh
jdk_switcher use oraclejdk8

git clone --depth=50 --branch=kotlin https://github.com/rahulsom/grooves.git
cd grooves
export JAVA_HOME=/usr/lib/jvm/java-8-oracle/
./gradlew assemble --scan --build-cache --configure-on-demand
./travis.sh
```

This worked just fine. I even reduced Docker for Mac to 2GB of memory. So I don't think it's resources related.

However, on travis the build still fails.

**Comment by BanzaiMan** [comment]
Do you know what these exceptions are? Are you running an HTTP server, and checking the responses? Is the server running (and responding to requests) when the tests run?

**Comment by rahulsom** [comment]
https://scans.gradle.com/s/jfso376y7trha/tests/nuzaumrfo6cam is gradle's build scan on it.

What's reported on https://travis-ci.org/rahulsom/grooves/builds/242295004#L850 as 

```
grooves.example.rxrest.PatientSpec > Patient List works FAILED
    groovyx.net.http.HttpResponseException
```

is presented in detail on the build scan as 
```
java.net.ConnectException: Connection refused: localhost/127.0.0.1:8081
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:338)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:561)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

My build at this point spins up 2 http servers - one is a stub and the other is the application under test.
The application under test is launched and being tested. However, it fails to connect to the stub to get the data it needs to serve valid responses during the test.

According to https://travis-ci.org/rahulsom/grooves/builds/242295004#L845, the stub is up and running (or at least it was at that moment.

**Comment by BanzaiMan** [comment]
Why is it refusing connexions?

By the way, I can reproduce this with the docker image. See https://gist.github.com/BanzaiMan/98f6ffefdf7c5015fa665458a9930e09.

**Comment by rahulsom** [comment]
It works on my machine. 
It also works here - https://hub.docker.com/r/rahulsom/grooves-build/builds/bwo6fbylne7waju9ctpzgys/
