### ISSUE TITLE
"No module named google_compute_engine" importing python boto 2 on new Trusty images

### ISSUE THREAD

**Issue by gdaolewe** [travis-ci/travis-ci#7940]
Minimal repo reproducing this here: https://github.com/gdaolewe/travis-boto-gce-issue

On sudo-enabled builds using the new Ubuntu Trusty images updated today (2017-6-21), with python 2.7.13 I cannot import python boto 2.32.0 or 2.47.0, with the following error:

```
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
    import boto
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/usr/lib/python2.7/dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
    from google_compute_engine import logger
ImportError: No module named google_compute_engine
```

If I use the `deprecated-2017Q2` group this works.

**Comment by alagopus** [comment]
Possibly related https://github.com/GoogleCloudPlatform/compute-image-packages/issues/262

**Comment by michael-younkin** [comment]
Yeah so this happens because of the `/etc/boto.cfg` file which (I believe) Google adds to their system images - the idea being that it loads some plugins that let you use boto more easily with Google Cloud services. This is mostly useless in a CI environment though. If you look at the config file, you'll see that it tries to load a Python plugin, which the travis people must have somehow corrupted in this image. It is unfortunate that they switched to a new image without testing widely used libraries like boto.

Anyway, you can fix the misconfiguration by adding `sudo rm -f /etc/boto.cfg` to the `before_install` section of your travis config. It just has to run before Python tries to import `boto`.

There is some saltiness in my reply, because this bug was very hard to figure out. That's partially because `boto` silently loads these global config files - I blame both travis and AWS for this!

**Comment by alagopus** [comment]
Yes @michael-younkin has the root of the problem. However, I would not recommend changing the container. Instead, include an empty or corrected `boto.cfg` with your virtual environment, and set `BOTO_CONFIG` to point at it. The system `/etc/boto.cfg` is not consistent with virtual environments, because the latter may not contain the dependencies that the former relies on.

**Comment by tbarbugli** [comment]
same issue here, the `sudo rm -f /etc/boto.cfg` trick is indeed a working patch

**Comment by BanzaiMan** [comment]
Hello. Could someone tell us how this file might come to be?

**Comment by alagopus** [comment]
Maybe you could get away with setting `export BOTO_CONFIG=/dev/null` at the start of your build.

**Comment by josegonzalez** [comment]
@alagopus can confirm that your suggestion works great!

**Comment by Raghuvar** [comment]
@mbyio Works also for me. `sudo rm -f /etc/boto.cfg`
Thanks

**Comment by jarshwah** [comment]
Bad bot!

**Comment by akx** [comment]
This also affects CircleCI, by the way.

**Comment by warrenrentlytics** [comment]
Is the `/dev/null` workaround reasonable for Circle CI, as well?

**Comment by mbyio** [comment]
If Circle CI is breaking for the same reason (they did not fully sanitize the images used for testing in Google Cloud VMs) then yeah it'll work there too.

**Comment by DrLuke** [comment]
This is still an issue.

**Comment by weallwegot** [comment]
for anyone running into this within a tox virtual env

```
# content of: tox.ini , put in same dir as setup.py
[tox]
envlist = py36

[testenv]
setenv = 
	BOTO_CONFIG = /dev/null
deps = 
	pytest
 	moto
commands =  pytest
```

**Comment by DrLuke** [comment]
This is still an issue !!!!

**Comment by DrLuke** [comment]
Please fix this already, it keeps breaking my CI when I start importing boto3 in a script. It's quite annoying.

**Comment by Jamim** [comment]
Hi @DrLuke,
You can try [this workaround](https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311326476).

**Comment by DrLuke** [comment]
HI @Jamim 

That's what I'm doing already, but that's really not a satisfying fix. It still breaks my CI every time I forget that I need to do this.

**Comment by BanzaiMan** [comment]
The PR above has been deployed. That file should be absent on the VMs moving forward.
