### ISSUE TITLE
Different "directories" to "cache" for different jobs

### ISSUE THREAD

**Issue by schuhschuh** [travis-ci/travis-ci#8092]
I have a Travis CI build for both Linux and macOS. Depending on OS, different dependencies need to be preinstalled in different locations. The caching of these dependencies thus requires the specification of different paths (directories). Alternatively, when a specified directory does not exist or can not be created due to permissions (see below), the caching of other directories should still proceed and maybe only produce a warning rather than an error. Best, however, when different `cache` options could be specified for different jobs (at least based on `os`).

The following is fine for the macOS build, but produces an error that prevents the caching of remaining folders:
```
adding /usr/local/Cellar to cache
creating directory /usr/local/Cellar
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - /usr/local/Cellar (Errno::EACCES)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:253:in `fu_mkdir'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:225:in `reverse_each'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:225:in `block in mkdir_p'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:210:in `each'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
	from /home/travis/.casher/bin/casher:87:in `block in add'
	from /home/travis/.casher/bin/casher:83:in `map'
	from /home/travis/.casher/bin/casher:83:in `add'
	from /home/travis/.casher/bin/casher:52:in `block in run'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/timeout.rb:32:in `catch'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/timeout.rb:32:in `catch'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
	from /home/travis/.casher/bin/casher:52:in `run'
	from /home/travis/.casher/bin/casher:240:in `<main>'
```
(https://travis-ci.org/BioMedIA/MIRTK/jobs/253603786)

Is it possible to specify a different set of paths for different jobs/OS's?

**Comment by BanzaiMan** [comment]
As we set environment variables before cache is pulled, you can do this:

```yaml
env:
  global:
    - CACHE_DIR=$([ $TRAVIS_OS_NAME = 'linux' ] && echo "FOO" || echo "BAR")

cache:
  directories:
    - $CACHE_DIR
```

In this example, the job will cache `FOO` on Linux and `BAR` on OS X.

This should probably be documented in https://docs.travis-ci.com/user/caching/

**Comment by schuhschuh** [comment]
Thanks, that would do.

Besides not having thought of using global environment variables, I wouldn't have dared to use a subshell `$(...)` in the `env` specification. Thought it needed to be more trivial expressions...
