### ISSUE TITLE
pip install -r requirement.txt failed (python 2.7)

### ISSUE THREAD

**Issue by calvin620707** [travis-ci/travis-ci#8105]
# Sympton
Travis fail to run `pip install -r requirements.txt`.
Our [requirement.txt](https://github.com/drmobile/dynamodb-titan/blob/master/requirements.txt) only include 2 python packages: `bulbs` and `boto`.
From the error log, it looks like pip on Travis downloaded and tried to install `distribute` then build fail. 

I had restart another Travis build [#35](https://travis-ci.org/drmobile/dynamodb-titan/builds/243550422) which already passed before. The new task, [#37](https://travis-ci.org/drmobile/dynamodb-titan/builds/243610270), which was restarted from #35 also failed. Therefore, I think it's possible Travis' environment issue.

# Failed build
[#37](https://travis-ci.org/drmobile/dynamodb-titan/builds/243610270)
[#40](https://travis-ci.org/drmobile/dynamodb-titan/builds/254723988)
# Error
```console
$ pip install -r requirements.txt
Collecting boto (from -r requirements.txt (line 1))
  Downloading boto-2.48.0-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 614kB/s 
Collecting bulbs (from -r requirements.txt (line 2))
  Downloading bulbs-0.3.29-20140417.tar.gz (71kB)
    100% |██████████���█████████████████████| 71kB 7.9MB/s 
Collecting distribute (from bulbs->-r requirements.txt (line 2))
  Downloading distribute-0.7.3.zip (145kB)
    100% |█████████���██████████████████████| 153kB 5.2MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/distribute.egg-info
    writing requirements to pip-egg-info/distribute.egg-info/requires.txt
    writing pip-egg-info/distribute.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/distribute.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/distribute.egg-info/dependency_links.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-OzEsdn/distribute/setup.py", line 58, in <module>
        setuptools.setup(**setup_params)
      File "/opt/python/2.7.13/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/python/2.7.13/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setuptools/command/egg_info.py", line 177, in run
        writer = ep.load(installer=installer)
      File "pkg_resources.py", line 2241, in load
        if require: self.require(env, installer)
      File "pkg_resources.py", line 2254, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "pkg_resources.py", line 2471, in requires
        dm = self._dep_map
      File "pkg_resources.py", line 2682, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "pkg_resources.py", line 2699, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named _markerlib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-OzEsdn/distribute/
The command "pip install -r requirements.txt" failed and exited with 1 during .
```

**Comment by calvin620707** [comment]
Fix the issue by `easy_install distribute`

Change from 
```yaml
before_script:
  - pip install -r requirements.txt
```
to
```yaml
before_script:
  - easy_install distribute
  - pip install -r requirements.txt
```
and the issue was fixed.
