### ISSUE TITLE
Missing sun.security classes on Oracle JDK8

### ISSUE THREAD

**Issue by dzieciou** [travis-ci/travis-ci#8145]
When running `mvn test` on both MacOs and Windows machines locally my tests are going fine. However, when I run them through Travis CI I keep getting errors

`java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext`

My Travis CI configuration:

    language: java
    jdk:
      - oraclejdk8

Full stacktrace:

    java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
    	at java.lang.Class.forName0(Native Method)
    	at java.lang.Class.forName(Class.java:264)
    	at java.security.Provider$Service.getImplClass(Provider.java:1634)
    	at java.security.Provider$Service.newInstance(Provider.java:1592)
    	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
    	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
    	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
    	at org.apache.http.conn.ssl.SSLContexts.createDefault(SSLContexts.java:57)
    	at org.apache.http.conn.ssl.SSLSocketFactory.getSocketFactory(SSLSocketFactory.java:168)
    	at org.apache.http.impl.conn.SchemeRegistryFactory.createDefault(SchemeRegistryFactory.java:52)
    	at org.apache.http.impl.client.AbstractHttpClient.createClientConnectionManager(AbstractHttpClient.java:321)
    	at org.apache.http.impl.client.AbstractHttpClient.getConnectionManager(AbstractHttpClient.java:486)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    	at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
    	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:64)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
    	at io.restassured.internal.RequestSpecificationImpl.applyProxySettings(RequestSpecificationImpl.groovy:2207)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
    	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
    	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
    	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
    	at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1230)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImme.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
    	at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:172)
    	at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
    	at com.github.dzieciou.testing.curl.UsingWithRestAssuredTest.shouldPrintMultipartWithMixedType(UsingWithRestAssuredTest.java:224)

**Comment by dzieciou** [comment]
It was enough to stop manipulating os.name system property in POM.
