### ISSUE TITLE
User limit of inotify watches reached

### ISSUE THREAD

**Issue by barreeeiroo** [travis-ci/travis-ci#8157]
I get this error testing my build:
```
YaClientApp:
     [java] Jul 25, 2017 11:32:32 AM java.util.prefs.FileSystemPreferences$1 run
     [java] INFO: Created user preferences directory.
     [java] The attempt to retrieve files in /home/travis/build/Makeroid/Makeroid/appinventor/appengine/src failed.
     [java] java.io.IOException: User limit of inotify watches reached
     [java] 	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
     [java] 	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
     [java] 	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] The attempt to retrieve files in /home/travis/build/Makeroid/Makeroid/appinventor/build/components/ComponentTranslation/src failed.
```

_.travis.yml_ file:
```
language: java

install: cd appinventor && ant

jdk:
  - openjdk8
```

**Comment by barreeeiroo** [comment]
Fixed using this _.travis.yml_ file:
```
language: java

install: cd appinventor && sudo ant

jdk:
  - openjdk8
```
