### ISSUE TITLE
Travis breaks when I add an empty class to my test folder

### ISSUE THREAD

**Issue by adam-arold** [travis-ci/travis-ci#8238]
This is the weirdest bug I've seen so far. If I add a class (any empty class) to my [Kotlin project](https://github.com/Hexworks/zircon) I get a wall of test failures when the `gradle check` is running the `:test` task:

> org.codetome.zircon.terminal.AbstractTerminalTest > shouldAddResizeListenerWhenAddIsCalled FAILED
>     java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.codetome.zircon.graphics.style.DefaultStyleSet.<init>, parameter foregroundColor
>         at org.codetome.zircon.graphics.style.DefaultStyleSet.<init>(DefaultStyleSet.kt)
>         at org.codetome.zircon.graphics.style.DefaultStyleSet.<init>(DefaultStyleSet.kt:12)
>         at org.codetome.zircon.terminal.AbstractTerminal.<init>(AbstractTerminal.kt:5)
>         at org.codetome.zircon.terminal.virtual.DefaultVirtualTerminal.<init>(DefaultVirtualTerminal.kt:21)
>         at org.codetome.zircon.terminal.virtual.DefaultVirtualTerminal.<init>(DefaultVirtualTerminal.kt:34)
>         at org.codetome.zircon.terminal.virtual.DefaultVirtualTerminal.<init>(DefaultVirtualTerminal.kt:33)
>         at org.codetome.zircon.terminal.AbstractTerminalTest.setUp(AbstractTerminalTest.kt:17)
> org.codetome.zircon.terminal.AbstractTerminalTest > shouldRemoveListenerWhenRemoveisCalled FAILED
>     java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.codetome.zircon.graphics.style.DefaultStyleSet.<init>, parameter foregroundColor
>         at org.codetome.zircon.graphics.style.DefaultStyleSet.<init>(DefaultStyleSet.kt)
>         at org.codetome.zircon.graphics.style.DefaultStyleSet.<init>(DefaultStyleSet.kt:12)
>         at org.codetome.zircon.terminal.AbstractTerminal.<init>(AbstractTerminal.kt:5)
>         at org.codetome.zircon.terminal.virtual.DefaultVirtualTerminal.<init>(DefaultVirtualTerminal.kt:21)
>         at org.codetome.zircon.terminal.virtual.DefaultVirtualTerminal.<init>(DefaultVirtualTerminal.kt:34)
>         at org.codetome.zircon.terminal.virtual.DefaultVirtualTerminal.<init>(DefaultVirtualTerminal.kt:33)
>         at org.codetome.zircon.terminal.AbstractTerminalTest.setUp(AbstractTerminalTest.kt:17)

This is completely unrelated and happens when I add **any** empty class to my project. I just tried it with this:

```
class Foo {
}
```

I have no idea what causes this. [This](https://github.com/Hexworks/zircon/commit/ffdc6421cdccafd3b701a9b4d5e57b47eb7a41c1) is my latest commit which broke the Travis build.

I tried to build the project on my Mac and it works fine so this must be a Travis issue.

**Comment by adam-arold** [comment]
Nevermind, I switched to CircleCI, it just works.
