### ISSUE TITLE
Environment Variables doesn't work with npm adduser

### ISSUE THREAD

**Issue by yozman** [travis-ci/travis-ci#8261]
I have a shell like this:
```shell
npm adduser --registry=https://registry.npmjs.org/ <<!
$NPM_USER
$NPM_PASS
$NPM_MAIL
!
```

when I turn on display value in build log it works.
when I turn off the option the build is fail

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by yozman** [comment]
```
npm ERR! cb() never called!
```

**Comment by BanzaiMan** [comment]
Please point to a build log URL.

**Comment by yozman** [comment]
https://api.travis-ci.org/jobs/265572741/log.txt?deansi=true

**Comment by BanzaiMan** [comment]
The error message is indicative of your `$NPM_TOKEN` being unset or empty.

```sh-session
travis@0fa7bbd7d084:~$ unset NPM_TOKEN
travis@0fa7bbd7d084:~$ npm adduser --registry=https://registry.npmjs.org/ <<!
blibee
$NPM_TOKEN
ye.rong@bianlifeng.com
!
Username: blibee
Password:
Password:
Email: (this IS public) npm ERR! cb() never called!
npm ERR! not ok code 0
```

If it *_is_* set, you get a different error message:

```sh-session
travis@0fa7bbd7d084:~$ NPM_TOKEN=foobar
travis@0fa7bbd7d084:~$ npm adduser --registry=https://registry.npmjs.org/ <<!
blibee
$NPM_TOKEN
ye.rong@bianlifeng.com
!
Username: blibee
Password:
Email: (this IS public) ye.rong@bianlifeng.com
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser
npm WARN adduser     https://npmjs.org/forgot
npm WARN adduser
npm ERR! Error: 401 Could not create user
npm ERR! {"ok":false,"id":"org.couchdb.user:undefined"}
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js:119:15)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js:74:18)
npm ERR!     at cb (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:57:9)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:137:16)
npm ERR!     at cb (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:166:9)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:320:12)
npm ERR!     at Request._callback (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.41-moby
npm ERR! command "/home/travis/.nvm/v0.10.36/bin/node" "/home/travis/.nvm/v0.10.36/bin/npm" "adduser" "--registry=https://registry.npmjs.org/"
npm ERR! cwd /home/travis
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/npm-debug.log
npm ERR! not ok code 0
```

**Comment by yozman** [comment]
@BanzaiMan 
I did like this
```shell
if [ $# == 0 ];then
  NPM_TOKEN=`cat NPM_TOKEN`
else
  NPM_TOKEN=$1
fi
```

when NPM_TOKEN isn't encrypt it's works,
when NPM_TOKEN is encrypt to NPM_TOKEN.enc and decrypt at before_install it doesn't work

**Comment by BanzaiMan** [comment]
It appears to me that that your decryption of `NPM_TOKEN.enc` is ends up with an empty (or nonexistent) `NPM_TOKEN`. Try re-encrypting the file.

**Comment by prmichaelsen** [comment]
Try
```sh
cat <<EOF
$npm_user
$npm_password
$email
EOF | npm adduser
```
or if using a token, do:
```sh
cat > ~/.npmrc <<EOF
//registry.npmjs.org/:_authToken=$npm_token
EOF
```
I'd recommend creating a token so you don't have to store your credentials anywhere on your CI/CD
