### ISSUE TITLE
Trusty 2017/Q3 updates encountered issues and their workarounds

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#8315]
Just a placeholder for now.

**Comment by peternewman** [comment]
The build environments update page lists clang as changing to be 3.9.0 ( https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/#Changed ), but on an edge build ( https://travis-ci.org/OpenLightingProject/ola/jobs/271392249#L8 ) it's still just listing 3.5.0:
https://travis-ci.org/OpenLightingProject/ola/jobs/271392249#L43

We're actually manually installing 5.0.0, from the clang repos, so it's mostly irrelevant, but I'm just curious why it doesn't seem to have updated?

**Comment by edmorley** [comment]
Someone from Travis CI will need to confirm this - but that job is a container job, and I believe they aren't able to use the `group` attribute. If you change to the fully virtualised GCE infrastructure (`sudo: required`) you should get the edge image. 

Perhaps it would be good to document the `group` attribute somewhere?

**Comment by peternewman** [comment]
Interesting thanks Ed. As mentioned, it reports, and changes the listed build group, so I'd hope it didn't do that if it wasn't going to change anything.

Some documentation on the default and available groups would certainly be good.

**Comment by synth** [comment]
I received `Command 'make ' failed`. Adding `group: deprecated-2017Q3` did not help. Also, we have `dist: precise` already in our travis.yml. :(

    current directory:
    /home/travis/build/Recognize/recognize/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.14.0
    /home/travis/.rvm/rubies/ruby-2.2.2/bin/ruby -r
    ./siteconf20170905-5943-1o74hch.rb extconf.rb
    cd src/ && /usr/bin/qmake
        /home/travis/build/Recognize/recognize/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.14.0/src/webkit_server.pro
    -o Makefile.webkit_server
    cd src/ && make -f Makefile.webkit_server 
    make[1]: Entering directory
    `/home/travis/build/Recognize/recognize/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.14.0/src'
    g++ -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB
    -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
    -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore
    -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui
    -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -Ibuild -x c++-header -c stable.h
    -o build/webkit_server.gch/c++
    stable.h:23:23: fatal error: QWebElement: No such file or directory
    compilation terminated.
    make[1]: *** [build/webkit_server.gch/c++] Error 1
    make[1]: Leaving directory
    `/home/travis/build/Recognize/recognize/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-    1.14.0/src'
    make: *** [sub-src-webkit_server-pro-make_default-ordered] Error 2
    Command 'make ' failed

**Comment by cotsog** [comment]
[The update will happen tomorrow](https://blog.travis-ci.com/2017-08-29-trusty-image-updates) i.e. Wednesday, September 6th, 2017. In the meantime, please remove the `group: ` directive from your .travis.yml file as it can have undesired side-effects.

@peternewman: can you send us an e-mail at support [at] travis-ci [dot] com with these details?

@synth: we will follow-up over the e-mail you've already sent us.

Thanks!

**Comment by MarcoFalke** [comment]
pyenv reports that python 3.6 is installed. Is this wanted?

Output:
```
$ pyenv versions
* system (set by /opt/pyenv/version)
  2.7
  2.7.13
  3.3
  3.3.6
  3.4
  3.4.6
  3.5
  3.5.3
  3.6
  3.6.1
  pypy2-5.6.0
```

I am using the following yaml:

```yaml
sudo: required
dist: trusty
os: linux
group: edge
language: generic
before_script:
    - pyenv versions

**Comment by edmorley** [comment]
@MarcoFalke the `language: generic` property used to map to the smallest `connie` image, but in travis-ci/packer-templates#454 was made to map to the largest `sugilite` image instead. From the date of that PR I think it would have already been in the last round of image updates (and so presumably this not be the cause for the surprise), but @meatballhat would have to confirm.

Anyway, for the sugilite image, Python 3.6.x is expected to be installed:
https://github.com/travis-ci/packer-templates/blob/f33ae65/cookbooks/travis_ci_sugilite/attributes/default.rb#L117-L124

**Comment by MarcoFalke** [comment]
Thanks for the reply. Though, I can't figure out how to call py3.6.

Doing those in the `before_script`:

```
0.06s$ /opt/pyenv/shims/python3.4 -c 'print("test")'
test
0.07s$ /opt/pyenv/shims/python3.6 -c 'print("test")'
pyenv: python3.6: command not found
The `python3.6' command exists in these Python versions:
  3.6
  3.6.1
The command "/opt/pyenv/shims/python3.6 -c 'print("test")'" failed and exited with 127 during .
Your build has been stopped.

**Comment by rhs** [comment]
I'm getting similar python version issues in my builds. This used to work before today:

```shell
pyenv: pip3: command not found
The `pip3' command exists in these Python versions:
  3.3
  3.3.6
  3.4
  3.4.6
  3.5
  3.5.3
  3.6
  3.6.1
```

**Comment by cotsog** [comment]
@MarcoFalke, @rhs: could you send us an e-mail to support [at] travis-ci [dot] com? Please include a description of your issue, the name of the repo where it's happening and links to builds on travis-ci.org or travis-ci.com showing the issue. Thanks!

**Comment by rsimha-amp** [comment]
@BanzaiMan, we're seeing a bunch of things breaking on the AMP Project due to the new images.

Errors: https://travis-ci.org/ampproject/amphtml/jobs/272980280
Tracking issue: https://github.com/ampproject/amphtml/issues/11203

I'm switching to the old image for now, while I try to fix these errors. Meanwhile, any input from you re: how to fix them is welcome.

**Comment by rsimha-amp** [comment]
@BanzaiMan, after switching to the old image, we're still seeing a bunch of errors due to missing plugins, even though `yarn.lock` is up to date and contains specifications for those plugins. See https://travis-ci.org/ampproject/amphtml/jobs/273011615. 

Right now, neither the old image, nor the new image is working, and this is now blocking all development work on our side. Could you please take a quick look at the link above, and let me know if you believe I'm missing something?

**Comment by BanzaiMan** [comment]
@rsimha-amp Could you try removing (or disabling) caching?

**Comment by rsimha-amp** [comment]
@BanzaiMan, thanks. Disabling caching did the trick.

**Comment by BanzaiMan** [comment]
@rsimha-amp Thanks for the report. Please remove existing caches. They are likely culprit in your build failures.

**Comment by MarcoFalke** [comment]
@cotsog See here for the minimal example that breaks: https://travis-ci.org/MarcoFalke/bitcoin/jobs/272286278/config

You can see that `pyenv versions` advertises py3.6, but the actual call fails.

**Comment by MarcoFalke** [comment]
@cotsog @cfields See here for the minimal example that breaks: https://travis-ci.org/MarcoFalke/bitcoin/jobs/272286278/config

You can see that `pyenv versions` advertises py3.6, but the actual call fails.

**Comment by Shilpi85** [comment]
We are running Parallel Cucumber selenium Test using the parallel_tests with 5 Process and with the new Image lots of tests are failing with time out issue. 
So for now we added the group: deprecated-2017Q3 and after that the tests are running fine.

**Comment by rsimha-amp** [comment]
@BanzaiMan, the missing plugin errors went away when I deleted the old caches. However, we're still seeing build errors related to the addition of `_JAVA_OPTIONS` in the new images.

See https://github.com/ampproject/amphtml/issues/11210

Any idea what's going on here?

**Comment by riquito** [comment]
We run into issues because there were new services running
- mysql
- memcached

We usually run these services ourselves using docker and the containers started to fail because the ports were already used (3306, 11211). We already had `group: deprecated-2017Q3` in our `.travis.yml`. Fixed by stopping MySQL and memcached services

```
before_install:
    - sudo service mysql stop
    - sudo service memcached stop
```

**Comment by csantanapr** [comment]
In Apache OpenWhisk we are having issues around `pip` installing `setuptools`
Our `.travis.yml` has something like this
```
sudo: required

language: scala
scala:
   - 2.11.8

services:
  - docker

before_install:
  - pip install --upgrade pip setuptools six
  - pip3 install --upgrade pip setuptools six

```
It errors like this:
```
$ pip install --upgrade pip setuptools six
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
Collecting setuptools
  Downloading setuptools-36.4.0-py2.py3-none-any.whl (478kB)
    100% |████████████████████████████████| 481kB 1.8MB/s 
Collecting six
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: setuptools, six
  Found existing installation: setuptools 36.3.0
    Uninstalling setuptools-36.3.0:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/bin/easy_install'
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

Please advise

**Comment by stlaz** [comment]
Getting the very same `pyenv: pip3: command not found` issue as @rhs. Is there a way around for this yet or should we just use the older image?
Repo: https://github.com/freeipa/freeipa
Sample build: https://travis-ci.org/freeipa/freeipa/jobs/273180675

**Comment by reactive-firewall** [comment]
Also getting the same kinds of errors with pip module in python3
Repo: https://www.github.com/reactive-firewall/Pocket-PiAP
Checkout hash: 55a877cbbc69a88524f2bcdf07b6d6d5d8536e5e
Sample Build: (239.1) https://travis-ci.org/reactive-firewall/Pocket-PiAP/jobs/273182690
relevant Log:
```plain
$ travis_retry python3 -m pip install tox || python3 -m pip install tox || true ;

/usr/bin/python3: No module named pip

The command "python3 -m pip install tox" failed. Retrying, 2 of 3.

/usr/bin/python3: No module named pip
```

**Comment by BanzaiMan** [comment]
Instead of giving us details here, it is far better to open individual issues and link to them. (Do give brief descriptions here.) We cannot keep track of multiple issues at play.

**Comment by chrissimpkins** [comment]
Received the following exception with Python 2.7 (as default Linux install, not otherwise specified in .travis.yml build matrices) builds on default Linux platform with language specified in travis.yml file as `generic` beginning yesterday:

```
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
```

The testing was not against a specific version of Python (not important for these tests) and this was resolved with conversion of travis.yml settings to `language: python` and explicit inclusion of `python: "3.6"` in the build matrices for our testing on Linux builds.

Example error build job: https://travis-ci.org/source-foundry/Hack/jobs/273130180
Associated .travis.yml settings file for fail: https://github.com/source-foundry/Hack/blob/dev-hints/.travis.yml

Example workaround build job: https://travis-ci.org/source-foundry/Hack/jobs/273320550
Associated .travis.yml settings file for pass: https://github.com/source-foundry/Hack/blob/dev-travis-ci-python-v/.travis.yml

Happy to post as a more detailed separate report if that would be helpful.  Please let me know if you need additional information.

**Comment by rhelmot** [comment]
Here is a workaround I found for a python issue that cropped up after the upgrade:

Our testing uses setup scripts that use `virtualenvwrapper` to manage python virtual environments. Previously, we had been using the `ruby` image (the language, not the steven universe character. awkward.) because it didn't come with `pyenv`, since pyenv and virtualenvwrapper obviously don't play nice together. Since the update, everything is using the sugalite image, which comes with pyenv, so everything is fucked.

The workaround is to set the environment variable `VIRTUALENVWRAPPER_PYTHON=$(pyenv which python)` prior to loading the virtualenvwrapper script. This will allow virtualenvwrapper to bypass pyenv and have everything work correctly.

**Comment by fosterbrereton** [comment]
Our running of `pip install conan`, which used to succeed before, has started to fail. A log where the error can be seen is [here](https://travis-ci.org/stlab/libraries/jobs/273078954). The new error that's cropped up is:
```shell
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/jwt'
```
Is this related to the recent Trusty updates?

**Comment by fosterbrereton** [comment]
@csantanapr A workaround that got me unstuck was to prepend the `pip` commands with `sudo`, e.g.

```shell
sudo pip install conan
```
YMMV.

(Note that there are _several_ security issues with using `sudo pip`; it is not a viable permanent solution to the problem.)

**Comment by daneah** [comment]
I, among others, see MySQL connection issues when moving from `precise` to `trusty`, as [documented here](https://github.com/travis-ci/travis-ci/issues/8331). This still seems to be a problem as of this morning!

**Comment by audiolion** [comment]
My TOX builds are failing for python 3.5 only

https://travis-ci.org/jjkester/django-auditlog/builds/274268676

**Comment by hroest** [comment]
It seems that there currently is an issue with using Clang 3.9 and not having libomp available, therefore making our C++ projects with OpenMP fail in the linking stage when using clang. We can still compile without OpenMP support and we can still use gcc with OpenMP. However, Clang 3.9 does not seem to work with libgomp and we cannot install libomp on the 14.04 system (since it is only available for 16.04). Any help would be appreciate here or over at https://github.com/OpenMS/OpenMS/pull/2906

**Comment by eed3si9n** [comment]
Reported `_JAVA_OPTIONS` causing problem for me as https://github.com/travis-ci/travis-ci/issues/8408.

workaround:

```
# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=
```
