### ISSUE TITLE
NodeJS spawn EACCES flow-bin

### ISSUE THREAD

**Issue by mymattcarroll** [travis-ci/travis-ci#8341]
Getting an error on all of our NodeJS builds, (versions 4, 6 and 8) where [flow-bin](https://www.npmjs.com/package/flow-bin) is installed into `devDependencies` and we attempt to run:

```sh
flow check
```

This is the error:

```
> package-name@0.0.1 flow_check /home/travis/build/organisation/package-name
> flow check
internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^
Error: spawn EACCES
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (/home/travis/build/organisation/package-name/node_modules/flow-bin/cli.js:17:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

This error only started appearing on September 2nd 2017.

**Comment by mymattcarroll** [comment]
Closing as this seems to be a issue with npm: 
https://github.com/npm/npm/issues/18324
https://github.com/facebook/flow/issues/4733
