### ISSUE TITLE
Deploying to gh-pages fails repeatedly

### ISSUE THREAD

**Issue by m-Schlitzer** [travis-ci/travis-ci#8343]
I tried to deploy the documentation of https://github.com/m-Schlitzer/ews-cpp/ via travis-ci but it failed repeatedly showing this error and the stacktrace.

```
travis_fold:end:dpl.1
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:1387:in `copy': unknown file type: /home/travis/build/m-Schlitzer/[secure]/html/. (RuntimeError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:472:in `block in copy_entry'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:1498:in `call'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:1498:in `wrap_traverse'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:469:in `copy_entry'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:444:in `block in cp_r'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:1571:in `block in fu_each_src_dest'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:1585:in `fu_each_src_dest0'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:1569:in `fu_each_src_dest'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/fileutils.rb:443:in `cp_r'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider/pages.rb:68:in `block in push_app'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider/pages.rb:67:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.42/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
travis_fold:start:dpl.2
[33mPreparing deploy[0m

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m

travis_fold:end:dpl.3
failed to deploy
```

The build works, and the documentation is generated locally and on travis-ci. The only thing failing is the deployment.  
The [.travis.yml](https://github.com/m-Schlitzer/ews-cpp/blob/ddb1de458fa4fad66909350fdaedb7fe3195bb4b/.travis.yml)

**Comment by BanzaiMan** [comment]
Are you sure /home/travis/build/m-Schlitzer/ews-app/html exists at the end of the build? Your build is changing the working directory to `$TRAVIS_BUILD_DIR/build` (https://github.com/m-Schlitzer/ews-cpp/blob/ddb1de458fa4fad66909350fdaedb7fe3195bb4b/.travis.yml#L7) and runs `cmake` there. Unless your build explicitly instructs the output to be in `../html`, the directory you specify in the configuration will not exist.

I ran your build steps, and confirmed that it is in `$TRAVIS_BUILD_DIR/build/html`.

**Comment by m-Schlitzer** [comment]
I overlooked that completely, thank you! It works now!
