### ISSUE TITLE
casher:188 no space left on device

### ISSUE THREAD

**Issue by elhindu** [travis-ci/travis-ci#8369]
when executing the command : store build cache,

We get the no space issue.  This seems to be a new problem.  How do we either get more space or figure out why we're needing more space than before?

Trace follows :

store build cache
travis_time:start:249d9824
[0K
travis_time:end:249d9824:start=1504816948683654245,finish=1504816948690365891,duration=6711646
[0Ktravis_time:start:131b2f7e
[0KLatest version currently installed. Aborting.
[32;1mchange detected (content changed, file is created, or file is deleted):
/home/travis/.m2/repository/com/argyledata/streams/extract/0.4.7.15-SNAPSHOT/extract-0.4.7.15-SNAPSHOT-bin.tar.gz
/home/travis/.m2/repository/com/argyledata/streams/extract/0.4.7.15-SNAPSHOT/extract-0.4.7.15-SNAPSHOT.jar
/home/travis/.m2/repository/com/argyledata/streams/extract/0.4.7.15-SNAPSHOT/extract-0.4.7.15-SNAPSHOT.pom
/home/travis/.m2/repository/com/argyledata/streams/extract/0.4.7.15-SNAPSHOT/maven-metadata-local.xml
/home/travis/.m2/repository/com/argyledata/streams/extract/0.4.7.15-SNAPSHOT/_remote.repositories
/home/travis/.m2/repository/com/argyledata/streams/extract/maven-metadata-local.xml
/home/travis/.m2/repository/com/argyledata/streams/featurization-core/0.4.7.15-SNAPSHOT/featurization-core-0.4.7.15-SNAPSHOT.jar
/home/travis/.m2/repository/com/argyledata/streams/featurization-core/0.4.7.15-SNAPSHOT/featurization-core-0.4.7.15-SNAPSHOT.pom
/home/travis/.m2/repository/com/argyledata/streams/featurization-core/0.4.7.15-SNAPSHOT/maven-metadata-local.xml
/home/travis/.m2/r
[0m
[32;1m...
[0m
[32;1mchanges detected, packing new archive[0m
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
/home/travis/.casher/bin/casher:188:in `write': No space left on device @ fptr_finalize - /home/travis/.casher/tar.err.log (Errno::ENOSPC)
	from /home/travis/.casher/bin/casher:188:in `tar'
	from /home/travis/.casher/bin/casher:129:in `push'
	from /home/travis/.casher/bin/casher:52:in `block in run'
	from /home/travis/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
	from /home/travis/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/timeout.rb:33:in `block in catch'
	from /home/travis/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/timeout.rb:33:in `catch'
	from /home/travis/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/timeout.rb:33:in `catch'
	from /home/travis/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/timeout.rb:105:in `timeout'
	from /home/travis/.casher/bin/casher:52:in `run'
	from /home/travis/.casher/bin/casher:240:in `<main>'

**Comment by BanzaiMan** [comment]
Perhaps your build is gobbling up more of the **Internet** (via maven download). You'd have to trim down what goes in the cache. Different infrastructures have different disk spaces available, but beyond that, there is not a whole lot of knobs to turn.

**Comment by elhindu** [comment]
Hiro,

We’ve lost the guy who initially set up and maintained the github/travis account for us.  Can you tell us which plan we’re currently on, what it’s limits are and what the next step up would be?

Thanks,
Vipin Agrawal

**Comment by BanzaiMan** [comment]
@elhindu Could you email us at support@travis-ci.com with details, please?
