### ISSUE TITLE
_JAVA_OPTIONS causes problems

### ISSUE THREAD

**Issue by eed3si9n** [travis-ci/travis-ci#8408]
### steps

sbt project (https://travis-ci.org/sbt/sbt/pull_requests) has been using:

```
{
  "sudo": false,
  "language": "scala",
  "jdk": "oraclejdk8",
...
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
```

### problem

We started seeing unexplainable errors in certain jobs during PR validation (socket getting closed etc) in the last day or two. Restarting the jobs sometimes fixes the problem, but they were failing more frequently than succeeding.

### workaround

[2017-09-06](https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/) update says that `_JAVA_OPTIONS="-Xmx2048m -Xms512m"` is now set, so I've added `before_script` to [unset it](https://github.com/sbt/sbt/pull/3522):

```
# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=
```

All jobs passed in the first run, so I am thinking this was the cause of the instability.

### notes

It could be that some of our integration tests are sensitive to `_JAVA_OPTIONS` because there are forked JVM process, or some underlying libraries are picking it up. I am not sure.

**Comment by BanzaiMan** [comment]
`_JAVA_OPTIONS` was set to such values in order to avoid Java processes getting killed by the host when they run inside containers.

Do you have examples of failures?

**Comment by eed3si9n** [comment]
Here are some of the failed jobs:

- https://travis-ci.org/sbt/sbt/jobs/274608340
- https://travis-ci.org/sbt/sbt/jobs/274608346
- https://travis-ci.org/sbt/sbt/jobs/274608352

These are all happening during scripted tests where the main instance of `sbt` (with `-Xmx800M -Xms800M -server`) launches another freshly-built instance of `sbt` (with `-Xmx1500M -Xms512M -server`) for integration testing. The freshly-built one could potentially spawn the third JVM for occasionally for forked tasks.

### actions/doc failure

```
[error] x actions / doc 
[error]  Cause of test exception: {line 29}  Command failed
```

Not exactly sure, but it could be calling javadoc internally since the test is filtering to *.java files. https://github.com/sbt/sbt/blob/34945af6314dee3c9ea55a76c882007f44819509/sbt/src/sbt-test/actions/doc/test#L27-L29.

### run/error failure

```
[error] x run / error 
[error]  Cause of test exception: {line 18}  Command succeeded but failure was expected
```

https://github.com/sbt/sbt/blob/34945af6314dee3c9ea55a76c882007f44819509/sbt/src/sbt-test/run/error/test#L16-L18:

```
# explicitly calling System.exit(1) should fail the 'run' task
$ copy-file changes/RunExplicitFailure.scala src/main/scala/Run.scala
-> run
```

### tests / setup-cleanup "Socket closed" failure

```
sbt.internal.scripted.TestException: {line -1}  Reload for scripted batch execution failed.
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$4(ScriptedTests.scala:201)
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$4$adapted(ScriptedTests.scala:195)
	at sbt.test.ScriptedTests.$anonfun$commonRunTest$5(ScriptedTests.scala:269)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at sbt.test.ScriptedTests.commonRunTest(ScriptedTests.scala:268)
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$2(ScriptedTests.scala:205)
	at sbt.test.ScriptedTests.runOrHandleDisabled(ScriptedTests.scala:226)
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$1(ScriptedTests.scala:209)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sbt.test.ScriptedTests.runBatchTests$1(ScriptedTests.scala:178)
	at sbt.test.ScriptedTests.runBatchedTests(ScriptedTests.scala:215)
	at sbt.test.ScriptedTests.$anonfun$batchScriptedRunner$8(ScriptedTests.scala:107)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:365)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:372)
	at sbt.test.ScriptedTests.$anonfun$batchScriptedRunner$7(ScriptedTests.scala:107)
	at sbt.test.ScriptedRunner.$anonfun$runAllInParallel$1(ScriptedTests.scala:399)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.flatmap2combiner(ParArray.scala:416)
	at scala.collection.parallel.ParIterableLike$FlatMap.leaf(ParIterableLike.scala:1070)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$FlatMap.tryLeaf(ParIterableLike.scala:1066)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:375)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:375)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:414)
	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:56)
	at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:956)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:951)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: sbt.internal.scripted.TestException: {line -1}  Command failed
	at sbt.test.BatchScriptRunner.processStatement(BatchScriptRunner.scala:42)
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$4(ScriptedTests.scala:197)
	... 57 more
Caused by: java.net.SocketException: Socket closed
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at xsbt.IPC$Server.connection(IPC.scala:55)
	at sbt.test.SbtHandler.receive(SbtHandler.scala:71)
	at sbt.test.SbtHandler.$anonfun$apply$1(SbtHandler.scala:30)
	at sbt.test.SbtHandler.$anonfun$apply$1$adapted(SbtHandler.scala:28)
	at sbt.test.SbtHandler.onSbtInstance(SbtHandler.scala:39)
	at sbt.test.SbtHandler.apply(SbtHandler.scala:28)
	at sbt.test.SbtHandler.apply(SbtHandler.scala:19)
	at sbt.test.BatchScriptRunner.processStatement(BatchScriptRunner.scala:33)
	... 58 more
```

Not sure if this is to do with test itself (https://github.com/sbt/sbt/tree/34945af6314dee3c9ea55a76c882007f44819509/sbt/src/sbt-test/tests/setup-cleanup). Socket closed could just be a symptom of second JVM getting killed for some reason.

**Comment by BanzaiMan** [comment]
Thanks for the detailed information. We appreciate it.

As far as I understand, `_JAVA_OPTIONS` takes precedence over command line options such as yours (which seems rather strange to me, but we can't argue what it is). So we inadvertently made your builds unstable (because the option now allows the processes to use more memory).

The option is going to stay (and we will unset it for those running with `sudo: required`, since these have a larger resource pool). We ask that you unset `_JAVA_OPTIONS` as you did here.

Thank you.

**Comment by eed3si9n** [comment]
I am personally okay with unsetting `_JAVA_OPTIONS` as a workaround. I just wanted to file it as an issue that someone else might cross across.

Also, I am not sure if `_JAVA_OPTIONS` is taking higher precedence. It might be that we have some situation where the third JVM is being spawned without any command line arguments, and `_JAVA_OPTIONS="-Xmx2048m -Xms512m"` gets picked up for those.

**Comment by rsimha-amp** [comment]
@BanzaiMan, another data point: The AMP project was affected by this issue too. Our closure compiler was broken by the new `_JAVA_OPTIONS`. We had to unset the env var in order to unbreak our build.

See https://github.com/ampproject/amphtml/pull/11206 for more context.

**Comment by leonard84** [comment]
Yes this is definitely braking builds that fork VMs, which where running fine before (https://travis-ci.org/spockframework/spock/jobs/275257045). The problem is probably the `-Xms512m` which forces each fork to reserve 512mb heap whether it is needed or not. I would suggest to keep the `-Xmx2048m` but to drop the `-Xms512m`.

**Comment by eregon** [comment]
@BanzaiMan I believe this change is not compatible enough for most Java software running on Travis CI containers and `_JAVA_OPTIONS` should not be defined.

By the name, it already looks like something internal which should not be used.
Moreover, setting `_JAVA_OPTIONS` causes __*every*__ java command to output extra info to stderr:
```
$ _JAVA_OPTIONS="-Xmx4g" java -version
Picked up _JAVA_OPTIONS: -Xmx4g
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)
```

which is likely to fail hundreds of builds like:
https://travis-ci.org/ruby/mspec/jobs/275517765
https://travis-ci.org/jruby/jruby/jobs/275547991
https://travis-ci.org/jruby/jruby/jobs/275547981
etc

**Comment by eregon** [comment]
https://github.com/travis-ci/travis-cookbooks/pull/885 is the PR which introduced this change.

**Comment by XhmikosR** [comment]
I see the same issue with grunt-html, Bootstrap's master branch etc.

**Comment by headius** [comment]
Same issue with JRuby here: https://travis-ci.org/jruby/jruby/jobs/285764026

**Comment by huntc** [comment]
Another data point: https://github.com/huntc/landlord/pull/1 - I'm forking Java processes and capturing their output (both stderr and stdout). Travis failed my test as a consequence.

**Comment by muuki88** [comment]
Thanks @eed3si9n for reporting this issue. 

[sbt-native-packager](https://github.com/sbt/sbt-native-packager) tests that checked the configured memory settings where also failing due to this change. The tests also fork a JVM and the `JAVA_OPTIONS` override the command line options.

**Comment by schneems** [comment]
This broke sprockets test suite:

```
  1) Failure:
TestClosureCompressor#test_compress_javascript [test/test_closure_compressor.rb:15]:
--- expected
+++ actual
@@ -1,2 +1,3 @@
-"function foo(){return!0};
+"Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
+function foo(){return!0};
 "
```

The warning is getting picked up by the closure compiler.

**Comment by hannes-ucsc** [comment]
Setting `_JAVA_OPTIONS` is a bad idea. We are running an Elasticsearch instance during our tests and we would actually like to decrease (!) the amount of heap used by that instance using the documented way of setting ES_JAVA_OPTIONS. The presence of _JAVA_OPTIONS defeats that and Elasticsearch starts with 2G of max heap and 512M of initial heap (that, btw, is also against ES recommendations, they should be the same).

**Comment by karussell** [comment]
Does it overwrite the command line option set [via maven-surefire-plugin](https://stackoverflow.com/a/7579853/194609)? It looks it does (if not it should not be printed IMO), which would be really ugly as [we](https://github.com/graphhopper/graphhopper/blob/master/pom.xml#L112) **reduce** memory to 100MB in order to avoid introducing certain memory related issues.

**Comment by ab** [comment]
Any update here?
