### ISSUE TITLE
NoMemoryError when deploying

### ISSUE THREAD

**Issue by MaitreDede** [travis-ci/travis-ci#8553]
Hi,
I have configured tag based deploy for [my builds](https://travis-ci.org/MaitreDede/PiCrossCompile/builds/285214102), but I got a `NoMemoryError`.

Stack trace in logs is :
```
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/openssl/buffering.rb:317:in `do_write': failed to allocate memory (NoMemoryError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:211:in `write0'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:185:in `block in write'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:202:in `writing'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:184:in `write'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http/generic_request.rb:187:in `send_request_with_body'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http/generic_request.rb:120:in `exec'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1412:in `block in transport_request'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider/releases.rb:135:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider/releases.rb:116:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider/releases.rb:107:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider/releases.rb:107:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

**Comment by BanzaiMan** [comment]
How big is the file you are trying to upload? My guess is that it is too big to fit in memory and upload with `dpl`.

**Comment by MaitreDede** [comment]
I thing it may approach 4G. I will try to reduce its size, I think it can go below 500M...
