### ISSUE TITLE
Cannot brew install rpm on macos

### ISSUE THREAD

**Issue by stephengroat** [travis-ci/travis-ci#8650]
When installing `rpm` via `brew` on `macos`, I recieve the error that:

```
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall rpm`
```

cannot replicate locally

(https://travis-ci.org/libexpat/libexpat/jobs/293278258#L1697)

**Comment by BanzaiMan** [comment]
What's the post-install step? Is it trying to write files to somewhere `travis` doesn't have write access to?

**Comment by stephengroat** [comment]
from the `rpm.rb` formula:

```ruby
  def post_install
    (var/"lib/rpm").mkpath

    # Attempt to fix expected location of GPG to a sane default.
    gnupg = Gpg.executable || HOMEBREW_PREFIX/"bin/gpg"
    inreplace lib/"rpm/macros", "/usr/bin/gpg2", gnupg
  end
```

**Comment by kholodilov** [comment]
I have this problem locally (Sierra 10.12.6):
```Dmitrijs-MacBook-Pro:location-scoring-sparkml dmitry$ brew install rpm
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/rpm-4.14.0.sierra.bottle.ta
Already downloaded: /Users/dmitry/Library/Caches/Homebrew/rpm-4.14.0.sierra.bottle.tar.gz
==> Pouring rpm-4.14.0.sierra.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall rpm`
==> Summary
🍺  /usr/local/Cellar/rpm/4.14.0: 249 files, 7.2MB
Dmitrijs-MacBook-Pro:location-scoring-sparkml dmitry$ brew postinstall rpm
==> Postinstalling rpm
Error: undefined method `executable' for Gpg:Class
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rpm.rb:49:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:976:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:834:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:975:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:967:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:16:in `<main>'```

**Comment by stephengroat** [comment]
seems to work after the image update
