### ISSUE TITLE
Trusty 2017/Q4 updates encountered issues and their workarounds

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#8870]
The newest Trusty images are coming on **Tuesday, December 12th, 2017**. 

You can have more details here [in the following blog post](https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images).

We are proactively opening this issue to try documenting all the issues encountered, their status and how to fix them. It's read-only on purpose as we (Travis CI) will be documenting the issues.
 
Hence, if you encounter a problem with the newest images on Tuesday, please open an issue [here](https://github.com/travis-ci/travis-ci/issues) and add [the `2017-Q4-trusty-env-update` label](https://github.com/travis-ci/travis-ci/labels/2017-Q4-trusty-env-update).

In the meantime, if you are using our sudo-enabled infrastructure (i.e. with `sudo: required` in your .travis.yml file), you can test these new images right now by adding the following:

```yaml
sudo: required
dist: trusty

group: edge
```

Unfortunately, it's not possible to test in advance the new images if your are using our container-based infrastructure (i.e. with `sudo: false` in your .travis.yml file).

## Update 2017-12-12

[The new images are live!](https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch)

### Using the previous images

You can still use the previous generation of our images with the following YAML snippet in your .travis.yml file:

```yaml
sudo: required
dist: trusty
group: deprecated-2017Q4
```

Note that the above recipe ☝️ doesn't work with our container-based infrastructure (i.e. with `sudo: false`).

### List of issues

[All issues with the `2017-Q4-trusty-env-update` label](https://github.com/travis-ci/travis-ci/labels/2017-Q4-trusty-env-update)

1. [Binaries globally installed by yarn aren't found](https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351395853) - **Status: Fixed**
1. [Warning that a world-writable directory is found in $PATH](https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351440090) - **Status: Fixed**
1. [`bundler` command is failing](https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351730396) - **Status: Workaround**
1. [Syntax errors in jdk_switcher.sh are making services or APT packages installation to fail](https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351749483) - **Status: Investigating**
1. [`aws ecr get-login` / `docker login` fails](https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-352458433) - **Status: Workaround**

**Comment by cotsog** [comment]
### Binaries globally installed by `yarn` aren't found

**Issue**

https://github.com/travis-ci/travis-ci/issues/8890

**Symptoms**

```
$ yarn global install bower
$ bower --version
bower: command not found
```

**Explanation**

Before, globally installed binaries were found in /home/travis/.nvm/versions/node/v7.4.0/bin which was included in the $PATH.

Now, they are installed in /home/travis/.yarn/bin on the new image which isn't included in the $PATH.

**Workaround**

Add the following in your .travis.yml file before globally installing your binary:

```yaml
- export PATH=$PATH:`yarn global bin`
```

**Comment by cotsog** [comment]
### Warning that a world-writable directory is found in $PATH

**Issue**

https://github.com/travis-ci/travis-ci/issues/8892

**Symptoms**

```
$ gem install bundler
/home/travis/.rvm/gems/ruby-2.3.4@global/gems/gem-wrappers-1.3.2/lib/gem-wrappers/installer.rb:56: warning: Insecure world writable dir /usr/local/clang-5.0.0/bin in PATH, mode 040777
```

**Explanation**

Looks like LLVM's 5.0.0 archive at http://releases.llvm.org/5.0.0/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04.tar.xz (which we are installing on our images) has these wide-open permissions.

**Workaround**

Change the permissions manually in your .travis.yml file e.g.

```yaml
before_install:
  - sudo chmod a-w /usr/local/clang-5.0.0/bin
  ⋮
```

**Comment by cotsog** [comment]
### `bundler` command is failing

**Issue**

https://github.com/travis-ci/travis-ci/issues/8910

**Symptoms**

```
bundler install --path vendor/bundle
/home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:308:in `activate_bin_path'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/bundler:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
The command "bundler install --path vendor/bundle" failed and exited with 1 during .
```

**Explanation**

We aren't sure yet where this change is coming from but it seems you cannot call `bundler` anymore in the new images. We suspect it could be a Rubygems/Bundler bug.

**Workaround**

Call `bundle` instead i.e.

```yaml
- bundle install --path vendor/bundle
```

**Comment by cotsog** [comment]
### Syntax errors in `jdk_switcher.sh` services or APT packages installation to fail

**Issue**

https://github.com/travis-ci/travis-ci/issues/8906

**Symptoms**

With `services: [rabbitmq]` in your .travis.yml file you will see the following errors:

<details>
```
Setting up rabbitmq-server (3.7.0-1) ...

Installing new version of config file /etc/init.d/rabbitmq-server ...

Installing new version of config file /etc/logrotate.d/rabbitmq-server ...

/var/lib/dpkg/info/rabbitmq-server.postinst: 14: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 21: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 28: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 35: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 42: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 49: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 56: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 62: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 62: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 62: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 109: /opt/jdk_switcher/jdk_switcher.sh: Syntax error: "(" unexpected (expecting "fi")

dpkg: error processing package rabbitmq-server (--configure):

 subprocess installed post-installation script returned error exit status 2

Processing triggers for libc-bin (2.19-0ubuntu6.13) ...

Processing triggers for ureadahead (0.100.0-16) ...

Errors were encountered while processing:

 rabbitmq-server

W: --force-yes is deprecated, use one of the options starting with --allow instead.

E: Sub-process /usr/bin/dpkg returned an error code (1)

apt-get.diagnostics

apt-get install failed
```
</details>

**Explanation**

We are looking into it.

**Workaround**

We are looking into it.

**Comment by cotsog** [comment]
### `aws ecr get-login` fails

**Issue**

https://github.com/travis-ci/travis-ci/issues/8901

**Symptoms**

To be added.

**Explanation**

The Docker CLI has been updated on our newest Trusty images to version 17.09 and the '-e/--email' option was deprecated and removed in version 17.06. On the AWS CLI side, [their documentation](http://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html#options) mentions the following for `aws ecr get-login`:

> You must specify --no-include-email if you're using docker version 17.06 or later.

**Workaround**

Add the `--no-include-email` to your `aws ecr get-login` command i.e.

```
- aws ecr get-login --no-include-email
```
