### ISSUE TITLE
Bundler not working in new trusty image

### ISSUE THREAD

**Issue by tandrewnichols** [travis-ci/travis-ci#8910]
Our builds are node.js but use Ruby for deploying. Since the trusty update, we get errors that bundler is missing when we run `bundler install` (in our install step). I've debugged the build and it _is_ there (`which bundler` works and it _is_ in $PATH). Here's the error we're seeing:

```
bundler install --path vendor/bundle
/home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:308:in `activate_bin_path'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/bundler:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
The command "bundler install --path vendor/bundle" failed and exited with 1 during .
```

**Comment by BanzaiMan** [comment]
The command you’re looking for is `bundle`, is it not?

**Comment by tandrewnichols** [comment]
I can't say for sure . . . but that command hasn't changed in our `.travis.yml` in . . . years. So unless you're telling me that travis is using a newer version of Ruby that no longer works that way, I'd say no.

**Comment by tandrewnichols** [comment]
I do see a lot of stuff on the web to that effect. But why would it have been working for the last 3 years if that's the problem?

**Comment by BanzaiMan** [comment]
I've spoken with @segiddins, and he suspects it might be a RubyGems/Bundler bug.

At any rate, however, I personally recommend using `bundle` instead.

**Comment by tandrewnichols** [comment]
We'll give it a try. Thanks!

**Comment by cotsog** [comment]
Cross-linking to the documented issue and workaround: https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351730396

**Comment by Bilge** [comment]
@BanzaiMan Changing `bundler` invocation to `bundle` fixed it for me 👍

**Comment by BanzaiMan** [comment]
See https://github.com/rubygems/rubygems/pull/2112 for a general long-term fix.

**Comment by tandrewnichols** [comment]
`bundle install` works for me as well.
