### ISSUE TITLE
pytest/py.test not working python <= 3.3

### ISSUE THREAD

**Issue by bannsec** [travis-ci/travis-ci#9002]
Looks like there are some issues with pytest on python <= 3.3. From what I can tell, travis-ci installs py.test by default on those versions, but that version doesn't work. Updating it doesn't seem to work either.

```
[0K$ pip install -U pip setuptools && pip install .[dev]
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Collecting setuptools
  Downloading setuptools-38.2.5-py2.py3-none-any.whl (489kB)
Installing collected packages: pip, setuptools
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
  Found existing installation: setuptools 18.0.1
    Uninstalling setuptools-18.0.1:
      Successfully uninstalled setuptools-18.0.1
Successfully installed pip-7.1.2 setuptools-38.2.5
Processing /home/travis/build/bannsec/pyCoW
Requirement already satisfied: pytest in /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages (from pyCoW==0.0.1)
Collecting python-coveralls (from pyCoW==0.0.1)
  Downloading python_coveralls-2.9.1-py2.py3-none-any.whl
Collecting coverage (from pyCoW==0.0.1)
  Downloading coverage-4.4.2-cp33-cp33m-manylinux1_x86_64.whl (195kB)
Collecting pytest-cov (from pyCoW==0.0.1)
  Downloading pytest_cov-2.5.1-py2.py3-none-any.whl
Collecting pytest-xdist (from pyCoW==0.0.1)
  Downloading pytest_xdist-1.20.1-py2.py3-none-any.whl
Collecting ipython (from pyCoW==0.0.1)
  Downloading ipython-6.2.1-py3-none-any.whl (745kB)
Requirement already satisfied: py>=1.4.29 in /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages (from pytest->pyCoW==0.0.1)
Requirement already satisfied: six in /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages (from python-coveralls->pyCoW==0.0.1)
Collecting requests (from python-coveralls->pyCoW==0.0.1)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting PyYAML (from python-coveralls->pyCoW==0.0.1)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting execnet>=1.1 (from pytest-xdist->pyCoW==0.0.1)
  Downloading execnet-1.5.0-py2.py3-none-any.whl
Collecting pytest-forked (from pytest-xdist->pyCoW==0.0.1)
  Downloading pytest_forked-0.2-py2.py3-none-any.whl
Collecting pygments (from ipython->pyCoW==0.0.1)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython->pyCoW==0.0.1)
  Downloading prompt_toolkit-1.0.15-py3-none-any.whl (247kB)
Collecting jedi>=0.10 (from ipython->pyCoW==0.0.1)
  Downloading jedi-0.11.1-py2.py3-none-any.whl (250kB)
Requirement already satisfied: setuptools>=18.5 in /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages (from ipython->pyCoW==0.0.1)
Collecting traitlets>=4.2 (from ipython->pyCoW==0.0.1)
  Downloading traitlets-4.3.2-py2.py3-none-any.whl (74kB)
Collecting typing; python_version <= "3.4" (from ipython->pyCoW==0.0.1)
  Downloading typing-3.6.2-py3-none-any.whl
Collecting decorator (from ipython->pyCoW==0.0.1)
  Downloading decorator-4.1.2-py2.py3-none-any.whl
Collecting pickleshare (from ipython->pyCoW==0.0.1)
  Downloading pickleshare-0.7.4-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython->pyCoW==0.0.1)
  Downloading pexpect-4.3.1-py2.py3-none-any.whl (55kB)
Collecting pathlib2; python_version == "3.3" (from ipython->pyCoW==0.0.1)
  Downloading pathlib2-2.3.0-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython->pyCoW==0.0.1)
  Downloading simplegeneric-0.8.1.zip
Collecting idna<2.7,>=2.5 (from requests->python-coveralls->pyCoW==0.0.1)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests->python-coveralls->pyCoW==0.0.1)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests->python-coveralls->pyCoW==0.0.1)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
Collecting urllib3<1.23,>=1.21.1 (from requests->python-coveralls->pyCoW==0.0.1)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Collecting apipkg>=1.4 (from execnet>=1.1->pytest-xdist->pyCoW==0.0.1)
  Downloading apipkg-1.4-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython->pyCoW==0.0.1)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Collecting parso==0.1.1 (from jedi>=0.10->ipython->pyCoW==0.0.1)
  Downloading parso-0.1.1-py2.py3-none-any.whl (91kB)
Collecting enum34; python_version == "3.3" (from traitlets>=4.2->ipython->pyCoW==0.0.1)
  Downloading enum34-1.1.6-py3-none-any.whl
Collecting ipython-genutils (from traitlets>=4.2->ipython->pyCoW==0.0.1)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython->pyCoW==0.0.1)
  Downloading ptyprocess-0.5.2-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "3.3"->ipython->pyCoW==0.0.1)
  Downloading scandir-1.6.tar.gz
Building wheels for collected packages: PyYAML, simplegeneric, scandir
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for simplegeneric: started
  Running setup.py bdist_wheel for simplegeneric: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/7b/31/08/c85e74c84188cbec6a6827beec4d640f2bd78ae003dc1ec09d
  Running setup.py bdist_wheel for scandir: started
  Running setup.py bdist_wheel for scandir: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/6e/33/69/090d9633efb6fe3c8077c40e1676819ed8d5a59b41cc9a5bea
Successfully built PyYAML simplegeneric scandir
Installing collected packages: idna, chardet, certifi, urllib3, requests, coverage, PyYAML, python-coveralls, pytest-cov, apipkg, execnet, pytest-forked, pytest-xdist, pygments, wcwidth, prompt-toolkit, parso, jedi, enum34, ipython-genutils, decorator, traitlets, typing, scandir, pathlib2, pickleshare, ptyprocess, pexpect, simplegeneric, ipython, pyCoW
  Running setup.py install for pyCoW: started
    Running setup.py install for pyCoW: finished with status 'done'
Successfully installed PyYAML-3.12 apipkg-1.4 certifi-2017.11.5 chardet-3.0.4 coverage-4.4.2 decorator-4.1.2 enum34-1.1.6 execnet-1.5.0 idna-2.6 ipython-6.2.1 ipython-genutils-0.2.0 jedi-0.11.1 parso-0.1.1 pathlib2-2.3.0 pexpect-4.3.1 pickleshare-0.7.4 prompt-toolkit-1.0.15 ptyprocess-0.5.2 pyCoW-0.0.1 pygments-2.2.0 pytest-cov-2.5.1 pytest-forked-0.2 pytest-xdist-1.20.1 python-coveralls-2.9.1 requests-2.18.4 scandir-1.6 simplegeneric-0.8.1 traitlets-4.3.2 typing-3.6.2 urllib3-1.22 wcwidth-0.1.7

travis_time:end:34425a08:start=1514923487181473099,finish=1514923517084329654,duration=29902856555
[0Ktravis_fold:end:install
[0Ktravis_time:start:1293615f
[0K$ pytest || py.test
The program 'pytest' is currently not installed. To run 'pytest' please ask your administrator to install the package 'python-logilab-common'
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.6/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/config.py", line 39, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/config.py", line 118, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/config.py", line 861, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/config.py", line 966, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/config.py", line 927, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/_pytest/vendored_packages/pluggy.py", line 501, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 2407, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 2430, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 2.9.2 (/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages), Requirement.parse('pytest>=3.0.0'))

travis_time:end:1293615f:start=1514923517090873514,finish=1514923517596643256,duration=505769742
[0K
[31;1mThe command "pytest || py.test" exited with 1.[0m
```

**Comment by hugovk** [comment]
Pytest 3.3.0+ no longer supports Python 3.3 (or 2.6), which is EOL and no longer receiving security updates.

https://docs.pytest.org/en/latest/changelog.html#pytest-3-3-0-2017-11-23


![image](https://user-images.githubusercontent.com/1324225/34263159-38b766bc-e677-11e7-918b-54bc889cfff0.png)

https://en.wikipedia.org/wiki/CPython#Version_history


If you really need Python 3.3, pin to an old version something like `pip install "pytest<3.3.0"`.



But Python 3.3 isn't used very much, you're probably better off just dropping it. 

Here's monthly pip installs from PyPI (13 December 2017, via `pypinfo --percent --pip --markdown "" pyversion`) showing only about 0.1% for Python 3.3:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   77.7% |    435,636,261 |
| 3.6            |    8.8% |     49,199,570 |
| 3.5            |    8.4% |     46,927,461 |
| 3.4            |    3.9% |     21,843,444 |
| 2.6            |    1.1% |      6,194,026 |
| 3.3            |    0.1% |        554,661 |
| 3.7            |    0.1% |        428,159 |
| 3.2            |    0.0% |         38,570 |
| None           |    0.0% |         21,921 |
| 2.8            |    0.0% |             35 |
| 3.1            |    0.0% |             26 |

**Comment by bannsec** [comment]
Ah interesting. Didn't know that (or about that pypinfo tool). thanks!
