### ISSUE TITLE
Deploy to already existing GitHub Release fails even with deploy.overwrite: true

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#9209]
If GitHub Release to be deployed to already exists, then deploy fails even with `deploy.overwrite` set to `true`. 

Log:
```
Current tag is: master/200
file.7z already exists, overwriting.
file.exe already exists, overwriting.
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': PATCH https://api.github.com/repos/org/repo/releases/9571845: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: Release
  code: already_exists
  field: tag_name // See: https://developer.github.com/v3/repos/releases/#edit-a-release
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:175:in `patch'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:46:in `patch'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:55:in `update_release'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/releases.rb:126:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

**Comment by BanzaiMan** [comment]
Isn't this a duplicate of #9208? The entity that GitHub is raising flags is `tag_name`. `overwrite: true` means overwriting existing files, not overwriting the existing Release.

**Comment by Deilan** [comment]
@BanzaiMan It's a separate problem. It's about overwriting existing files as far: It is being reproduced when files to be written are already there and is not being reproduced if they don't exist.

**Comment by Deilan** [comment]
I thought it was because files already exist, but you're right: it's about already existing release. I will change the description then.

No, it's not a duplicate of #9208 because this issue will still be there even after `tag_name` will be honored: it will be reproduced for every rerun of build with deployment to GitHub Releases.

**Comment by Deilan** [comment]
@BanzaiMan I thought it was because files already exist, but you're right: it's about already existing release. I will change the description then.

No, it's not a duplicate of #9208 because this issue will still be there even after `tag_name` will be honored: it will be reproduced for every rerun of build with deployment to GitHub Releases.

**Comment by BanzaiMan** [comment]
That's a duplicate of #8248, right?

**Comment by Deilan** [comment]
@BanzaiMan Doesn't look like a duplicate of #8248 to me.

From #8248's description I don't get what's the actual problem of OP. And in my case there's a very simple expected/actual difference:
```
Error summary:
  resource: Release
  code: already_exists
```

which is not mentioned is #8248 at all.
