### ISSUE TITLE
lzma is broken for osx for python3 nightly

### ISSUE THREAD

**Issue by KOLANICH** [travis-ci/travis-ci#9244]
```js
{
  "sudo": false,
  "language": "python",
  "install": [
    "pip install six",
    "pip install pycryptodome",
    "pip install chardet"
  ],
  "script": "nosetests --nologcapture",
  "os": "osx",
  "python": "nightly"
}
```
```
File "/Users/travis/build/KOLANICH/pdfminer.six/pdfminer/cmapdb.py", line 18, in <module>
    import lzma
  File "/opt/python/3.7-dev/lib/python3.7/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/travis/build/KOLANICH/pdfminer.six/pdfminer/cmapdb.py", line 21, in <module>
    import backports.lzma as lzma
ModuleNotFoundError: No module named 'backports'
```

**Comment by BanzaiMan** [comment]
Sorry, but we don't support Python on the Mac. https://github.com/travis-ci/travis-ci/issues/2312 Any trace of support you might see is an accident.
