### ISSUE TITLE
Travis CLI Error on Mac OS

### ISSUE THREAD

**Issue by joesan** [travis-ci/travis-ci#9292]
Not sure if this is caused by some faulty installation on my Mac Book Pro with a High Sierra OS.

I get this error when I call any travis cli:

> -bash: /usr/local/bin/travis: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

I would please need help to resolve this?

I then tried to do a fresh install and I get this error:

```
Joes-MacBook-Pro:plant-simulator joe$ gem install travis -v 1.8.8 --no-rdoc --no-ri
Building native extensions. This could take a while...
ERROR:  Error installing travis:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.23/ext/ffi_c
/usr/local/opt/ruby/bin/ruby -r ./siteconf20180305-50317-1bqw1ti.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.5.0_2/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:590:in `try_cpp'
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:1097:in `block in have_header'
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:947:in `block in checking_for'
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:350:in `block in postpone'
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:346:in `postpone'
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:946:in `checking_for'
	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/mkmf.rb:1096:in `have_header'
	from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0/ffi-1.9.23/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.5.0/gems/ffi-1.9.23 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0/ffi-1.9.23/gem_make.out
```

**Comment by joesan** [comment]
I resolved this by doing the following:

Go to https://developer.apple.com/download/more/ and download XCode for Mac High Sierra 10.13 (the version that I have).

After the XCode was fully installed, I did the following to install the Travis CLI:

gem install travis -v 1.8.8 --no-rdoc --no-ri

I guess the problem with my Mac was I had an older version of Mac OS where I had travis installed. I recently upgraded to a new Mac OS High Sierra and travis CLI stopped working since then. But I managed to resolve it!
