### ISSUE TITLE
Travis-CI PyPI deployment setup broken

### ISSUE THREAD

**Issue by Samreay** [travis-ci/travis-ci#9303]
Hi guys,

Seems like there are now issues with deploying to PyPI from Travis-CI, setting up the environment fails. This may be an issue with `pip` instead of Travis-CI though.

With a super simple .travis.yml deployment section of

```
deploy:
  - provider: pypi
    user: "samreay"
    password:
      secure: [redacted]
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9,\.]*$
      python: 3.6
```

The travis build fails with:

```
Installing deploy dependencies
--2018-03-07 03:27:11--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.0.175, 151.101.64.175, 151.101.128.175, ...
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.0.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1595408 (1.5M) [text/x-python]
Saving to: ‘STDOUT’
     0K .......... .......... .......... .......... ..........  3% 2.13M 1s
    50K .......... .......... .......... .......... ..........  6% 5.64M 0s
   100K .......... .......... .......... .......... ..........  9% 14.6M 0s
   150K .......... .......... .......... .......... .......... 12% 7.09M 0s
   200K .......... .......... .......... .......... .......... 16% 29.0M 0s
   250K .......... .......... .......... .......... .......... 19% 17.9M 0s
   300K .......... .......... .......... .......... .......... 22% 9.69M 0s
   350K .......... .......... .......... .......... .......... 25% 12.5M 0s
   400K .......... .......... .......... .......... .......... 28% 20.0M 0s
   450K .......... .......... .......... .......... .......... 32% 12.6M 0s
   500K .......... .......... .......... .......... .......... 35% 17.9M 0s
   550K .......... .......... .......... .......... .......... 38% 19.2M 0s
   600K .......... .......... .......... .......... .......... 41% 15.4M 0s
   650K .......... .......... .......... .......... .......... 44% 10.6M 0s
   700K .......... .......... .......... .......... .......... 48% 38.4M 0s
   750K .......... .......... .......... .......... .......... 51% 13.3M 0s
   800K .......... .......... .......... .......... .......... 54% 19.6M 0s
   850K .......... .......... .......... .......... .......... 57% 11.8M 0s
   900K .......... .......... .......... .......... .......... 60% 22.3M 0s
   950K .......... .......... .......... .......... .......... 64% 23.4M 0s
  1000K .......... .......... .......... .......... .......... 67% 11.1M 0s
  1050K .......... .......... .......... .......... .......... 70% 29.7M 0s
  1100K .......... .......... .......... .......... .......... 73% 22.3M 0s
  1150K .......... .......... .......... .......... .......... 77% 14.5M 0s
  1200K .......... .......... .......... .......... .......... 80% 13.8M 0s
  1250K .......... .......... .......... .......... .......... 83% 21.2M 0s
  1300K .......... .......... .......... .......... .......... 86% 26.0M 0s
  1350K .......... .......... .......... .......... .......... 89% 21.7M 0s
  1400K .......... .......... .......... .......... .......... 93% 13.7M 0s
  1450K .......... .......... .......... .......... .......... 96% 15.4M 0s
  1500K .......... .......... .......... .......... .......... 99% 66.8M 0s
  1550K ........                                              100%  294M=0.1s
2018-03-07 03:27:11 (12.7 MB/s) - written to stdout [1595408/1595408]
Traceback (most recent call last):
  File "<stdin>", line 20061, in <module>
  File "<stdin>", line 194, in main
  File "<stdin>", line 82, in bootstrap
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/tmp/tmpz8evqxsk/pip.zip/pip/__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/tmp/tmpz8evqxsk/pip.zip/pip/utils/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/tmp/tmpz8evqxsk/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
  File "/tmp/tmpz8evqxsk/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
  File "/tmp/tmpz8evqxsk/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
  File "/tmp/tmpz8evqxsk/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
  File "/tmp/tmpz8evqxsk/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
  File "/tmp/tmpz8evqxsk/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
  File "/tmp/tmpz8evqxsk/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
AttributeError: '_NamespacePath' object has no attribute 'sort'
Couldn't install pip, setuptools, twine or wheel.
```

If this is not an environment issue causing `pip` to fail, I'll raise a bug for `pip` and try and find a version that works. Any thoughts appreciated.

**Comment by BanzaiMan** [comment]
Hello there. Thanks for taking time to open the issue. Please refrain from addressing us with "guys", since not all of us are.

With that out of the way, I see that the command that's failing in your case is:

    wget -O - https://bootstrap.pypa.io/get-pip.py | python - --no-setuptools --no-wheel && pip install --upgrade setuptools twine wheel

Seems like a widespread issue. https://stackoverflow.com/questions/43169218/attributeerror-namespacepath-object-has-no-attribute-sort

**Comment by Samreay** [comment]
Yeah, when hunting for a bug fix I found it a lot, with most recommendations being to upgrade or use a specific version of `pip` or `setuptools`. Unfortunately, the command that is executed is done by Travis-CI and (as far as I am aware) I (nor other developers using Travis-CI) have no control over it.

**Comment by BanzaiMan** [comment]
If you have a suggestion to improve this command, we are happy to try.

**Comment by spyoungtech** [comment]
Found [this](https://github.com/mandeep/Travis-Encrypt/commit/34b4bc1e548d8116969ed1807b6472606e338981) in a repository mentioning the problem. It seems that this might be fixable by adding the following to revert to the old travis behavior.

```
edge:
  branch: v1.8.45
```

I'm no expert and I'm not sure if this actually works or not, just thought I would share here.

**Comment by Samreay** [comment]
Good find, glad there's a work around until the issue gets fixed upstream. I'll test it on my project on Monday to confirm.

**Comment by Xonshiz** [comment]
Was trying to deploy my basic setup and ran into this issue. @spyoungtech solution is still valid in 2020.

**Comment by spyoungtech** [comment]
Good to know this helped @Xonshiz 

By the way, it is 2021 :-)
