### ISSUE TITLE
Gitlab deployment broken after 1.9.0 update

### ISSUE THREAD

**Issue by kknd113** [travis-ci/travis-ci#9313]
```
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- dpl/provider/elastic_beanstalk (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/local/bundle/gems/dpl-1.9.0/lib/dpl/provider.rb:92:in `rescue in block in new'
	from /usr/local/bundle/gems/dpl-1.9.0/lib/dpl/provider.rb:67:in `block in new'
	from /usr/local/bundle/gems/dpl-1.9.0/lib/dpl/cli.rb:41:in `fold'
	from /usr/local/bundle/gems/dpl-1.9.0/lib/dpl/provider.rb:66:in `new'
	from /usr/local/bundle/gems/dpl-1.9.0/lib/dpl/cli.rb:31:in `run'
	from /usr/local/bundle/gems/dpl-1.9.0/lib/dpl/cli.rb:7:in `run'
	from /usr/local/bundle/gems/dpl-1.9.0/bin/dpl:5:in `<top (required)>'
	from /usr/local/bundle/bin/dpl:23:in `load'
	from /usr/local/bundle/bin/dpl:23:in `<main>'
```

**Comment by BanzaiMan** [comment]
Sorry, but we don't know how Gitlab uses `dpl`. Please contact their support.
