### ISSUE TITLE
scripts/compile fails in current iteration of docker container

### ISSUE THREAD

**Issue by ross-spencer** [travis-ci/travis-ci#9353]
This [issue](https://github.com/travis-ci/travis-ci/issues/8098) still seems to exist in current versions of the docker container, see the trace below:
```
root@99270973463d:/usr/src/app/script# ./compile 
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- travis/support (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/src/app/lib/travis/build.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from ./compile:5:in `<main>'
```
Further, while `compile` exists in the script directory, it does not get added to the available commands:
```
root@99270973463d:/usr/src/app/script# travis
Usage: travis COMMAND ...

Available commands:

	accounts       displays accounts and their subscription status
	branches       displays the most recent build for each branch
	cache          lists or deletes repository caches
	cancel         cancels a job or build
	console        interactive shell
	disable        disables a project
	enable         enables a project
	encrypt        encrypts values for the .travis.yml
	encrypt-file   encrypts a file and adds decryption steps to .travis.yml
	endpoint       displays or changes the API endpoint
	env            show or modify build environment variables
	help           helps you out when in dire need of information
	history        displays a projects build history
	init           generates a .travis.yml and enables the project
	lint           display warnings for a .travis.yml
	login          authenticates against the API and stores the token
	logout         deletes the stored API token
	logs           streams test logs
	monitor        live monitor for what's going on
	open           opens a build or job in the browser
	pubkey         prints out a repository's public key
	raw            makes an (authenticated) API call and prints out the result
	report         generates a report useful for filing issues
	repos          lists repositories the user has certain permissions on
	requests       lists recent requests
	restart        restarts a build or job
	settings       access repository settings
	setup          sets up an addon or deploy target
	show           displays a build or job
	sshkey         checks, updates or deletes an SSH key
	status         checks status of the latest build
	sync           triggers a new sync with GitHub
	token          outputs the secret API token
	version        outputs the client version
	whatsup        lists most recent builds
	whoami         outputs the current user
```
If I enter the container and clone `travis-support` and `travis-rollout` then `gem build ...` `gem install ...` then compile will run without complaint.

**Comment by lv7777** [comment]
I have Same Issue too.

**Comment by ashwinvis** [comment]
@ross-spencer Can you share your dockerfile?

**Comment by rokups** [comment]
Having same issue here. This is how i do it:

    docker run -it -u travis -v ~/path/to/project:/home/travis/builds/project travisci/ci-garnet:packer-1512502276-986baf0 /bin/bash

In opened shell i execute following:

	rvm install 2.3.0
	rvm use 2.3.0 --default
	cd /home/travis/builds
	git clone https://github.com/travis-ci/travis-build.git
	cd travis-build
	gem install travis
	travis version
	ln -s `pwd` ~/.travis/travis-build
	bundle install

And lastly

    cd ~/builds/project
    travis compile

Results in:

```
        /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- travis/support (LoadError)
        from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /home/travis/.travis/travis-build/lib/travis/build.rb:1:in `<top (required)>'
        from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /home/travis/.travis/travis-build/init.rb:11:in `setup'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/travis-1.8.9/lib/travis/cli/command.rb:197:in `execute'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/travis:23:in `load'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/travis:23:in `<main>'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```
