### ISSUE TITLE
Travis doesn't build on node.js 5, but works on all other versions

### ISSUE THREAD

**Issue by Yamboy1** [travis-ci/travis-ci#9499]
For some reason travis seems to fail to build on node.js 5. All of my other builds on Node.js 4,6,7,8 and 9 all pass.

It seems like the modules aren't being installed properly:

```
$ npm install 
terminal-utilities@2.4.0 /home/travis/build/Yamboy1/terminal-utilities
└── (empty)
npm ERR! Linux 4.14.12-041412-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v5.12.0/bin/node" "/home/travis/.nvm/versions/node/v5.12.0/bin/npm" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! path /home/travis/build/Yamboy1/terminal-utilities/node_modules/.staging/terminal-utilities-5edfd32b
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/travis/build/Yamboy1/terminal-utilities/node_modules/.staging/terminal-utilities-5edfd32b' -> '/home/travis/build/Yamboy1/terminal-utilities'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/travis/build/Yamboy1/terminal-utilities/node_modules/.staging/terminal-utilities-5edfd32b' -> '/home/travis/build/Yamboy1/terminal-utilities'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Linux 4.14.12-041412-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v5.12.0/bin/node" "/home/travis/.nvm/versions/node/v5.12.0/bin/npm" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! path npm-debug.log.2612673309
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.2612673309'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.2612673309'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/Yamboy1/terminal-utilities/npm-debug.log
npm ERR! code 1
The command "eval npm install  " failed. Retrying, 2 of 3.
sh: 0: getcwd() failed: No such file or directory
path.js:1144
          cwd = process.cwd();
                        ^
Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1144:25)
    at Function.Module._resolveLookupPaths (module.js:263:17)
    at Function.Module._resolveFilename (module.js:330:31)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /home/travis/.nvm/versions/node/v5.12.0/lib/node_modules/npm/bin/npm-cli.js:27:13
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v5.12.0/lib/node_modules/npm/bin/npm-cli.js:77:3)
    at Module._compile (module.js:413:34)
The command "eval npm install  " failed. Retrying, 3 of 3.
sh: 0: getcwd() failed: No such file or directory
path.js:1144
          cwd = process.cwd();
                        ^
Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1144:25)
    at Function.Module._resolveLookupPaths (module.js:263:17)
    at Function.Module._resolveFilename (module.js:330:31)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /home/travis/.nvm/versions/node/v5.12.0/lib/node_modules/npm/bin/npm-cli.js:27:13
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v5.12.0/lib/node_modules/npm/bin/npm-cli.js:77:3)
    at Module._compile (module.js:413:34)
The command "eval npm install  " failed 3 times.
The command "npm install " failed and exited with 1 during .
Your build has been stopped.
```
Why is this happening on node 5 and how can I fix it?

 https://travis-ci.org/Yamboy1/terminal-utilities/builds/366668799

**Comment by edmorley** [comment]
node.js 5 was end of lifed on 2016-06-30 and so doesn't have the latest security fixes, making it insecure:
https://github.com/nodejs/Release#release-schedule
(The same will apply to node.js 4 in 2 weeks)

As such, I'd recommend just dropping it from your testing matrix.

**Comment by Yamboy1** [comment]
Ok

**Comment by Yamboy1** [comment]
Thanks @edmorely
