### ISSUE TITLE
Travis Script broken

### ISSUE THREAD

**Issue by bytelucas** [travis-ci/travis-ci#9549]
When tying to deploy with a script, I get the following error:
```Successfully installed dpl-script-1.9.6
1 gem installed
!!! Script support is experimental !!!
/home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:54:in `system': wrong first argument (ArgumentError)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:54:in `shell'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-script-1.9.6/lib/dpl/provider/script.rb:18:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'```

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!
