### ISSUE TITLE
Unable to deploy to Google Cloud Storage: Name or service not known (SocketError)

### ISSUE THREAD

**Issue by prestonvanloon** [travis-ci/travis-ci#9556]
The build: https://travis-ci.org/prysmaticlabs/website/jobs/373329805

Some snippet of the raw log...
```
travis_time:end:0db560ee:start=1525146664854346848,finish=1525146673502839721,duration=8648492873
[0Ktravis_fold:end:cache.2
[0Ktravis_fold:start:dpl_0
[0Ktravis_time:start:1269e742
[0K$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Fetching: dpl-1.9.6.gem
Fetching: dpl-1.9.6.gem (  6%)
Fetching: dpl-1.9.6.gem ( 14%)
Fetching: dpl-1.9.6.gem ( 23%)
Fetching: dpl-1.9.6.gem ( 31%)
Fetching: dpl-1.9.6.gem ( 39%)
Fetching: dpl-1.9.6.gem ( 47%)
Fetching: dpl-1.9.6.gem ( 55%)
Fetching: dpl-1.9.6.gem ( 63%)
Fetching: dpl-1.9.6.gem ( 71%)
Fetching: dpl-1.9.6.gem ( 79%)
Fetching: dpl-1.9.6.gem ( 87%)
Fetching: dpl-1.9.6.gem ( 95%)
Fetching: dpl-1.9.6.gem (100%)
Fetching: dpl-1.9.6.gem (100%)
Successfully installed dpl-1.9.6
1 gem installed

travis_time:end:1269e742:start=1525146675307897055,finish=1525146677709894021,duration=2401996966
[0Ktravis_fold:end:dpl_0
[0Ktravis_time:start:00218e50
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m
Fetching: gstore-0.2.1.gem
Fetching: gstore-0.2.1.gem ( 28%)
Fetching: gstore-0.2.1.gem ( 67%)
Fetching: gstore-0.2.1.gem (100%)
Fetching: gstore-0.2.1.gem (100%)
Successfully installed gstore-0.2.1
Fetching: mime-types-2.99.3.gem
Fetching: mime-types-2.99.3.gem (  2%)
Fetching: mime-types-2.99.3.gem (  4%)
Fetching: mime-types-2.99.3.gem (  5%)
Fetching: mime-types-2.99.3.gem (  7%)
Fetching: mime-types-2.99.3.gem (  9%)
Fetching: mime-types-2.99.3.gem ( 11%)
Fetching: mime-types-2.99.3.gem ( 13%)
Fetching: mime-types-2.99.3.gem ( 15%)
Fetching: mime-types-2.99.3.gem ( 16%)
Fetching: mime-types-2.99.3.gem ( 18%)
Fetching: mime-types-2.99.3.gem ( 20%)
Fetching: mime-types-2.99.3.gem ( 22%)
Fetching: mime-types-2.99.3.gem ( 33%)
Fetching: mime-types-2.99.3.gem ( 44%)
Fetching: mime-types-2.99.3.gem ( 55%)
Fetching: mime-types-2.99.3.gem ( 66%)
Fetching: mime-types-2.99.3.gem ( 77%)
Fetching: mime-types-2.99.3.gem ( 88%)
Fetching: mime-types-2.99.3.gem ( 99%)
Fetching: mime-types-2.99.3.gem (100%)
Fetching: mime-types-2.99.3.gem (100%)
Successfully installed mime-types-2.99.3
Fetching: dpl-gcs-1.9.6.gem
Fetching: dpl-gcs-1.9.6.gem (100%)
Fetching: dpl-gcs-1.9.6.gem (100%)
Successfully installed dpl-gcs-1.9.6
3 gems installed

travis_fold:end:dpl.1
travis_fold:start:dpl.2
[33mPreparing deploy[0m
Logging in with Access Key: ****************XFBT

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m
Digest::Digest is deprecated; use Digest

travis_fold:end:dpl.3
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:879:in `initialize': getaddrinfo: Name or service not known (SocketError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/gstore-0.2.1/lib/gstore/request.rb:86:in `_http_do'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/gstore-0.2.1/lib/gstore/request.rb:71:in `signed_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/gstore-0.2.1/lib/gstore/client.rb:40:in `_http_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/gstore-0.2.1/lib/gstore/client.rb:22:in `put'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/gstore-0.2.1/lib/gstore/object.rb:4:in `put_object'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-gcs-1.9.6/lib/dpl/provider/gcs.rb:38:in `block (2 levels) in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-gcs-1.9.6/lib/dpl/provider/gcs.rb:31:in `glob'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-gcs-1.9.6/lib/dpl/provider/gcs.rb:31:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-gcs-1.9.6/lib/dpl/provider/gcs.rb:30:in `chdir'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-gcs-1.9.6/lib/dpl/provider/gcs.rb:30:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

**Comment by prestonvanloon** [comment]
I figured it out. The problem is that travis doesn't support the bucket prefix `gs://` which I intuitively added since this is how `gsutil` references bucket names.

**Comment by BanzaiMan** [comment]
At the moment, gcs provider is not working well (see https://github.com/travis-ci/dpl/issues/792).
