### ISSUE TITLE
The command "pip install --user awscli" failed

### ISSUE THREAD

**Issue by pgarzina** [travis-ci/travis-ci#9584]
this all worked 4 days ago, no changes done to my yml or sh scripts.
Any help appreciated

> The command "pip install --user awscli" failed and exited with 2 during .

```
$ pip install --user awscli
Collecting awscli
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f123d8da950>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/e8/d7/9a01c1e73cfceedacef3f8837797fe5a8d93f2b3d7c6129622d0bf7658ad/awscli-1.15.14-py2.py3-none-any.whl
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f123d8da390>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/e8/d7/9a01c1e73cfceedacef3f8837797fe5a8d93f2b3d7c6129622d0bf7658ad/awscli-1.15.14-py2.py3-none-any.whl
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f123cff6090>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/e8/d7/9a01c1e73cfceedacef3f8837797fe5a8d93f2b3d7c6129622d0bf7658ad/awscli-1.15.14-py2.py3-none-any.whl
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f123cff61d0>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/e8/d7/9a01c1e73cfceedacef3f8837797fe5a8d93f2b3d7c6129622d0bf7658ad/awscli-1.15.14-py2.py3-none-any.whl
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f123cff6310>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/e8/d7/9a01c1e73cfceedacef3f8837797fe5a8d93f2b3d7c6129622d0bf7658ad/awscli-1.15.14-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/e8/d7/9a01c1e73cfceedacef3f8837797fe5a8d93f2b3d7c6129622d0bf7658ad/awscli-1.15.14-py2.py3-none-any.whl (Caused by ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f123cff6410>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)'))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command "pip install --user awscli" failed and exited with 2 during .
Your build has been stopped

```

**Comment by candrews** [comment]
I'm also seeing connection timeout errors trying to reach drupal.org:
```
  - Installing drupal/entity_browser (2.0.0-alpha2): Loading from cache
  - Applying patches for drupal/entity_browser
    https://www.drupal.org/files/issues/entity-browser-view-context-2865928-14.patch (2865928 - The View widget should filter based on field settings)
   Could not apply patch! Skipping. The error was: The "https://www.drupal.org/files/issues/entity-browser-view-context-2865928-14.patch" file could not be downloaded: failed to open stream: Connection timed out
    https://www.drupal.org/files/issues/2877751-17.patch (2877751 - Inform users how many items they can add to a field that uses an entity browser)
   Could not apply patch! Skipping. The error was: The "https://www.drupal.org/files/issues/2877751-17.patch" file could not be downloaded: failed to open stream: Connection timed out
  - Installing drupal/dropzonejs (2.0.0-alpha3): Loading from cache
  - Installing bower-asset/dropzone (v5.1.1): Loading from cache
```

The problem appears to be a networking issue at Travis.

**Comment by darthrevan** [comment]
Same, pip fails to install any packages.

**Comment by rilian** [comment]
same here

**Comment by mplanchard** [comment]
This may be more general than just pip. I'm getting indefinite timeouts running `wget`:

```
$ wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
--2018-05-07 16:20:58--  https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
Resolving releases.hashicorp.com (releases.hashicorp.com)... 151.101.1.183, 151.101.65.183, 151.101.129.183, ...
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.1.183|:443... failed: Connection timed out.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.65.183|:443... failed: Connection timed out.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.129.183|:443... failed: Connection timed out.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.193.183|:443... failed: Connection timed out.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|2a04:4e42::439|:443... failed: Cannot assign requested address.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|2a04:4e42:200::439|:443... failed: Cannot assign requested address.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|2a04:4e42:400::439|:443... failed: Cannot assign requested address.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|2a04:4e42:600::439|:443... failed: Cannot assign requested address.
Retrying.
--2018-05-07 16:29:28--  (try: 2)  https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.1.183|:443... failed: Connection timed out.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.65.183|:443... failed: Connection timed out.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.129.183|:443... failed: Connection timed out.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.193.183|:443... failed: Connection timed out.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|2a04:4e42::439|:443... failed: Cannot assign requested address.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|2a04:4e42:200::439|:443... failed: Cannot assign requested address.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|2a04:4e42:400::439|:443... failed: Cannot assign requested address.
Connecting to releases.hashicorp.com (releases.hashicorp.com)|2a04:4e42:600::439|:443... failed: Cannot assign requested address.
Retrying.
```

**Comment by joshku** [comment]
Just as a FYI - looks like the Python infrastructure team is aware of this and opened up an [incident](https://status.python.org/incidents/zjxwp5lpyn8s)

**Comment by BanzaiMan** [comment]
This should be resolved now. https://www.traviscistatus.com/incidents/0ch1w22m3lwc

If you continue to see the problem, please include build log URL to indicate it.

Thank you.

**Comment by rohitpai-na** [comment]
Seeing this issue again on multiple builds:
```
$ pip install --user awscli
Collecting awscli
/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement awscli (from versions: )
No matching distribution found for awscli
/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
The command "pip install --user awscli" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by di** [comment]
@rohitpai-na PyPI's CDN provider is dropping support for non-SNI clients. Please see https://status.python.org/incidents/hzmjhqsdjqgb and https://github.com/pypa/pypi-support/issues/978 for more details.
