### ISSUE TITLE
builds failing because ConnectTimeoutError

### ISSUE THREAD

**Issue by mikkokotila** [travis-ci/travis-ci#9585]
I started to get this today:

```
Collecting pandas (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb3dc68ef0>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb3dc700b8>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb3dc70240>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb3dc70cc0>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb3ef44be0>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 254, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 147, in _new_conn
    (self.host, self.timeout))
pip._vendor.requests.packages.urllib3.exceptions.ConnectTimeoutError: (<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb3ef44710>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pip._vendor.requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz (Caused by ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb3ef44710>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/pip/_vendor/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
pip._vendor.requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz (Caused by ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb3ef44710>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)'))
The command "pip install -r requirements.txt" failed and exited with 2 during .
Your build has been stopped.
```

**Comment by ThomasWaldmann** [comment]
Same issue here. And I tried to fetch the file from my laptop: that worked.

So it is a travis-related issue, not a pythonhosted site issue.
