### ISSUE TITLE
Android tests failing with error INSTALL_FAILED_DEXOPT

### ISSUE THREAD

**Issue by CDRussell** [travis-ci/travis-ci#9636]
I have a project which has suddenly started failing and I'm not convinced it's because of changes on my end.

You can see an example of this failure [here](https://travis-ci.org/duckduckgo/Android/builds/380708898)

The project is open source, so you can see full project at [DuckDuckGo Android](https://github.com/duckduckgo/android) on GitHub.

I have been trying to investigate what's causing it, and the only thing I can see is that it _might_ be related to using the [test orchestrator](https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator). 

When the orchestrator is _enabled_, the `androidTest` APK fails to install (note, not the actual app APK; it's the test APK which fails).

When the orchestrator is _disabled_, the APK installs and the tests run.

Annoyingly, this used to work just fine and I'm not sure why it is suddenly breaking all of our builds.

```Unable to install /home/travis/build/duckduckgo/Android/app/build/outputs/apk/androidTest/debug/duckduckgo-5.3.1-debug-androidTest.apk
com.android.ddmlib.InstallException: INSTALL_FAILED_DEXOPT
	at com.android.ddmlib.Device.installRemotePackage(Device.java:1029)
	at com.android.ddmlib.Device.installPackage(Device.java:900)
	at com.android.ddmlib.Device.installPackage(Device.java:878)
	at com.android.ddmlib.Device.installPackage(Device.java:867)
	at com.android.builder.testing.ConnectedDevice.installPackage(ConnectedDevice.java:122)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:138)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:52)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
com.android.builder.testing.ConnectedDevice > runTests[test(AVD) - 5.1.1] FAILED 
	com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_DEXOPT
		at com.android.builder.testing.ConnectedDevice.installPackage(ConnectedDevice.java:128)
03:15:11 I/XmlResultReporter: XML test result file generated at /home/travis/build/duckduckgo/Android/app/build/outputs/androidTest-results/connected/TEST-test(AVD) - 5.1.1-app-.xml. Total tests 1, failure 1, 
[no message defined]
java.lang.RuntimeException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_DEXOPT
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_DEXOPT
	at com.android.builder.testing.ConnectedDevice.installPackage(ConnectedDevice.java:128)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:138)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:52)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	... 4 more
Caused by: com.android.ddmlib.InstallException: INSTALL_FAILED_DEXOPT
	at com.android.ddmlib.Device.installRemotePackage(Device.java:1029)
	at com.android.ddmlib.Device.installPackage(Device.java:900)
	at com.android.ddmlib.Device.installPackage(Device.java:878)
	at com.android.ddmlib.Device.installPackage(Device.java:867)
	at com.android.builder.testing.ConnectedDevice.installPackage(ConnectedDevice.java:122)
	... 7 more
:app:connectedDebugAndroidTest FAILED
:app:connectedDebugAndroidTest (Thread[Task worker for ':',5,main]) completed. Took 3 mins 20.474 secs.
FAILURE: Build failed with an exception.
```

**Comment by CDRussell** [comment]
After literally no help or even acknowledgement, auto-closing the issue is disappointing.

**Comment by BanzaiMan** [comment]
I'm sorry that it took a while for us to get back to you. The truth of the matter is that many of us lack the expertise to correctly identify what sort of issues your Android builds may be having.

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
