### ISSUE TITLE
Cloning gh-pages branch failed

### ISSUE THREAD

**Issue by elbaro** [travis-ci/travis-ci#9662]
Installing deploy dependencies
```
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.15.2
Successfully installed public_suffix-3.0.2
Successfully installed addressable-2.5.2
Successfully installed sawyer-0.8.1
Successfully installed octokit-4.6.2
Successfully installed dpl-pages-1.9.6
7 gems installed
!!! GitHub Pages support is experimental !!!
Logged in as @elbaro (elbaro)
Starting deployment of gh-pages branch to GitHub Pages...
The deployment is configured to preserve the target branch if it exists on remote
Created a temporary work directory /tmp/d20180525-27695-1h45yej/work
Trying to clone a single branch gh-pages from existing repo...
```
Preparing deploy

Deploying application
```
Cloning gh-pages branch failed
/home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.6/lib/dpl/provider/pages.rb:142:in `mkdir': File exists @ dir_s_mkdir - /tmp/d20180525-27695-1h45yej/work (Errno::EEXIST)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.6/lib/dpl/provider/pages.rb:142:in `github_pull_or_init'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.6/lib/dpl/provider/pages.rb:196:in `block in push_app'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.6/lib/dpl/provider/pages.rb:191:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

From the message I guess the problem is on the travis side.
Another repo of mine with similar setup works fine.

Failed: https://travis-ci.org/elbaro/vips-rs/builds/383568657
Ok: https://travis-ci.org/elbaro/vips-sys/jobs/372382684

**Comment by BanzaiMan** [comment]
There is no `gh-pages` branch in https://github.com/elbaro/vips-rs, while the other has it. https://github.com/elbaro/vips-sys/tree/gh-pages

I don't know if we should create one if it doesn't exist.

**Comment by elbaro** [comment]
Thanks, manually creating a branch solved the issue.
I suggest automatically creating the branch if not exist.
Otherwise a user needs a [dummy commit](https://github.com/elbaro/vips-rs/commits/gh-pages) to start the branch.
