### ISSUE TITLE
OSError Permission Denied: Installing cookiecutter as a dependency

### ISSUE THREAD

**Issue by heitorlessa** [travis-ci/travis-ci#9753]
Hi everyone,

 First time using Travis so might not be using the correct settings to run this Python project.
  
 After some troubleshooting I can make it consistently fail simply by adding:

```yaml
sudo: false
language: python
python:
  - "3.6"
cache: pip
install:
  - pip install cookiecutter
script:
  - echo "Hello!"
```

Tail of the logs that indicates it tries to create a new folder in a system protected location, however when naturally jumping to a ``-user`` I got a Travis Virtual Env activation issue :( 

Any pointers would be helpful.

---

Debugging info:

 **Build logs**: https://travis-ci.org/aws-samples/cookiecutter-aws-sam-pipeline/builds/392909859

```bash
Installing collected packages: future, urllib3, certifi, idna, chardet, requests, poyo, binaryornot, MarkupSafe, jinja2, click, whichcraft, python-dateutil, arrow, jinja2-time, cookiecutter
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/lib/python3.6'
The command "pip install cookiecutter" failed and exited with 2 during .
```

**``pip install --user cookiecutter`` Build logs**: https://travis-ci.org/aws-samples/cookiecutter-aws-sam-pipeline/builds/392911194

```bash
/home/travis/.travis/job_stages: line 57: /home/travis/virtualenv/python3.6_with_system_site_packages/bin/activate: No such file or directory
The command "source ~/virtualenv/python3.6_with_system_site_packages/bin/activate" failed and exited with 1 during .
```

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
